# -*- coding: utf-8 -*-
PATCH = {
'schedule.message': '📅 Programar mensaje',
'schedule.export_text': '📤 Exportar',
'schedule.without_bot_warning': '🤖 Para programar necesitas un bot remitente. Conéctalo para tu canal — toma un minuto.',
'schedule.confirm_change': '✅ ¿Confirmar cambio?',
'schedule.confirm_no': '❌ No, dejar como está',
'schedule.confirm_yes': '✅ Sí, cambiar',
'schedule.new_posts': '📤 Programar más',
'schedule.past_date': '❌ La fecha ya pasó.',
'schedule.review_change_date': '📅 ¿Cambiar fecha/hora programada?',
'schedule.package_notice': '📦 Paquete: {count} mensaje(s)',
'schedule.managed_by_sender_bot': '📋 Gestionado por @{bot} en {channel} (@{channel_username})',
'schedule.review_title': '📝 <b>Revisión</b>\n\nCanales: {channels}\nHora: {datetime}\n\n{preview}',
'schedule.review_media': '📷 Medios: {media}',
'schedule.error': '❌ Error al programar: {error}',
'schedule.review_change': '⚙️ Cambiar ajustes',
'schedule.review_change_channel': '📢 Cambiar canal',
'schedule.review_change_media': '💾 Cambiar medios',
'schedule.to_channels': '📢 Enviando a: {channels}',
'schedule.review_buttons': '🔘 Botones inline: {count}',
'schedule.review_question': '❓ ¿Quieres cambiar algo?',
'schedule.review_choose_channels': '📢 Elegir canales',
'schedule.review_edit': '✏️ Editar',
'schedule.review_schedule': '✅ Programar',
'schedule.edit_replaced': '✅ Mensaje reemplazado. La versión anterior ya no está programada.',
'schedule.edit_date_updated': '✅ Fecha/hora actualizada. La versión anterior ya no está programada.',
'schedule.edit_media_received': '📎 Medios recibidos ({count}). Envía más o pulsa <b>Listo</b>.',
'schedule.edit_done': '✅ Listo',
'schedule.edit_media_choice_prompt': '📎 Nuevos medios recibidos. ¿Qué hago con ellos?',
'schedule.edit_media_add': '➕ Añadir a la selección',
'schedule.edit_media_replace': '🔄 Reemplazar medios actuales',
'schedule.edit_media_replace_storage': '💾 Reemplazar desde almacén',
'schedule.edit_media_mode_prompt': '🎲 ¿Cómo usar {count} archivos en tus publicaciones?',
'schedule.edit_content_updated': '✏️ Contenido actualizado.',
'schedule.edit_nothing': '❌ Envía tu mensaje editado o medios.',
'timezone.btn': '🕐 Zona horaria',
'timezone.change': 'Cambiar zona horaria',
'timezone.prompt_method': '🕐 <b>Cambiar zona horaria</b>\n\nElige cómo ponerla:',
'timezone.set_city_btn': '🏙 Escribir ciudad',
'timezone.set_location_btn': '📍 Enviar ubicación',
'timezone.set_time_btn': '🕐 Enviar hora',
'timezone.city_found': '🏙 Ciudad: <b>{city}</b>\nZona horaria: <b>{tz}</b>\n\n¿Es correcto?',
'timezone.city_not_found': '❌ Ciudad <b>{city}</b> no encontrada.',
'timezone.location_found': '📍 Zona detectada: <b>{tz}</b>\n¿Es correcto?',
'timezone.location_not_found': '❌ No pude detectar la zona con esa ubicación.',
'timezone.time_found': '🕐 Según tu hora ({time}), tu zona es <b>{tz}</b>.\n¿Es correcto?',
'timezone.time_not_found': '❌ No pude determinar la zona con esa hora.',
'timezone.detect_confirm_btn': '✅ Correcto',
'timezone.detect_wrong_btn': '❌ Mal — reintentar',
'timezone.apply_all': 'Aplicar a todos los canales',
'timezone.manage_title': '🕐 <b>Zona horaria</b>\n\nActual: <b>{tz}</b>\nAcciones disponibles:',
'timezone.per_channel_set': '✅ Zona de {channel} puesta a <b>{tz}</b>.',
'timezone.apply_all_confirm': '¿Aplicar <b>{tz}</b> a todos tus canales?',
'timezone.apply_all_done': '✅ Zona <b>{tz}</b> aplicada a {count} canales.',
'timezone.apply_all_cancelled': '❌ Actualización masiva cancelada.',
'timezone.no_channels': 'Sin canales conectados. Conecta uno primero.',
'timezone.detect_time_prompt': '🕐 ¿Qué hora es ahora para ti?\n\nEnvía en formato HH:MM (24h), p. ej. <code>15:30</code>.',
'timezone.set': '✅ Zona horaria puesta a {tz}.',
'timezone.hint': 'Zona actual: {tz}',
'timezone.select_prompt': '🌍 Elige tu zona horaria:',
'timezone.detected': '🌍 Zona detectada: {tz}',
'timezone.auto_detect': '🔄 Detectar auto',
'timezone.command': '/timezone — Cambiar tu zona horaria',
'tutorial.skip_btn': '⏭ Omitir tutorial',
'tutorial.next_btn': '▶️ Siguiente',
'tutorial.skip_confirm': '¿Seguro que quieres omitir el tutorial?',
'tutorial.skip_confirm_yes': '✅ Sí, omitir',
'tutorial.skip_confirm_no': '❌ No, continuar',
'tutorial.skipped': 'Tutorial omitido. Usa /help si necesitas ayuda.',
'tutorial.about_next_btn': '▶ Continuar',
'tutorial.connect_channel_btn': '📡 Conectar canal',
'tutorial.welcome': '👋 ¡Bienvenido! Te muestro cómo funciona.\n\n<b>Paso 1:</b> Conecta un canal.\nReenvíame cualquier mensaje de tu canal para verificar que eres admin.\n\nPulsa <b>Omitir</b> si lo harás después.',
'tutorial.channel_connected': '✅ ¡Canal conectado! Ya puedes programar.\n\n<b>Paso 2:</b> Usa /schedule para tu primera publicación.\n\nPulsa <b>Listo</b> para terminar.',
'tutorial.tz_text': '🕐 <b>Zona horaria</b>\n\nPongamos tu zona para enviar a la hora local correcta.',
'tutorial.tz_send_location': '📍 Enviar ubicación',
'tutorial.tz_send_time': '🕐 Enviar hora',
'tutorial.tz_type_city': '🏙 Escribir ciudad',
'tutorial.tz_city_found': '🏙 ¿<b>{city}</b> es tu ciudad?\n\nZona: <b>{tz}</b>',
'tutorial.tz_saved': '✅ Zona puesta a <b>{tz}</b>.',
'tutorial.tz_city_prompt': '🏙 Escribe tu ciudad (p. ej. Madrid, Ciudad de México, Buenos Aires):',
'tutorial.tz_time_prompt': '🕐 ¿Qué hora es ahora?\n\nEnvía en HH:MM (24h). Ejemplo: <code>15:30</code>.',
'tutorial.tz_skip': '⏭ Omitir zona horaria',
'tutorial.contact_support': '💬 Contactar soporte',
'tutorial.complete': '🎉 <b>¡Tutorial completado!</b>\n\nYa puedes usar Fast Scheduler.\n\n<b>Guía rápida:</b>\n• 📅 <b>Programar</b> tu primer post\n• 📢 <b>Canal</b> para gestionar canales\n• 🤖 <b>Bots</b> para conectar remitente\n• 📊 <b>Estadísticas</b> de rendimiento\n\n¿Ayuda? Usa /help.',
}
