# -*- coding: utf-8 -*-
PATCH = {
'channel.tz_line': 'Hora: {tz}',
'channel.bot_tag': 'Bot: @{bot}',
'channel.connected': 'Canal <b>{channel}</b> conectado.',
'channel.connected_basic': 'Canal conectado. Ya puedes programar mensajes.',
'channel.connected_success_user': 'Canal <b>{channel}</b> conectado. La confirmación completa te llegó por el bot principal.',
'channel.connected_all_set': 'Todo listo. El canal <b>{channel}</b> está preparado. {count} mensaje(s) pendientes vinculados.',
'channel.channel_hidden_done': 'El canal ahora está oculto para extraños.',
'channel.channel_visible_done': 'El canal ahora es visible para extraños.',
'channel.invalid_message': 'Reenvía un mensaje <b>de tu canal</b>, no de un chat privado o grupo.',
'channel.max_reached': 'Límite de canales alcanzado ({limit}). Desconecta uno o pasa a Premium.',
'channel.invalid_channel_format': 'Formato de canal no válido.',
'channel.redirect_count': '{count} mensaje(s) programados movidos a este canal.',
'channel.redirect_recurring_count': '{count} recurrente(s) mantienen su canal anterior. Actualízalos aparte.',
'channel.pick_free': 'Gratis: {channel}',
'channel.pick_managed': 'Gestionado: {channel}',
'channel.has_bot': 'El canal tiene bot: @{bot}',
'channel.no_bot': 'Sin bot conectado a este canal.',
'channel.visibility_hidden': 'Oculto (se muestra como canal privado)',
'channel.check_off': 'No',
'channel.check_on': 'Sí',
'channel.limit_premium': 'Gratis solo 1 canal. Premium hasta 3 canales.',
'channel.premium_notice': 'Función Premium: programa a varios canales a la vez.',
'channels.connected_line': 'Conectado: {channel}',
'premium.badge': 'Premium',
'premium.plans_comparison_btn': 'Comparar planes',
'premium.features_btn': 'Funciones',
'premium.activated_date': 'Premium activo hasta {date}.',
'premium.status_line_free': 'Plan gratuito',
'premium.status_line_paid': 'Premium activo',
'stats_title': 'Estadísticas',
'stats_note_text': 'Datos de tu canal.',
'stats_select_metric': 'Elige métrica:',
}
