# -*- coding: utf-8 -*-
PATCH = {
'channel.btn': '📢 Canal',
'channel.menu_title': '📢 <b>Mis canales</b>',
'channel.connect_new': '➕ Conectar canal',
'channel.prompt': '📢 <b>Conectar canal</b>\n\nEnvíame @tucanal o reenvíame cualquier mensaje del canal.',
'channel.connected': '✅ ¡Canal conectado!',
'channel.disconnected': '✅ Canal desconectado.',
'channel.not_found': '❌ Canal no encontrado.',
'channel.invalid_link': '❌ Enlace no válido.',
'channel.max_reached': '❌ Límite de canales alcanzado.',
'channel.sender_bot_required': '🤖 Este canal necesita un bot remitente.',
'channels.btn': '📢 Canales',
'referral.program': '🎁 Referidos',
'referral.copy_link': '📋 Copiar enlace',
'referral.locked_text': '🔒 Completa la verificación para desbloquear referidos.',
'referral.no_referrals_yet': 'Aún sin referidos. Comparte tu enlace.',
'referral.activate_premium_referral': 'Activar {avail} días de referido',
'referral.no_referral_days': 'No tienes días de referido.',
'rate.first_schedule': '⭐ ¿Te gusta Fast Scheduler? ¡Déjanos 5 estrellas!',
'rate.high_thanks': '🙏 ¡Gracias por tu valoración!',
'rate.support_bot_btn': '🤖 Bot de soporte',
'rate.add_review_btn': '✏️ Dejar reseña',
'premium.menu_title': '⭐ <b>Premium</b>',
'premium.status': 'Estado Premium',
'premium.badge': '⭐ Premium',
'premium.menu_text': '⭐ <b>Premium</b>\n\nDesbloquea 3 canales, mensajes ilimitados, estadísticas y más.',
'premium.features_btn': '✨ Funciones',
}
