# -*- coding: utf-8 -*-
"""Big batch 6a: translate all 310 main help titles/nav to natural Spanish.
Uses explicit overrides for top items + term mapper for the rest.
Only applies when EN has no placeholders (titles never do) to stay safe.
"""
MANUAL = {
'help.btn': 'Ayuda',
'help.open_in_web': 'Abrir en web',
'help.command': 'Centro de ayuda',
'help.text': 'Centro de ayuda Elige un tema para saber mas de Fast Scheduler.',
'help.center_intro': 'Bienvenido al centro de ayuda. Explora temas o busca respuestas.',
'help.title': 'Ayuda y comandos',
'help.commands.title': 'Comandos de texto',
'help.start.title': 'Primeros pasos',
'help.recurring.title': 'Mensajes recurrentes',
'help.delete.title': 'Borrar mensajes',
'help.premium.title': 'Premium',
'help.language.title': 'Idioma',
'help.feedback.title': 'Opinion y soporte',
'help.search.title': 'Buscar mensajes',
'help.backup.title': 'Copia de seguridad',
'help.calendar.title': 'Vista calendario',
'help.export.title': 'Exportar',
'help.import.title': 'Importar',
'help.formatting.title': 'Formato y botones',
'help.advertising.title': 'Publicidad',
'help.admins.title': 'Admins',
'help.faq.title': 'Preguntas frecuentes',
'help.errors.title': 'Solucion de problemas',
'help.contact.title': 'Contacto y soporte',
'help.channels.title': 'Canales',
'help.bots.title': 'Bots remitentes',
}
TERMS = [
('Frequently Asked Questions','Preguntas frecuentes'),
('How Admins Share Limits','Como comparten limites los admins'),
('Permissions & Requests','Permisos y solicitudes'),
('Ownership Transfer','Transferencia de propiedad'),
('What Is Excluded','Que se excluye'),
('What Is Backed Up','Que se guarda'),
('Backup Password','Clave de copia'),
('Restore Backup','Restaurar copia'),
('Scheduled Backups','Copias programadas'),
('Backup Size','Tamano de copia'),
('Add a Sender Bot','Anadir bot remitente'),
('Bot Fleet','Flota de bots'),
('Manage Sender Bots','Gestionar bots'),
('Bot Permissions','Permisos del bot'),
('Remove a Sender Bot','Eliminar bot'),
('Rotate Token','Rotar token'),
('Posting as Your Bot','Publicar como tu bot'),
('Channel Stats & Leaderboards','Stats y rankings'),
('Bot Status','Estado del bot'),
('Sender Bots','Bots remitentes'),
('Add a Channel','Anadir canal'),
('Connect the Bot','Conectar el bot'),
('Default Channel','Canal por defecto'),
('Permanent Link','Enlace permanente'),
('Manage Channels','Gestionar canales'),
('Channel Permissions','Permisos del canal'),
('How Posting Works: Sender Bots','Como publicar: bots remitentes'),
('Remove a Channel','Eliminar canal'),
('Signature Position','Posicion de firma'),
('Channel Stats','Stats del canal'),
('Unlink vs Delete','Desvincular vs borrar'),
('All Commands','Todos los comandos'),
('Settings & Configuration','Ajustes'),
('Connecting a Bot','Conectar un bot'),
('Connecting a Channel','Conectar un canal'),
('Contact & Support','Contacto y soporte'),
('Report a Bug','Reportar error'),
('Request a Feature','Pedir funcion'),
('Response Time','Tiempo de respuesta'),
('Telegram Support','Soporte Telegram'),
('Supported Content Types (Free Plan)','Contenidos soportados (gratis)'),
('Edit Messages','Editar mensajes'),
('Channel Errors','Errores de canal'),
('Common Errors','Errores comunes'),
('Media Errors','Errores de medios'),
('Network Errors','Errores de red'),
('Payment Errors','Errores de pago'),
('Rate Limited','Limite excedido'),
('Export a Chat','Exportar chat'),
('CSV Export','Exportar CSV'),
('Export Data','Exportar datos'),
('JSON Export','Exportar JSON'),
('Plain Text','Texto plano'),
('Account FAQ','Cuentas: preguntas'),
('Best Practices','Buenas practicas'),
('Create Backup','Crear copia'),
('Verify','Verificar'),
('Cloud','Nube'),
('Download','Descargar'),
('Signature','Firma'),
('Settings','Ajustes'),
('Support','Soporte'),
('Contact','Contacto'),
('Email','Correo'),
('Forbidden','Prohibido'),
('Timeouts','Tiempos de espera'),
('Formats','Formatos'),
('Feedback','Opinion'),
('Language','Idioma'),
('Import','Importar'),
('Export','Exportar'),
('Backup','Copia'),
('Calendar View','Calendario'),
('Premium','Premium'),
]
def translate_title(s):
  t = s
  for en_, es_ in TERMS:
    t = t.replace(en_, es_)
  return t
