# -*- coding: utf-8 -*-
PATCH = {
'import.btn': 'Importar',
'import.export_title': 'Exportar / Importar',
'import.export_menu_text': 'Exportar / Importar Gestiona tus datos: exporta todo como archivo, importa desde export previo, crea y restaura copias.',
'import.instructions': 'Importar datos Enviame un JSON exportado de Fast Scheduler. La importacion mezcla datos y sobrescribe coincidentes.',
'import.file_missing': 'Envia un JSON valido.',
'import.invalid_format': 'Formato no valido. Envia un JSON.',
'import.success': 'Importacion ok. Mensajes: {messages} Canales: {channels} Bots: {bots}',
'import.error_version': 'Este export es de otra version. Puede requerir update.',
'import.error_generic': 'Fallo importar: {error}',
'import.merge_options_title': 'Opciones de import',
'import.merge_keep_existing': 'Conservar existentes (omitir dupes)',
'import.merge_overwrite': 'Sobrescribir',
'import.merge_add': 'Anadir todo (conservar dupes)',
'import.merge_mode_chosen': 'Modo import: {mode}',
'import.file_too_large': 'Archivo muy grande. Maximo: {limit} MB.',
'import.file_size_limit': 'Archivo muy grande (max {limit} MB).',
'import.file_wrong_extension': 'Envia un .json.',
'import.processing': 'Procesando import...',
'import.preview': 'Vista previa:',
'import.confirm_btn': 'Confirmar import',
'import.cancel_btn': 'Cancelar',
'import.global_error': 'Error import: {error}',
'import.link_invalid': 'Enlace de import no valido.',
'import.no_file': 'Sin archivo. Envia el export.',
'import.no_valid_messages': 'Sin mensajes validos en el import.',
'import.overflow_cancelled': 'Import cancelado por exceso de limite.',
'import.file_received': 'Import desde <b>{filename}</b> ok.',
'import.photo_received': 'Foto recibida ({n}/{total})',
'import.prompt': 'Envia un JSON exportado de Fast Scheduler.',
'import.session_expired': 'Sesion de import expirada. Empieza de nuevo.',
'import.setdate_notes': 'Mensajes SetDate se importan como programados normales.',
'import.tz_change_account': 'Cambiar zona de cuenta',
'import.tz_remember': 'Recordar mi eleccion',
'import.tz_use_account': 'Usar zona de cuenta',
'import.tz_use_file': 'Usar zona del archivo',
'import.without_photos': 'Omitir fotos',
'import.from_storage': 'Importar desde almacen',
'import.send_random_photos': '{count} foto(s) random adjuntas.',
'import.tz_mismatch': 'Zona distinta: archivo usa {file_tz}, tu cuenta {user_tz}. Elige cual usar:',
'import.item_normal': '#{job_id} — {dt}',
'import.overflow': '{count} mensaje(s) exceden limite.',
'import.overflow_first_n': 'Primeros {n} guardados.',
'import.overflow_last_n': 'Ultimos {n} guardados.',
'import.limit_overflow': 'Exceso: {available} libres, {total} total, {current} actual, {limit} max, {overflow} sobra.',
'import.item_base': '#{job_id} — {dt}',
'import.error': 'Error import: {error}',
'import.item_sequential': '#{job_id} — {dt} (secuencial)',
'import.item_random': '#{job_id} — {dt} (random)',
'import.cancelled': 'Import cancelado.',
'media.only_allowed': 'Solo archivos media (fotos, videos, docs).',
'media.receive_status': 'Medios recibidos ({count}). Envia mas o pulsa Listo.',
'media.storage': '@@STORAGE@@Almacen de medios',
'media.storage_title': '@@STORAGE@@Almacen de medios Guarda y reutiliza archivos en tus programados.',
'media.storage_empty': '@@STORAGE@@Sin archivos aun.',
'media.storage_full': '@@STORAGE@@Almacen lleno ({count}/{limit}). Borra o pasa a Premium.',
'media.storage_limit_reached': '@@STORAGE@@Limite de almacen alcanzado ({limit}).',
'media.my_storages_btn': '@@STORAGE@@Mis almacenes',
'media.use_from_storage': '@@STORAGE@@Usar desde almacen',
}
