# -*- coding: utf-8 -*-
PATCH = {
'premium.status': 'Premium: {status}',
'premium.unsupported_title': 'Este contenido aun no se puede enviar:',
'premium.sticker_warning': 'Stickers Premium no se pueden enviar — solo cuentas Telegram Premium pueden, y un bot nunca es Premium.',
'premium.rich_warning': 'Articulos con formato aun no se pueden enviar — requiere que el dueno tenga Telegram Premium. Se enviara como texto plano.',
'premium.status_frozen': 'Congelado',
'premium.status_text': 'Premium',
'premium.menu_text': 'Suscripcion Premium Tu plan: {plan} GRATIS Recurrentes: {recurring_free} (expira en 1 ano) Canales: {channels_free} Bots: {bots_free} Estadisticas: promedios (Premium full) Videos en programados: {videos_msg_free} Videos en almacen: {videos_storage_free} Total medios: {media_items_free} 4K: {allow_4k_free} Prioridad: standard Compresion: {compression_free} Ranking: no Auto-reportes: solo Premium PREMIUM Recurrentes: {recurring_prem} Canales: {channels_prem} Bots: {bots_prem} Estadisticas: reportes ilimitados, ranking, datos por post Videos programados: {videos_msg_prem} Videos almacen: {videos_storage_prem} Total medios: {media_items_prem} 4K: {allow_4k_prem} Prioridad: prioritaria Compresion: {compression_prem} Ranking: si Auto-reportes: ilimitados',
'premium.value_intro': 'Ahorra tiempo gestionando tu canal. Prepara semanas de contenido, ten tus medios listos y deja que Fast Scheduler entregue mientras creces.',
'premium.menu_stats_premium': 'Estadisticas: reportes ilimitados, ranking, datos por post',
'premium.menu_stats_free': 'Estadisticas: solo promedios (Premium full)',
'premium.menu_leaderboard_premium': 'Ranking: por reacciones, rangos, top 100, filtros',
'premium.menu_leaderboard_free': 'Ranking: solo Premium',
'premium.menu_senderbot_premium': 'Gestion remitente: funciones completas',
'premium.menu_senderbot_free': 'Gestion remitente: limitada (Premium full)',
'premium.menu_autoreports_premium': 'Auto-reportes: ilimitados',
'premium.menu_autoreports_free': 'Auto-reportes: solo Premium',
'premium.activated_lifetime': 'Premium activado. Ahora activo con duracion de por vida.',
'premium.activated_date': 'Premium activado. Tu Premium ({plan}) activo hasta {date}.',
'premium.status_line_paid': 'Premium activo {expires} Auto-renovacion: {autorenew}',
'premium.status_line_paid_cancelled': 'Premium activo Expira: {expires} (auto-renovacion cancelada)',
'premium.next_renewal': 'Proxima renovacion',
'premium.status_details': 'Estado Premium Plan: {plan} Estado: {status} Inicio: {started} Expira: {expires} Auto-renovacion: {autorenew}',
'premium.not_active': 'Premium no activo en tu cuenta.',
'premium.expiration_unknown': 'Desconocido',
'premium.start_unknown': 'Desconocido',
'premium.required': 'Funcion Premium Requiere Premium activo. Desbloquea: mas limites, videos, estadisticas y ranking, copia y exportacion.',
'premium.comparison_free': 'Plan gratis {monthly_sent_free} envios por canal/mes Hasta {scheduled_free} programados Hasta {recurring_free} recurrentes Hasta {channels_free} canal Hasta {bots_free} bot',
}
