# -*- coding: utf-8 -*-
PATCH = {
'monthly_sent_reached_alert': 'Limite mensual alcanzado en este canal ({limit}/mes). Mensaje {job_id} no enviado.',
'monthly_standard_option': 'Standard mensual — {price}/mes',
'monthly_three_option': '3 meses — {price} (ahorra {full_price})',
'monthly_six_option': '6 meses — {price} (ahorra {full_price})',
'monthly_pay_monthly_note': 'Pagando mes a mes: 3 meses = {three_month_total}, 6 meses = {six_month_total}',
'multi_month_discount_note': 'Descuento prepago: {percent}% — pagas {discounted} en vez de {price}.',
'expiry.day0_title': 'Premium expirado',
'expiry.day0_info': 'Tu Premium expiro. Los mensajes se seguiran enviando a todos tus canales por <b>{days} dias</b>. Nada congelado aun.',
'expiry.day0_footer': 'Renueva Premium en 2 semanas para no perder acceso. @@STORAGE@@ Tambien elegiras que almacen guardar.',
'expiry.excess_channels': 'Canales sobrantes ({count}):',
'expiry.excess_bots': 'Bots sobrantes ({count}):',
'expiry.day3_title': 'Los mensajes paran manana',
'expiry.day3_info': 'Recordatorio: en <b>1 dia</b> paran los envios a tus canales congelados. Quedaran congelados 11 dias mas.',
'expiry.day3_footer': 'Renueva Premium para recuperar todo.',
'expiry.day4_title': 'Envios detenidos',
'expiry.day4_info': 'Los mensajes a tus canales congelados se detuvieron. Seguirán conectados pero congelados. Se desconectaran en unas 3 semanas si no renuevas.',
'expiry.day4_footer': 'Renueva Premium para reanudar envios y conservar canales.',
'expiry.backup_sent_title': 'Tu copia de seguridad',
'expiry.backup_sent_info': 'Como tu Premium expiro, preparamos una copia completa de tus datos. Usala para restaurar canales, bots y mensajes si renuevas despues.',
'expiry.backup_marketing': 'Renueva cuando quieras y sigue donde quedaste — tus datos seguiran aqui.',
'expiry.day14_title': '2 semanas sin Premium',
'expiry.day14_info': 'Tus canales y bots llevan 2 semanas congelados. Quedan <b>{weeks} semanas</b> antes de desconexion permanente. Activos en riesgo:',
'expiry.day14_footer': 'Renueva Premium para conservar todo.',
'expiry.day15_title': 'Premium expirado — 15 dias',
'expiry.day15_info': 'Tus canales y bots siguen congelados. En unos 20 dias se desconectaran y se borraran los datos. Enviaremos un aviso final.',
'expiry.day15_footer': 'Renueva Premium antes de que sea tarde.',
'expiry.disconnect_warn_title': 'Aviso final: desconexion en 12 horas',
'expiry.disconnect_warn_info': 'Ultima oportunidad. En <b>{hours} horas</b> se desconectaran estos activos. Los mensajes programados y datos que excedan el plan gratis se borraran.',
'expiry.disconnect_warn_footer': 'Renueva Premium ya para conservar canales, bots y datos.',
'expiry.disconnected_title': 'Activos sobrantes desconectados',
'expiry.disconnected_info': 'Tus canales y bots sobrantes fueron desconectados. Activos afectados:',
'expiry.disconnected_channels': 'Canales desconectados ({count}):',
'expiry.disconnected_bots': 'Bots desconectados ({count}):',
'expiry.disconnected_footer': 'Tus usuarios de canales y bots quedaron guardados en tu cuenta. Puedes reconectarlos si vuelves a Premium.',
'expiry.media_choice_title': '@@STORAGE@@Conserva tu almacen',
'expiry.media_choice_info': '@@STORAGE@@Tu Premium expiro. Puedes conservar <b>un</b> almacen. @@STORAGE@@ Los demas se borraran, y el conservado se recorta a 100 items (videos primero). @@STORAGE@@ Elige cual conservar:',
'expiry.media_keep_btn': '{name} ({count} items)',
'expiry.media_choice_saved': '@@STORAGE@@Eleccion de almacen guardada.',
'expiry.media_choice_confirmed': '@@STORAGE@@Eleccion guardada. Tu almacen elegido se conserva. Los demas se borran tras el periodo de gracia. @@STORAGE@@ El conservado se recorta a 100 items (videos primero).',
'expiry.media_deletion_title': '@@STORAGE@@Limpieza de almacen',
'expiry.media_deletion_info': '@@STORAGE@@La limpieza sera en <b>{days} dias</b>. @@STORAGE@@ Si no elegiste almacen, borraremos todo. @@STORAGE@@ Elige en el menu.',
'expiry.media_deletion_footer': 'Pasa a Premium para conservar todo.',
'expiry.choice_title': 'Elige que conservar',
'expiry.choice_info': 'Tu Premium expiro. Puedes conservar hasta <b>{channels} canal(es)</b>. El bot del canal conservado sigue con el; los demas se congelan. Elige abajo.',
'expiry.choice_channels_header': 'Canales (conserva hasta {limit}):',
'expiry.choice_bots_header': 'Bots (conserva hasta {limit}):',
'expiry.choice_recurring_header': 'Recurrentes (conserva 1):',
'expiry.choice_help': 'Toca un boton para activar/desactivar. Luego pulsa Guardar.',
'expiry.choice_keep_btn': 'Conservar {name}',
'expiry.choice_remove_btn': 'Quitar {name}',
'expiry.choice_save_btn': 'Guardar seleccion',
'expiry.choice_limit_reached': 'Solo puedes conservar hasta {limit}.',
'expiry.choice_no_channels': 'Debes conservar al menos un canal.',
'expiry.choice_saved_alert': 'Seleccion guardada.',
'expiry.choice_confirmed_title': 'Seleccion guardada',
'expiry.choice_confirmed_info': 'Elegiste conservar <b>{channels} canal(es)</b>. Sus bots siguen activos. El resto queda congelado y se desconectara.',
'expiry.scheduled_excess_title': 'Mensajes sobre el limite',
'expiry.scheduled_excess_info': 'Tienes <b>{count}</b> programados, pero tu plan gratis solo permite <b>{limit}</b>. Tras 3 dias de gracia, los sobrantes no se enviaran.',
'expiry.scheduled_excess_footer': 'Pasa a Premium para enviar todo, o descarga una copia para proteger tus datos.',
'expiry.download_scheduled_btn': 'Descargar copia completa (.fsback)',
'expiry.download_scheduled_caption': 'Tu copia completa (.fsback). Trae todo — programados, recurrentes, canales, bots, medios y ajustes. Guardala: la restauras con /import.',
'expiry.download_scheduled_sent': 'Copia enviada. Importala cuando quieras con /import.',
'expiry.cmd_grace_title': 'Premium expirado — recordatorio',
'expiry.cmd_grace_info': 'No renovaste Premium. En <b>{days} dia(s)</b> paran los envios a los canales no conservados y se congelaran. Tus bots extra se apagaran en unas 3 semanas.',
'expiry.cmd_grace_footer': 'Renueva Premium para que todo siga funcionando.',
}
