# -*- coding: utf-8 -*-
TERMS2 = [
('Billing FAQ','Preguntas de facturacion'),
('Sender Bot FAQ','Preguntas de bot remitente'),
('Migration FAQ','Preguntas de migracion'),
('Payment FAQ','Preguntas de pago'),
('Scheduling FAQ','Preguntas de programacion'),
('Security FAQ','Preguntas de seguridad'),
('Telegram FAQ','Preguntas de Telegram'),
('Tips FAQ','Preguntas de consejos'),
('Troubleshooting FAQ','Preguntas de errores'),
('API FAQ','Preguntas de API'),
('Storage FAQ','Preguntas de almacen'),
('Bug Reports','Reportar errores'),
('Feature Requests','Pedir funciones'),
('Other','Otros'),
('Payment Issues','Problemas de pago'),
('Attachments','Adjuntos'),
('History','Historial'),
('Replies','Respuestas'),
('Status Meanings','Estados'),
('Getting Started','Primeros pasos'),
('Glossary','Glosario'),
('Channel','Canal'),
('Recurring','Recurrentes'),
('Sender Bot','Bot remitente'),
('Media Storage','Almacen de medios'),
('Step 1: Connect a Channel','Paso 1: conecta un canal'),
('Step 2: Connect a Sender Bot','Paso 2: conecta un bot'),
('Step 3: Schedule a Message','Paso 3: programa un mensaje'),
('Sync Across Bots','Sincronizar bots'),
('Legal & Terms','Legal y terminos'),
('Your Data','Tus datos'),
('Privacy Policy','Privacidad'),
('Privacy Details','Detalles de privacidad'),
('Legal Terms','Terminos legales'),
('Terms Details','Detalle de terminos'),
('Sender Bot Limit','Limite de bots'),
('Channel Limit','Limite de canales'),
('Monthly Send Limit','Limite mensual'),
('Raise Limits','Subir limites'),
('Media Limit','Limite de medios'),
('Raise Bots','Mas bots'),
('Raise Channels','Mas canales'),
('Raise Send Limits','Mas envios'),
('Raise Storage','Mas almacen'),
('Recurring Limit','Limite recurrentes'),
('Scheduled Limit','Limite programados'),
('Storage Limit','Limite almacen'),
('Limits','Limites'),
('Free Plan Limits','Limites gratis'),
('Premium Plan Limits','Limites Premium'),
('Media Compression & Retention','Compresion y retencion'),
('Media Selection Types','Tipos de seleccion'),
('Message List','Lista de mensajes'),
('Archive','Archivo'),
('Manage Box','Gestionar caja'),
('Storage Boxes','Cajas de almacen'),
('Copying Items Between Boxes','Copiar entre cajas'),
('Create a Box','Crear caja'),
('Delete Media','Borrar medios'),
('Stored Documents','Docs guardados'),
('Using From Storage','Usar desde almacen'),
('Storage Limits','Limites de almacen'),
('Manage Storage','Gestionar almacen'),
('Move Media','Mover medios'),
('Stored Photos','Fotos guardadas'),
('Storage on Premium','Almacen en Premium'),
('Preview','Vista previa'),
('Quota','Cuota'),
('Rename Box','Renombrar caja'),
('Premium','Premium'),
('Admins','Admins'),
]
def translate2(s):
  t = s
  for en_, es_ in TERMS2:
    t = t.replace(en_, es_)
  return t
