# -*- coding: utf-8 -*-
PATCH = {
'backup.btn': 'Crear copia',
'backup.title': 'Copia de seguridad. Tus datos estan a salvo. Crea copia de todo. Restaura desde copia previa.',
'backup.created': 'Copia creada con exito.',
'backup.failed': 'Fallo la copia: {error}',
'backup.restored': 'Copia restaurada con exito.',
'backup.restore_failed': 'Fallo restaurar: {error}',
'backup.delete_confirm': 'Borrar esta copia?',
'backup.deleted': 'Copia borrada.',
'backup.list_empty': 'Sin copias.',
'backup.list_header': 'Tus copias',
'backup.info_size': 'Tamano: {size}',
'backup.info_date': 'Fecha: {date}',
'backup.confirm_password': 'Confirma la clave de la copia:',
'backup.enter_password': 'Pon clave para proteger esta copia:',
'backup.export_button': 'Exportar copia',
'backup.generating': 'Generando copia...',
'backup.hint_prompt': 'Anade una pista para recordar tu clave:',
'backup.import_protected': 'Esta copia tiene clave. Ponla:',
'backup.invalid_file': 'Archivo de copia no valido.',
'backup.no_data': 'Sin datos para copiar.',
'backup.password_mismatch': 'Las claves no coinciden.',
'backup.restore_add': 'Anadir a datos existentes',
'backup.restore_mode_prompt': 'Elige modo de restauracion:',
'backup.restore_overwrite': 'Sobrescribir datos',
'backup.select_title': 'Elige copia a restaurar:',
'backup.show_hint': 'Mostrar pista',
'backup.wrong_password_last': 'Clave mal. Ultimo intento.',
'backup.import_error': 'Error al importar copia: {error}',
'backup.import_success': 'Importacion ok. Mensajes: {messages} Canales: {channels} Bots: {bots}',
'backup.backup_import_success': 'Importacion ok. Mensajes: {messages} Canales: {channels} Bots: {bots}',
'backup.locked': 'Copia bloqueada. Intenta en {minutes}m {seconds}s.',
'backup.locked_timer': 'Espera {minutes}m {seconds}s',
'backup.wrong_password': 'Clave mal. Quedan {attempts} intento(s).',
'backup.export': 'Exportar copia',
'backup.hint': 'Pista: {hint}',
'backup.full': 'Copia completa',
'backup.select_separately': 'Elegir por separado',
'backup.ask_password': 'Proteger la copia con clave?',
'backup.yes': 'Si',
'backup.no': 'No',
'backup.password_set': 'Clave confirmada.',
'backup.hint_skipped': 'Sin pista.',
'backup.ready': 'Archivo de copia listo.',
'backup.protected': 'Copia protegida creada.',
'backup.unprotected': 'Copia sin clave creada.',
'backup.contact_admin': 'Demasiados intentos. Contacta admin.',
'backup.not_your_bot': 'Esta copia no es de este bot.',
'export.btn': 'Exportar',
'export.progress': 'Preparando tu exportacion...',
'export.ready': 'Exportacion lista.',
'export.warning': 'El export trae tus programados, canales, bots y ajustes.',
'export.no_data': 'Sin datos para exportar.',
'export.format_prompt': 'Elige formato:',
'export.format_json': 'JSON',
'export.format_csv': 'CSV',
'export.format_txt': 'Texto plano',
'export.sections_prompt': 'Que exportar?',
'export.section_messages': 'Mensajes programados',
'export.section_channels': 'Canales',
'export.section_bots': 'Bots remitentes',
'export.section_settings': 'Ajustes',
'export.section_all': 'Todo',
'export.select_sections': 'Elige secciones:',
'export.check_off': 'No',
'export.check_on': 'Si',
'export.data': 'Exportar datos',
'export.data_csv': 'Exportar datos (CSV)',
'export.data_title': 'Exportar datos',
'export.format_choice': 'Elige formato:',
'export.messages_csv': 'Mensajes (CSV)',
'export.stats_csv': 'Stats (CSV)',
'export.success': 'Exportacion ok.',
}
