# -*- coding: utf-8 -*-
PATCH = {
'help.start.title': 'Primeros pasos',
'help.getting_started.title': 'Primeros pasos',
'help.connect_channel.title': 'Conectar un canal',
'help.scheduling.title': 'Programar mensajes',
'help.premium.title': 'Premium',
'help.bots.title': 'Bots',
'help.channels.title': 'Canales',
'help.backup.title': 'Copia de seguridad',
'help.calendar.title': 'Calendario',
'help.channel_add.title': 'Añadir canal',
'help.channel_connect.title': 'Conectar canal',
'help.channel_manage.title': 'Gestionar canal',
'help.channel_remove.title': 'Eliminar canal',
'help.commands.title': 'Comandos',
'help.export.title': 'Exportar',
'help.import.title': 'Importar',
'help.language.title': 'Idioma',
'help.limits.title': 'Límites',
'help.referral.title': 'Referidos',
'help.stats.title': 'Estadísticas',
'help.timezone.title': 'Zona horaria',
'help.tips.title': 'Consejos',
'help.faq.title': 'Preguntas frecuentes',
'help.contact.title': 'Contacto',
'help.feedback.title': 'Opinión',
'help.errors.title': 'Errores',
'help.backup_create.title': 'Crear copia',
'help.backup_restore.title': 'Restaurar copia',
'help.bot_add.title': 'Añadir bot remitente',
}
