# -*- coding: utf-8 -*-
"""RU batch: filter … scheduled — the remaining mid sections."""

PATCH = {
    # ---- filter ----
    'filter.all_media': '@@STORAGE@@Все',
    'filter.images_short': '@@STORAGE@@Изображения',
    'filter.videos_short': '@@STORAGE@@Видео',
    'filter.files_short': '@@STORAGE@@Файлы',
    'filter.other_short': '@@STORAGE@@Другое',
    'filter.placeholder': 'Фильтр...',
    'filter.all': 'Все',
    'filter.btn': '🔍 Фильтр',
    'filter.open': 'Открыт',
    'filter.replied': 'С ответом',
    'filter.spam': 'Спам',
    'filter.other': 'Другое',
    'filter.images': '🖼 Изображения',
    'filter.videos': '🎬 Видео',
    'filter.files': '📄 Файлы',
    'filter.images_videos': '🖼🎬 Изображения и видео',
    'filter.images_files': '🖼📄 Изображения и файлы',
    'filter.videos_files': '🎬📄 Видео и файлы',
    # ---- select ----
    'select.language': '🌐 <b>Выбор языка</b>\n\nВыберите предпочтительный язык:',
    'select.channel_title': '📢 <b>Выбор канала</b>\n\nКакой канал использовать:',
    'select.channel': '📢 Выбрать канал',
    'select.channel_for_message': '📢 Для какого канала это сообщение?',
    'select.channel_for_bot': '📢 Каким каналом будет управлять новый бот?',
    'select.bot_hint': '🤖 Выберите бота для подключения к <b>{channel}</b>:',
    'select.bot_to_remove': '🤖 Выберите бота для удаления:',
    'select.recurring_type': '🔄 <b>Тип повтора</b>\n\nКак часто публиковать это сообщение?',
    'select.destination_storage': '@@STORAGE@@💾 Выберите хранилище-приёмник:',
    'select.all': 'Выбрать все',
    'select.btn': 'Выбрать',
    'select.all_btn': '✅ Выбрать все',
    'select.at_least_one': '❌ Выберите хотя бы один пункт.',
    'select.at_least_one_item': '❌ Выберите хотя бы один пункт.',
    'select.category': '📝 Выберите категорию:',
    'select.photo_mode': '📷 Выберите режим фото:',
    'select.timezone': '🌍 Выбрать часовой пояс',
    'select.channel_default_hint': '⭐ По умолчанию: {channel}',
    # ---- stats intervals ----
    'stats.interval_3h': 'Каждые 3 часа',
    'stats.interval_6h': 'Каждые 6 часов',
    'stats.interval_12h': 'Каждые 12 часов',
    'stats.interval_daily_9': 'Ежедневно в 09:00',
    'stats.interval_daily_18': 'Ежедневно в 18:00',
    'stats.interval_weekly_mon_9': 'Еженедельно (пн 09:00)',
    'stats.interval_monthly_1_9': 'Ежемесячно (1-го в 09:00)',
    'stats.interval_quarterly': 'Ежеквартально (1 янв в 09:00)',
    'stats.interval_yearly': 'Ежегодно (1 янв в 09:00)',
    'stats.no_data_yet': '(данных пока нет)',
    'stats.no_data_period': '(нет данных за период)',
    'stats.interval': '📊 Интервал статистики',
    'stats.interval_all': 'За всё время',
    'stats.interval_day': 'Сегодня',
    'stats.interval_month': 'Этот месяц',
    'stats.interval_week': 'Эта неделя',
    'stats.metric_all': '📊 Все метрики',
    'stats.select_metric': '📊 <b>Что хотите отслеживать?</b>\n\nВыберите метрику для подробной статистики:\n\n👁 <b>Самые просматриваемые</b> — посты с наибольшим числом просмотров\n💬 <b>Самые обсуждаемые</b> — посты с наибольшим числом комментариев\n❤️ <b>Самые реагируемые</b> — посты с наибольшим числом реакций\n📊 <b>Все метрики</b> — все метрики вместе\n\nКаждая метрика показывает лучший контент, чтобы вы понимали, что находит отклик у аудитории.',
    # ---- icons ----
    'icon.scheduled': '📅',
    'icon.recurring': '🔄',
    'icon.broadcast': '📢',
    'icon.chat': '💬',
    'icon.eye': '👁',
    'icon.edit': '✏️',
    'icon.del': '🗑',
    'icon.media': '🖼',
    'icon.date': '📅',
    'icon.clipboard': '📋',
    'icon.channel': '📢',
    'icon.id': '🆔',
    'icon.photo': '📷',
    'icon.tz': '🕐',
    'icon.anonymous': '🎭',
    'icon.pause': '⏸',
    'icon.resume': '▶',
    # ---- download ----
    'download.box_btn': '@@STORAGE@@📥 Скачать хранилище',
    'download.format_zip': '@@STORAGE@@ZIP',
    'download.format_tar': '@@STORAGE@@TAR',
    'download.format_targz': '@@STORAGE@@TAR.GZ',
    'download.format_tarbz2': '@@STORAGE@@TAR.BZ2',
    'download.format_tarxz': '@@STORAGE@@TAR.XZ',
    'download.select_format': '@@STORAGE@@📥 Выберите формат скачивания:',
    'download.select_types': '@@STORAGE@@Выберите, какие типы медиа включить:',
    'download.ready': '@@STORAGE@@✅ Скачивание готово!',
    'download.started': '@@STORAGE@@⏳ Готовим скачивание...',
    'download.btn': '📥 Скачать',
    'download.error': '❌ Ошибка скачивания: {error}',
    'download.failed_warning': '❌ Скачивание не удалось.',
    'download.no_files': '❌ Нет файлов для скачивания.',
    'download.progress': '⏳ Скачиваем... {percent}%',
    # ---- invalid ----
    'invalid.token': '❌ Неверный токен: {error}',
    'invalid.channel_format': '❌ Неверный формат канала.',
    'invalid.channel_link': '❌ Неверная ссылка-приглашение канала.',
    'invalid.cron': '❌ Неверное cron-выражение. Используйте 5 полей через пробел: минута час день месяц день_недели.\n\nПример: <code>0 9 * * 1</code> — каждый понедельник в 9:00',
    'invalid.day': '❌ Неверный день. Используйте корректное название дня (например, Понедельник) или число (1–31).',
    'invalid.day_range': '❌ День должен быть от 1 до 31.',
    'invalid.time': '❌ Неверный формат времени.',
    'invalid.time_format': '❌ Неверный формат времени. Используйте ЧЧ:ММ (24 ч).\n\nПример: <code>09:00</code>',
    'invalid.format': '❌ Неверный формат.',
    'invalid.file_type': '❌ Неверный тип файла.',
    'invalid.date': '❌ Неверный формат даты.',
    'invalid.datetime': '❌ Неверная дата/время.',
    'invalid.button_value': '❌ Неверное значение кнопки.',
    'invalid.date_format': '❌ Неверный формат даты.',
    'invalid.input': '❌ Некорректный ввод.',
    # ---- delete ----
    'delete.btn': '🗑 Удалить',
    'delete.all': '🗑 Удалить все',
    'delete.all_confirm': '⚠️ Вы уверены, что хотите удалить <b>все</b> {count} сообщений?\n\nДействие необратимо.',
    'delete.by_id': '🗑 Удалить по ID',
    'delete.id_prompt': 'Отправьте ID сообщений, которые нужно удалить.\n\nНесколько ID разделяйте запятыми.\nПример: <code>5, 12, 23</code>',
    'delete.menu_text': '🗑 <b>Удаление сообщений</b>\n\nВыберите способ удаления:',
    'delete.box_btn': '@@STORAGE@@🗑 Удалить хранилище',
    'delete.btn_short': '@@STORAGE@@Удалить',
    'delete.button': '🗑 Удалить',
    'delete.feedback': '🗑 Удалить',
    'delete.message_confirm': '⚠️ <b>Удалить это сообщение?</b>\n\nДействие необратимо.',
    'delete.complaint': '🗑 Удалить',
    # ---- seq ----
    'seq.addmore_done_btn': '✅ Готово',
    'seq.pick_title': '📸 <b>Последовательные медиа</b>',
    'seq.res_addmore_btn': '➕ Добавить ещё',
    'seq.res_random_btn': '🎲 Случайный порядок',
    'seq.res_specific_btn': '📋 Определённый порядок',
    'seq.res_text_btn': '📝 Добавить текст',
    'seq.session_expired': '⏳ Сессия истекла. Начните заново.',
    'seq.skip_text_btn': '⏭ Без текста',
    'seq.addmore_text': '📷 Отправьте ещё {needed} медиафайлов',
    'seq.addmore_progress': '📷 Получено {count}/{needed}',
    'seq.media_item': '📷 #{n}',
    'seq.mismatch_text': '⚠️ Медиа: {media_count}, сообщений: {msg_count} (лишних: {surplus})',
    # ---- sequential ----
    'sequential.by_date': 'По дате',
    'sequential.by_sent': 'По порядку отправки',
    'sequential.order_by_date': 'Сортировать по дате',
    'sequential.order_by_sent': 'Сортировать по отправке',
    'sequential.order_choose': '🔀 По порядку',
    'sequential.order_date_desc': 'Сначала новые',
    'sequential.order_detail': '📝 <b>Настройки порядка</b>\n\nВыберите, как упорядочивать фото в режиме последовательности:\n\n<b>📅 По дате</b>\nФото сортируются по дате загрузки. Новые могут быть первыми или последними — как вы выберете.\n\n<b>📤 По порядку отправки</b>\nФото сортируются по времени последней отправки. Удобно для ротации медиатеки.\n\n<b>💡 Советы:</b>\n• «По дате» — для хронологического контента (например, серии фото)\n• «По порядку отправки» — чтобы свежий контент всегда шёл первым\n• Порядок влияет на распределение фото по отложенным постам',
    'sequential.order_sent_desc': 'Сначала отправленные последними',
    'sequential.media_received': '📷 Получено: {count} — {type_label}.',
    'sequential.media_ready': '📷 Медиафайлов готово: {count}.',
    'sequential.photo_mode': '🔀 По порядку',
    'sequential.order_prompt': '🔀 Порядок: {order} ({order_desc})',
    # ---- error ----
    'error.btn': '❌ Ошибка',
    'error.occurred': '❌ <b>Произошла ошибка.</b>\n\n{error}\n\nАдминистратор уведомлён.',
    'error.loading_bot': '❌ <b>Ошибка при загрузке этого бота.</b>\n\nПопробуйте ещё раз или напишите в поддержку.',
    'error.generic': '❌ Что-то пошло не так. Попробуйте ещё раз.',
    'error.unknown': '❌ Произошла неизвестная ошибка.',
    'error.permission': '❌ У вас нет прав для этого действия.',
    'error.not_found': '❌ Не найдено.',
    'error.timeout': '⏳ Время запроса истекло. Попробуйте ещё раз.',
    'error.network': '❌ Ошибка сети. Проверьте соединение.',
    'error.limit': '⚠️ Достигнут лимит. Попробуйте позже.',
    'error.invalid_input': '❌ Некорректный ввод. Попробуйте ещё раз.',
    # ---- upsell ----
    'upsell.scheduled_messages': 'Планируйте больше сообщений — Premium даёт {limit} отложенных постов.',
    'upsell.daily_messages': 'Отправляйте больше сообщений в день — Premium поднимает дневной лимит до {limit}.',
    'upsell.channels': 'Подключайте больше каналов — Premium позволяет подключить {limit} каналов.',
    'upsell.bots': 'Подключайте больше ботов-отправителей — Premium позволяет подключить {limit} ботов.',
    'upsell.recurring': 'Больше повторяющихся сообщений — Premium допускает {limit} повторяющихся сообщений.',
    'upsell.media_storage': 'Больше хранилищ медиа — Premium даёт больше хранилищ по {limit} файлов.',
    'upsell.video': 'Загружайте видео — Premium включает загрузку видео ({limit}).',
    'upsell.leaderboard': 'Доступ к рейтингу — Premium открывает рейтинги по эффективности постов.',
    'upsell.calendar': 'Вид календаря — Premium даёт полный обзор календаря.',
    'upsell.backup_export': 'Резервные копии и экспорт данных — Premium открывает полное резервное копирование и экспорт.',
    'upsell.4k_media': '❌ <b>Медиа 4K не поддерживается на бесплатном тарифе</b>\n\nБесплатный тариф не поддерживает фото и видео в разрешении 4K (≥{photo_4k_threshold}px для фото, ≥{video_4k_threshold}p для видео).\n\nВаше медиа заблокировано. Premium открывает отправку медиа в высоком разрешении!\n\n<b>В Premium входит:</b>\n• ✅ Фото до <b>{premium_photo_max_dim}px</b>\n• ✅ Видео до <b>{premium_video_max_dim}p</b>\n• ✅ Более щадящее сжатие — качество выше\n\n💎 <b>Перейдите на Premium, чтобы открыть поддержку 4K.</b>',
    # ---- connect ----
    'connect.bot_btn': '🤖 Подключить бота-отправителя',
    'connect.channel': '📢 Подключить канал',
    'connect.channel_sender_bot': '📢 Или подключите через бота-отправителя',
    'connect.sender_bot': '🔗 Подключить бота-отправителя',
    'connect.sender_bot_btn': '🔗 Подключить нового бота-отправителя',
    'connect.channel_for_bot': 'Подключить канал',
    'connect.from_main_bot': '📢 <b>Подключение нового канала</b>\n\nНовый канал можно подключить только из главного бота.\nНажмите кнопку ниже, чтобы открыть его и подключить канал.',
    'connect.limit_reached': 'К сожалению, можно подключить не более {limit} каналов. Отключите один из них или напишите нашему админу, если нужны более высокие лимиты.',
    'connect.open_main_bot_btn': '🚀 Открыть главного бота и подключить',
    'connect.channels_btn': '📢 Мои каналы',
    # ---- csv ----
    'csv.btn': 'CSV',
    'csv.channel': 'Канал',
    'csv.content': 'Содержимое',
    'csv.datetime': 'Дата/время',
    'csv.id': 'ID',
    'csv.photo_count': 'Фото',
    'csv.photo_mode': 'Режим фото',
    'csv.type': 'Тип',
    'csv.scheduled': 'Отложено',
    'csv.recurring': 'Повторяющееся',
    # ---- signature flat leftovers ----
    'signature.menu_text': '📝 <b>Подписи</b>\n\nДобавьте строку подписи к отложенным сообщениям. Она будет автоматически добавляться в конец каждого поста.',
    # ---- managed ----
    'managed.info_text': '📢 <b>О настройках канала</b>\n\n<b>{channel}</b>\n\nУправляет: @{bot}\n\n• Все посты идут через @{bot}\n• Планирование по-прежнему ведёт главный бот\n• Быстрые действия — в @{bot}',
    'managed.by_tag': 'Управляет @{bot}',
    'managed.info_text_in_bot': '🤖 <b>Управляется этим ботом</b>\n\n📢 <b>Канал:</b> {channel}\n🔗 <b>Подключён:</b> {connected_date}\n🔄 <b>Управление передано:</b> {moved_date}\n\nВернуть управление главному боту можно в любой момент кнопкой ниже.',
    'managed.mode_notice': '🤖 Управление передано боту(-ам)-отправителю — используйте их',
    'managed.mode_search': '🔍 Поиск',
    'managed.mode_title': '🤖 <b>Управление передано боту-отправителю</b>',
    'managed.mode_desc': 'Все ваши каналы управляются через ботов-отправителей. Используйте бота-отправителя ниже, чтобы планировать сообщения, смотреть статистику и управлять контентом.\n\n<code>╔══════════════════════════╗</code>\n<code>║  Управляйте через @{bot}  ║</code>\n<code>╚══════════════════════════╝</code>',
    'managed.mode_minimal_menu': '🤖 <b>Главное меню (упрощённое)</b>\n\n<i>Управление передано вашему боту-отправителю.</i>\n\nИспользуйте бота-отправителя (@{bot}) для планирования сообщений, управления контентом и просмотра статистики.\n\nВернуть полное управление этому боту можно в любой момент кнопкой ниже.',
    'managed.mode_minimal_no_bot': '🤖 <b>Главное меню (упрощённое)</b>\n\n<i>Управление передано вашим ботам-отправителям.</i>\n\nИспользуйте ботов-отправителей для планирования сообщений, управления контентом и просмотра статистики.\n\nВернуть полное управление этому боту можно в любой момент.',
    # ---- my ----
    'my.bots_title': '🤖 <b>Мои боты-отправители</b>\n\nПодключённые боты помогают управлять каналами: полная поддержка инлайн-клавиатур и персональный интерфейс.',
    'my.bots_hint': '💡 Боты-отправители позволяют выглядеть вашему каналу управляемым собственным ботом, а не главным ботом FastSchedule.',
    'my.bots_list_item': '🤖 @{username} — {channel}',
    'my.bots_none': 'Боты-отправители пока не подключены. Подключите одного, чтобы открыть расширенное управление каналом.',
    'my.bots': '🤖 Мои боты',
    'my.feedback_title': '📮 <b>Мои отзывы</b>',
    'my.feedback_instructions': 'Выберите сообщение, чтобы посмотреть детали.',
    'my.feedback_none': 'Вы ещё не отправляли отзывов.',
    'my.feedback_detail_title': '📮 <b>Детали отзыва</b>',
    # ---- welcome ----
    'welcome.btn': '👋 <b>Добро пожаловать, {name}!</b>\n\n',
    'welcome.intro': '👋 <b>Добро пожаловать!</b>\n\nЯ Fast Scheduler — бот планирования для Telegram-каналов. Подключите канал, задайте время публикаций — и я буду доставлять сообщения автоматически.',
    'welcome.not_subscribed': '⚠️ Вы ещё не подписаны ни на один канал.\nИспользуйте кнопку <b>Канал</b>, чтобы подключить.',
    'welcome.no_channel': '📢 Вы ещё не подключили ни одного канала.\n\nПодключите канал, чтобы начать планировать сообщения.',
    'welcome.addbot_needed': '🤖 Чтобы открыть все возможности, подключите бота-отправителя.\n\nОтправьте токен своего бота, чтобы начать.',
    'welcome.subscribed': '✅ Вы подписаны и готовы к работе!',
    'welcome.channel': '📢 Подключённый канал: {channel}\n',
    'welcome.bot_connected': '🤖 Подключённый бот: @{bot_username}\n<i>Используется только для отправки сообщений. Всё управление — через главного бота.</i>\n',
    'welcome.bot_connected_user': '🤖 Бот @{username} подключён! Полное подтверждение отправлено вам главным ботом.',
    # ---- add ----
    'add.sender_bot': '➕ Добавить бота-отправителя',
    'add.another_bot': '➕ Добавить ещё бота',
    'add.more_media_btn': '➕ Добавить ещё медиа',
    'add.storage_btn': '@@STORAGE@@➕ Добавить хранилище',
    'add.media_btn': '@@STORAGE@@➕ Добавить медиа',
    'add.btn': '➕ Добавить',
    'add.promo_code_btn': '💳 Добавить промокод',
    'add.report_btn': '📊 Добавить отчёт',
    # ---- daily ----
    'daily.btn': '📅 Ежедневно',
    'daily.prompt': '📅 <b>Ежедневное расписание</b>\n\nВо сколько публиковать сообщение каждый день?\n\nФормат: <code>ЧЧ:ММ</code> (24 ч)\nПример: <code>09:00</code>',
    'daily.schedule': 'Ежедневно в {time}',
    'daily.limit_reached': '⚠️ Достигнут лимит отправки. Возвращайтесь позже или перейдите на Premium.',
    'daily.limit_recurring_alert': '⚠️ Достигнут дневной лимит повторяющихся сообщений (задание #{job_id}). Лимит: {limit}',
    'daily.messages': '📅 В день: {limit}',
    'daily.limit_reached_alert': '⚠️ Достигнут лимит отправки для @{bot_username} (задание #{job_id}). Лимит: {limit}',
    'daily.sent': 'Отправлено за день',
    # ---- message ----
    'message.list': '📋 Мои сообщения',
    'message.list_btn': '📋 Список сообщений',
    'message.info_title': '📋 <b>О сообщении</b>',
    'message.deleted': '🗑 Сообщение <b>#{id}</b> удалено.',
    'message.too_long': '❌ Сообщение слишком длинное ({count} симв.). Максимум — {max} симв.',
    'message.scheduled': '✅ Запланировано сообщений: {count}.',
    'message.updated_keep_media': '✅ Сообщение #{id} обновлено (медиа сохранено).',
    'message.sent': '✅ <b>Сообщение отправлено!</b>\n\nID: <code>{job_id}</code>',
    # ---- change ----
    'change.channel_btn': '🔄 Сменить канал',
    'change.channel_prompt': '🔄 <b>Замена канала</b>\n\nВы собираетесь заменить <b>{channel}</b> новым каналом.\n\n• {count} отложенных сообщений перейдут на новый канал\n• Повторяющиеся сообщения останутся на старом канале — обновите их отдельно (автоматически они не переносятся)\n\nПерешлите сообщение из нового канала, чтобы продолжить.',
    'change.channel_fallback': '❌ Не удалось сменить канал.',
    'change.bot_warning': '⚠️ Смена бота для <b>{channel}</b> отключит текущего бота. Продолжить?',
    'change.log_btn': '📝 Список изменений',
    'change.bot': '🔄 Сменить бота',
    'change.channel': '🔄 Сменить канал',
    # ---- cron ----
    'cron.schedule': 'Своё cron-расписание: {cron}',
    'cron.format': '<b>Формат cron:</b> <code>минута час день месяц день_недели</code>\n\n<b>Примеры:</b>\n• <code>0 9 * * 1</code> — каждый понедельник в 09:00\n• <code>30 18 * * *</code> — каждый день в 18:30\n• <code>0 */2 * * *</code> — каждые 2 часа\n• <code>0 8 1 * *</code> — 1-го числа каждого месяца в 08:00',
    'cron.title': '⚙️ Своё cron-выражение',
    'cron.examples': '<b>Частые примеры cron:</b>\n• <code>0 9 * * 1</code> — каждый понедельник в 9:00\n• <code>30 18 * * *</code> — ежедневно в 18:30\n• <code>0 8 1 * *</code> — 1-го числа в 8:00',
    'cron.example_daily': '0 9 * * * — каждый день в 09:00',
    'cron.example_weekly': '0 9 * * 1 — каждый понедельник в 09:00',
    'cron.example_monthly': '0 9 1 * * — 1-го числа в 09:00',
    # ---- duplicate ----
    'duplicate.ask_date': '📅 Когда отправить дубликат?',
    'duplicate.btn': '📋 Дублировать',
    'duplicate.confirm_title': '📋 <b>Дублирование сообщения</b>',
    'duplicate.no': '❌ Нет',
    'duplicate.yes': '✅ Да',
    'duplicate.ask_channel': '📢 Выберите канал для дубликата:',
    'duplicate.done': '✅ Дубликат создан: {ids}',
    # ---- inline ----
    'inline.syntax_error_title': '⚠️ <b>Неверный синтаксис инлайн-кнопок</b>',
    'inline.syntax_error_line': '• {snippet}',
    'inline.syntax_error_hint': '<b>Правильный формат:</b>\n<code>&lt;inline&gt;Текст кнопки&lt;link="https://example.com"&gt;</code>\n<code>&lt;inline&gt;Название действия&lt;callback="action_data"&gt;</code>\nИспользуйте <code>--</code>, чтобы поставить кнопки рядом, и <code>//</code>, чтобы начать новый ряд.\n\nИсправьте синтаксис и отправьте сообщение снова.',
    'inline.import_skipped': '⚠️ {count} сообщений пропущены: в них неверный синтаксис инлайн-кнопок. Исправьте разметку <code>&lt;inline&gt;</code> и импортируйте снова.',
    'inline.callback_error_title': '⚠️ <b>Незарегистрированная callback-кнопка</b>',
    'inline.callback_error_line': '• <code>{data}</code>',
    'inline.callback_error_hint': '<b>Эти кнопки ничего не будут делать при нажатии</b> — у бота нет обработчика для таких callback-данных.\n\n<b>Варианты:</b>\n• Используйте кнопку-ссылку: <code>&lt;inline&gt;Текст кнопки&lt;link="https://example.com"&gt;</code>\n• Или используйте callback-данные, совпадающие с существующим действием бота.',
    # ---- support ----
    'support.feedback_redirect_title': '📮 <b>Отзывы и поддержка</b>\n\nПоддержка, отзывы и темы помощи теперь живут в @FastSchedulerSupport_bot.\n\nНажмите кнопку ниже, чтобы открыть бота поддержки:',
    'support.feedback_redirect_btn': '📮 Открыть бота поддержки',
    'support.help_blank': '❓ <b>Помощь</b>\n\nТемы помощи переехали в @FastSchedulerSupport_bot.\n\nНажмите ниже, чтобы открыть:',
    'support.help_open_btn': '❓ Открыть помощь в боте поддержки',
    'support.first_rating_support_note': '💬 Поддержка и ваши оценки — в боте @FastSchedulerSupport_bot',
    'support.feedback_moved_note': '📮 Чтобы отправить отзыв, оценить бота или посмотреть историю отзывов, откройте @FastSchedulerSupport_bot.',
    'support.first_rating_thanks': '⭐ Спасибо за оценку Fast Scheduler!\n\n💬 Поддержка и ваши оценки — в боте @FastSchedulerSupport_bot',
    # ---- default ----
    'default.channel_set': '✅ <b>{channel}</b> теперь ваш канал по умолчанию.',
    'default.channel_removed': '✅ Канал по умолчанию убран.\n\nДля каждого нового сообщения канал нужно будет выбирать заново.',
    'default.channel_premium_notice': '⭐ Канал по умолчанию — новые сообщения будут попадать сюда автоматически.',
    'default.channel_star_info': '⭐ По умолчанию',
    'default.channel_title': '⭐ <b>Канал по умолчанию</b>\n\nСообщения по умолчанию будут отправляться в этот канал. Канал всё ещё можно менять при планировании.',
    'default.channel_button': '⭐ Задать канал по умолчанию',
    # ---- notify ----
    'notify.complaint_spam': '📮 <b>Обновление по отзыву</b>\n\nВаш отзыв <code>{complaint_id}</code> отмечен как спам.',
    'notify.complaint_closed': '📮 <b>Обновление по отзыву</b>\n\nВаш отзыв <code>{complaint_id}</code> закрыт.',
    'notify.complaint_deleted': '📮 <b>Обновление по отзыву</b>\n\nВаш отзыв <code>{complaint_id}</code> удалён.',
    'notify.premium_granted': '🎉 <b>Premium активирован!</b>\n\nТеперь вам доступны все премиум-возможности!',
    'notify.premium_revoked': '⚠️ <b>Premium отключён.</b>\n\nВаш премиум-доступ снят.',
    'notify.blocked': '🚫 Вы заблокированы администратором.',
    # ---- promo / reports / restore / scheduled ----
    'promo.remove': 'Убрать промокод',
    'promo.apply': 'Применить промокод',
    'promo.applied': '✅ Промокод применён: {code}',
    'promo.code_invalid': '❌ Неверный промокод.',
    'promo.code_applied_msg': '✅ Промокод применён! {discount_text}\nЦена: {price}\nОсталось: {remaining}',
    'promo.add_start': '➕ Добавить промокод',
    'reports.btn': '📊 Отчёты',
    'reports.no_data': '📪 Отчётов пока нет.',
    'reports.title': '📊 <b>Отчёты</b>',
    'reports.channel_line': '📢 {channel}',
    'reports.active_line': '📊 Активных: {active} / {limit}',
    'reports.free_limit_notice': '📊 Бесплатный тариф: максимум {limit} отчёт(а).',
    'restore.mgmt_btn': '🔄 Вернуть главному боту',
    'restore.mgmt_red_btn': '🔴 Вернуть управление и отключить бота',
    'restore.btn': '📂 Восстановить из копии',
    'restore.confirm_prompt': '⚠️ Восстановить из резервной копии?\n\nТекущие данные будут заменены.',
    'restore.confirm_btn': '✅ Да, восстановить',
    'restore.to_main': 'Вернуть главному боту',
    'scheduled.limit_reached': '⚠️ Достигнут лимит канала: ожидающих отложенных сообщений {used}/{limit}.\n\nУдалите часть ожидающих сообщений или перейдите на Premium, чтобы планировать больше.',
    'scheduled.messages_list': '📅 <b>Отложенные сообщения</b>\n\nУ вас отложенных сообщений: {count}. Выберите одно, чтобы посмотреть или управлять.',
    'scheduled.item_line': '{icon} {id}: {preview} — {datetime}',
    'scheduled.expired_on_restart': '⏳ Задание #{job_id} истекло ({datetime})',
    'scheduled.sent_late': '⏳ Задание #{job_id} отправлено с опозданием {delay}.',
    'scheduled.messages': 'Отложенные сообщения',
}
