# -*- coding: utf-8 -*-
"""RU batch: premium remainder, recurring, no, calendar, lang, storage."""

PATCH = {
    # ---- premium remainder ----
    'premium.comparison_free_limit': 'Вы достигли лимита бесплатного тарифа. Premium позволит планировать больше и откроет дополнительные каналы, ботов-отправителей и хранилища медиа.',
    'premium.grace_24h_info': '⏳ Льготный период до: {date}',
    'premium.menu': '💎 Перейти на Premium',
    'premium.payment_unavailable_text': '❌ Оплата сейчас недоступна. Попробуйте позже или напишите в поддержку.',
    'premium.cancel_prompt': '❓ <b>Отмена Premium</b>\n\nЖаль, что вы уходите! Расскажете, почему отменяете?',
    'premium.cancel_reason_no_longer_needed': 'Больше не нужен',
    'premium.cancel_reason_issues': 'Технические проблемы',
    'premium.cancel_reason_other': 'Другая причина',
    'premium.cancel_reason_optional_prompt': '📝 Расскажите подробнее (необязательно):',
    'premium.cancel_skip_reason_button': '⏭ Пропустить',
    'premium.excess_channels': '⚠️ <b>Каналы:</b> у вас подключено {current}. После окончания Premium активными останутся только {limit}. Остальные будут отключены, если не продлить подписку.',
    'premium.excess_bots': '🤖 <b>Боты:</b> у вас подключено {current}. После окончания Premium активными останутся только {limit}. Остальные будут отключены, если не продлить подписку.',
    'premium.excess_recurring': '🔄 <b>Повторяющиеся сообщения:</b> у вас {current}. Бесплатный тариф допускает только 1. Дополнительные повторяющиеся сообщения будут приостановлены, пока вы не вернёте Premium.',
    'premium.channel_selected': '✅ {name}',
    'premium.channel_unselected': '⬜ {name}',
    'premium.bot_selected': '✅ @{username}',
    'premium.bot_unselected': '⬜ @{username}',
    'premium.recurring_selected': '✅ {name}',
    'premium.recurring_unselected': '⬜ {name}',
    'premium.activated_until': '🎉 <b>Premium активирован!</b>\n\nВаш Premium активен до {date}.',
    'premium.video_schedule_limit': '❌ Видео превышает лимит {limit} МБ. Бесплатный тариф допускает видео до {limit} МБ. Возьмите файл поменьше или сожмите видео.',
    'premium.priority_boot': '⭐ Ваш бот-отправитель запускается с приоритетом — вы подписчик Premium!',
    'premium.required_stats': '⭐ <b>Нужен Premium</b>\n\nСтатистика по этому каналу требует подписки Premium.',
    'premium.emoji_warning': '⚠️ <b>Обнаружены премиум-эмодзи</b>\n\nДля отправки премиум-эмодзи нужен Telegram Premium. Бот не поддерживает их в отложенных сообщениях — они появятся как обычный текст.\n\nЕсли вы оформите <b>FastSchedule Premium</b>, вы поддержите владельца бота и поможете покрыть стоимость апгрейда аккаунта бота до Telegram Premium, чтобы в будущем премиум-эмодзи можно было отправлять.\n\nСпасибо за понимание :)',
    'premium.emoji_btn_subscribe': '⭐️ Оформить Premium',
    'premium.emoji_btn_anyway': '✅ Всё равно запланировать',
    'premium.emoji_btn_cancel': '❌ Отмена',
    'premium.help_btn': 'ℹ️ О боте',
    'premium.renew_manual_title': '🔄 <b>Ваша подписка Premium закончилась.</b>\n\nСпособ оплаты: {method} · Тариф: {plan}',
    'premium.renew_manual_info': 'Этот способ оплаты не поддерживает автопродление, поэтому после каждого окончания подписки её нужно продлевать вручную. Premium активен до <b>{expires}</b> — продлите до этого момента, чтобы ничего не прерывалось.',
    'premium.renew_manual_info_stars': 'Это был разовый платёж Telegram Stars. Автопродления нет, поэтому до <b>{expires}</b> выберите и оплатите новый план, чтобы ничего не прерывалось. Годовой действует год; предоплаченные 3/6 месяцев — свой заявленный срок.',
    'premium.renew_manual_tip': '💡 <b>Рекомендуем:</b> выберите <b>годовой план</b> — продление раз в год вместо каждого месяца. Продление — скучное занятие, пусть будет реже! Плюс годовая скидка сэкономит деньги. (Хотите иначе? Выберите план {other_plan}.)',
    'premium.renew_manual_reminder': '⏰ <b>Напоминание:</b> льготный период почти закончился. Продлите сейчас, чтобы функции Premium не отключились.',
    'premium.renew_pay_again_btn': '💳 Оплатить план {plan} снова',
    'premium.renew_choose_plan_btn': '📋 Выбрать другой план',
    'premium.renew_cancel_btn': '❌ Отменить подписку',
    'premium.renew_manual_tip_yearly': '💡 <b>Хороший выбор:</b> вы взяли <b>годовой план</b>, поэтому продлевать нужно <b>раз в год</b> — без месячной суеты. Продление скучное: с годовым планом вы занимаетесь им один раз вместо двенадцати.',
    'premium.payment_method_disabled': '❌ Этот способ оплаты сейчас отключён. Оплатите через Telegram Stars.',
    'premium.stars_payment_sent_prompt': '⭐ Запрос на оплату отправлен! Откройте сообщение выше, чтобы оплатить через Telegram Stars.',
    'premium.menu_text_premium': '⭐ <b>Подписка Premium</b>\n\n<b>Ваш тариф:</b> {plan}\n\n👑 <b>ТАРИФ PREMIUM</b>\n\n• Отправок в месяц: {daily_prem}\n\n• Отложенных: {scheduled_prem}\n\n• Повторяющихся: {recurring_prem}\n\n• Каналы: {channels_prem}\n\n• Боты: {bots_prem}\n\n• Статистика: отчёты без ограничений, рейтинг, полные данные по постам\n\n• Видео в отложенных сообщениях: {videos_msg_prem}\n\n• Видео в хранилище: {videos_storage_prem}\n\n• Всего файлов в хранилищах: {media_items_prem}\n\n• Медиа 4K: {allow_4k_prem}\n\n• Приоритет рассылок: приоритетный\n\n• Сжатие: {compression_prem}\n\n• Рейтинг: да\n\n• Автоотчёты: без ограничений\n\n📦 <b>БЕСПЛАТНЫЙ ТАРИФ</b>\n\n• Отправок в месяц: {daily_free}\n\n• Отложенных: {scheduled_free}\n\n• Повторяющихся: {recurring_free} (завершаются через год)\n\n• Каналы: {channels_free}\n\n• Боты: {bots_free}\n\n• Статистика: только средние (полная — в Premium)\n\n• Видео в отложенных сообщениях: {videos_msg_free}\n\n• Видео в хранилище: {videos_storage_free}\n\n• Всего файлов в хранилищах: {media_items_free}\n\n• Медиа 4K: {allow_4k_free}\n\n• Приоритет рассылок: обычный\n\n• Сжатие: {compression_free}\n\n• Рейтинг: нет\n\n• Автоотчёты: до 3 расписаний\n\n',
    'premium.menu_text_free': '⭐ <b>Подписка Premium</b>\n\n<b>Ваш тариф:</b> {plan}\n\n📦 <b>БЕСПЛАТНЫЙ ТАРИФ</b>\n\n• Отправок в месяц: {daily_free}\n\n• Отложенных: {scheduled_free}\n\n• Повторяющихся: {recurring_free} (завершаются через год)\n\n• Каналы: {channels_free}\n\n• Боты: {bots_free}\n\n• Статистика: только средние (полная — в Premium)\n\n• Видео в отложенных сообщениях: {videos_msg_free}\n\n• Видео в хранилище: {videos_storage_free}\n\n• Всего файлов в хранилищах: {media_items_free}\n\n• Медиа 4K: {allow_4k_free}\n\n• Приоритет рассылок: обычный\n\n• Сжатие: {compression_free}\n\n• Рейтинг: нет\n\n• Автоотчёты: до 3 расписаний\n\n👑 <b>ТАРИФ PREMIUM</b>\n\n• Отправок в месяц: {daily_prem}\n\n• Отложенных: {scheduled_prem}\n\n• Повторяющихся: {recurring_prem}\n\n• Каналы: {channels_prem}\n\n• Боты: {bots_prem}\n\n• Статистика: отчёты без ограничений, рейтинг, полные данные по постам\n\n• Видео в отложенных сообщениях: {videos_msg_prem}\n\n• Видео в хранилище: {videos_storage_prem}\n\n• Всего файлов в хранилищах: {media_items_prem}\n\n• Медиа 4K: {allow_4k_prem}\n\n• Приоритет рассылок: приоритетный\n\n• Сжатие: {compression_prem}\n\n• Рейтинг: да\n\n• Автоотчёты: без ограничений',
    'premium.status_details_renewal': '⭐ <b>Статус Premium</b>\n\nТариф: {plan}\nСтатус: {status}\nНачало: {started}\nСледующее продление: {expires}\nАвтопродление: {autorenew}',
    # ---- recurring ----
    'recurring.btn': '🔄 Повторяющиеся ({limit}, {type})',
    'recurring.message': '🔄 Повторяющиеся сообщения',
    'recurring.messages_list': '🔄 <b>Повторяющиеся сообщения</b>\n\nУ вас повторяющихся сообщений: {count}. Выберите одно, чтобы посмотреть или управлять.',
    'recurring.prompt': '🔄 <b>Настройка повторяющихся сообщений</b>\n\nПовторяющиеся сообщения публикуются автоматически по расписанию — ежедневно, еженедельно, ежемесячно или своё (cron).\n\nОтправьте текст сообщения, которое должно публиковаться повторно:\n\n📌 <b>Инлайн-кнопки:</b>\nДобавьте кликабельные кнопки: <code>&lt;inline&gt;Текст кнопки&lt;link="https://example.com"&gt;</code>\nИспользуйте <code>--</code> для кнопок рядом и <code>//</code> для нового ряда.',
    'recurring.created': '✅ Повторяющееся сообщение создано!\n\n🔄 Расписание: {schedule}\n📢 Канал: {channel}\n🆔 ID: <code>{id}</code>',
    'recurring.error': '❌ Произошла ошибка при настройке повторяющихся сообщений.',
    'recurring.expired': '⏳ Повторяющееся сообщение истекло или его канал больше недоступен.',
    'recurring.without_bot_warning': '🤖 Для создания повторяющихся сообщений нужен бот-отправитель. Подключите его к своему каналу — это займёт около минуты.',
    'recurring.schedule': '⏰ <b>Задайте расписание повтора</b>',
    'recurring.messages': 'Повторяющиеся сообщения',
    'recurring.signature_menu_prompt': 'Выберите, как добавить подпись:',
    'recurring.signature_prompt': 'Добавить подпись к этим повторяющимся сообщениям?',
    'recurring.start_date_prompt': 'Когда должно начинаться это повторяющееся сообщение?\nОтправьте дату в формате ГГГГ-ММ-ДД или выберите сегодня/завтра.',
    'recurring.time_prompt': 'Отлично. Теперь отправьте время для каждого повторного поста, например 09:00 или 9:00 AM.',
    'recurring.view_list': '📋 Мои повторяющиеся сообщения',
    'recurring.review_title': '🔄 <b>Проверка повторяющегося сообщения</b>\n\n{preview}\n\n⏰ Расписание: {schedule}\n📢 Канал: {channel}',
    'recurring.review_question': '❓ Хотите что-нибудь изменить?',
    'recurring.review_schedule': '✅ Запланировать',
    'recurring.review_edit': '✏️ Редактировать',
    'recurring.edit_prompt': '✏️ <b>Редактирование повторяющегося сообщения</b>\n\nОтправьте <b>новую версию</b> своего повторяющегося сообщения — она <b>заменит</b> старую.\n\nМожно изменить и <b>дату/время старта</b>:\n<code>ДД.ММ.ГГГГ ЧЧ:ММ</code>\n<code>ваше сообщение</code>\n<i>Или вместе:</i> <code>ДД.ММ.ГГГГ ЧЧ:ММ ваше сообщение</code>\n\nРанее отправленные медиа сохранятся. Можно также отправить новые медиа, чтобы добавить их к текущему выбору или заменить его.',
    'recurring.edit_replaced': '✅ Повторяющееся сообщение заменено. Старая версия больше не запланирована.',
    'recurring.edit_date_updated': '✅ Дата/время старта обновлены. Старая версия больше не запланирована.',
    'recurring.edit_content_updated': '✏️ Содержимое обновлено.',
    'recurring.edit_nothing': '❌ Отправьте исправленное сообщение или медиа.',
    'recurring.start_label': 'начало',
    'recurring.no_text': '(медиасообщение)',
    'recurring.paused_label': '⏸ На паузе',
    'recurring.pause_confirm': '⏸ <b>Приостановить повторяющееся сообщение?</b>\n\nID сообщения: <code>{job_id}</code>\n\nСообщение <b>перестанет отправляться</b>, пока вы его не возобновите.\nВсе настройки и содержимое сохранятся.\n\nВозобновить можно в любой момент из списка сообщений.',
    'recurring.resume_confirm': '▶ <b>Возобновить повторяющееся сообщение?</b>\n\nID сообщения: <code>{job_id}</code>\n\nСообщение <b>снова начнёт отправляться</b> по своему расписанию.\nСледующая отправка произойдёт в ближайшее запланированное время.',
    'recurring.paused_toast': '⏸ Повторяющееся сообщение на паузе.',
    'recurring.resumed_toast': '▶ Повторяющееся сообщение возобновлено.',
    # ---- no ----
    'no.bot_connected': 'Бот-отправитель не подключён',
    'no.channel': '📢 Канал не подключён.',
    'no.channel_connected': 'Вы ещё не подключили ни одного канала. Подключите канал, чтобы начать.',
    'no.channels_selected': 'Каналы не выбраны.',
    'no.access_channel': '❌ У вас нет доступа к этому каналу.',
    'no.managed_channels': 'Сейчас нет каналов под управлением ботов-отправителей.',
    'no.messages': '📪 Сообщения не найдены.',
    'no.media_type_selected': '@@STORAGE@@Выберите хотя бы один тип медиа для фильтра.',
    'no.media_to_save': '@@STORAGE@@Нет медиафайлов для сохранения.',
    'no.other_storage_boxes_found': '@@STORAGE@@Других хранилищ нет.',
    'no.other_storage_copy': '@@STORAGE@@❌ Нет хранилища, куда можно копировать.',
    'no.other_storage_move': '@@STORAGE@@❌ Нет хранилища, куда можно переместить.',
    'no.referral_days': '❌ Реферальных дней нет.',
    'no.referral_days_left': '❌ Реферальных дней не осталось.',
    'no.changes': '❌ Нечего сохранять — изменений нет.',
    'no.items': '📪 Пусто.',
    'no.media_mode': 'Только текст',
    'no.media_received': '❌ Медиа не получено.',
    'no.bots_connected': '📪 Боты не подключены.',
    'no.bots_connected_hint': '📪 Боты не подключены. Подключите через /addbot.',
    'no.hint_available': '📪 Подсказки нет.',
    'no.messages_export_selected': '❌ Для экспорта не выбрано ни одного сообщения.',
    'no.photos_received': '❌ Фото не получены.',
    'no.text': '(без текста)',
    'no.review': '(без отзыва)',
    'no.media_selected': 'Медиа не выбрано.',
    'no.free_channels': 'Ко всем вашим каналам уже подключены боты-отправители.\n\nСначала отключите одного из них или подключите новый канал.',
    'no.images_received': 'Изображения пока не получены.',
    'no.target_user': 'Целевой пользователь не указан. Начните заново.',
    'no.sender_bot': 'Нет бота-отправителя',
    # ---- calendar ----
    'calendar.btn': '📅 Календарь',
    'calendar.title': '📅 Календарь',
    'calendar.header': '📅 <b>{month} {year}</b>',
    'calendar.month_nav': '{month} {year}',
    'calendar.day_with_msgs': '{day} ({count})',
    'calendar.day_empty': '{day}',
    'calendar.view_day': '📅 Открыть день',
    'calendar.today_btn': '📅 Сегодня',
    'calendar.select_day': '📅 Выберите день, чтобы увидеть отложенные сообщения.',
    'calendar.no_messages': '📪 На этот день сообщений нет.',
    'calendar.messages_for': '📅 <b>{date}</b>\n\nСообщений: {count}',
    'calendar.message_line': '• #{id} — {time} — {channel}',
    'calendar.prev_month': '◀',
    'calendar.next_month': '▶',
    'calendar.prev_week': '◀ Неделя',
    'calendar.next_week': 'Неделя ▶',
    'calendar.week_view': 'Неделя',
    'calendar.month_view': 'Месяц',
    'calendar.legend_scheduled': '📅 Отложено',
    'calendar.legend_sent': '✅ Отправлено',
    'calendar.legend_failed': '❌ С ошибкой',
    'calendar.empty': '📪 В этот день сообщений нет.',
    'calendar.no_other_channels': '❌ Других каналов нет.',
    'calendar.select_channel': '📢 Выберите канал для просмотра:',
    'calendar.unavailable_managed': '❌ Календарь недоступен для управляемых каналов.',
    'calendar.channel': '📢 {channel}',
    'calendar.day': '📅 {day}',
    'calendar.view': '📅 Календарь',
    # ---- lang ----
    'lang.english_btn': '🇬🇧 English',
    'lang.sync_offer': '🌐 <b>Синхронизация языка</b>\n\nВ FastSchedule у вас стоит язык <b>{lang}</b>.\n\nПрименить его и здесь?',
    'lang.sync_yes': '✅ Да, использовать {lang}',
    'lang.sync_no': '❌ Нет, оставить текущий',
    'lang.sync_choose': '🌐 Выбрать другой язык',
    'lang.sync_tg_offer': '🌐 Язык интерфейса Telegram — <b>{lang}</b>.\n\nИспользовать его же в FastSchedule?',
    'lang.sync_tg_yes': '✅ Да',
    'lang.sync_tg_no': '❌ Нет',
    'lang.sync_tg_choose': '🌐 Выбрать вручную',
    'lang.sync_not_supported': '⚠️ Язык <b>{lang}</b> пока поддерживается не полностью.\n\nВыберите из доступных языков ниже:',
    'lang.sync_setdate_offer': '🌐 <b>Синхронизация с SetDate</b>\n\nЯзык бота SetDate — <b>{lang}</b>. Синхронизировать и здесь?',
    'lang.sync_setdate_yes': '✅ Да, использовать {lang}',
    'lang.sync_setdate_no': '❌ Нет, оставить текущий',
    'lang.sync_setdate_choose': '🌐 Выбрать другой язык',
    'lang.sync_setdate_applied': '✅ Язык синхронизирован с ботом SetDate!\n\nТеперь оба бота используют язык <b>{lang}</b>.',
    'lang.sync_notify_setdate': '🌐 Язык FastSchedule изменён на <b>{lang}</b>.\n\nБот SetDate обновлён автоматически.',
    'lang.sync_notify_setdate_ok': '✅ Язык SetDate синхронизирован.',
    'lang.sync_disable': 'Отключить автосинхронизацию',
    'lang.sync_enable': 'Включить автосинхронизацию',
    'lang.russian_btn': '🇷🇺 Русский',
    'lang.sync_toggled_on': '✅ Синхронизация языка включена.',
    'lang.sync_toggled_off': '❌ Синхронизация языка отключена.',
    'lang.sync_hide_on': '🔕 Скрыть уведомления о синхронизации между ботами',
    'lang.sync_hide_off': '🔔 Показывать уведомления о синхронизации между ботами',
    'lang.sync_hide_toggled_on': '🔕 Уведомления о синхронизации между ботами будут скрыты',
    'lang.sync_toggled_disabled': 'Синхронизация языка отключена',
    'lang.sync_toggled_enabled': 'Синхронизация языка включена',
    'lang.sync_hide_toggled_off': '🔔 Уведомления о синхронизации между ботами будут показываться',
    # ---- storage ----
    'storage.btn': '💾 Хранилище медиа',
    'storage.select_box': '@@STORAGE@@💾 Выберите хранилище:',
    'storage.is_empty': '@@STORAGE@@📪 Это хранилище пусто.',
    'storage.disabled_message': '⚠️ Хранилище медиа сейчас отключено.',
    'storage.box_btn': '@@STORAGE@@💾 {name}',
    'storage.name_prompt': '@@STORAGE@@📝 Отправьте название для этого хранилища:',
    'storage.rename_prompt': '@@STORAGE@@📝 Отправьте новое название хранилища.\n\nТекущее название: <b>{current_name}</b>',
    'storage.remaining_prompt': '@@STORAGE@@💾 Сколько файлов показать?',
    'storage.content_header': '@@STORAGE@@💾 <b>{name}</b>\n\n{stats}',
    'storage.stats': '@@STORAGE@@📊 {count} шт. | {types}',
    'storage.not_found': '@@STORAGE@@❌ Хранилище не найдено.',
    'storage.invalid_number': '@@STORAGE@@❌ Отправьте корректное положительное число.',
    'storage.deleted': '@@STORAGE@@🗑 Хранилище удалено.',
    'storage.delete_confirm': '@@STORAGE@@⚠️ Удалить это хранилище и всё его содержимое? Действие необратимо.',
    'storage.empty_confirm': '@@STORAGE@@⚠️ Удалить все файлы из этого хранилища?',
    'storage.empty_warning': '@@STORAGE@@⚠️ Все файлы будут удалены навсегда.',
    'storage.items_removed': '@@STORAGE@@🗑 Удалено файлов из хранилища: {count}.',
    'storage.list_legend': '@@STORAGE@@💾 <b>Ваши хранилища медиа</b>\nХранилищ: {count}',
    'storage.many_images_sent': '@@STORAGE@@✅ Отправлено медиафайлов: {count}.',
    'storage.media_sent': '@@STORAGE@@✅ Медиа отправлено',
    'storage.choose_filter': '@@STORAGE@@🔍 Фильтр по типу:',
    'storage.first_media_skipped': '@@STORAGE@@Сохранение медиа пропущено.',
    'storage.copy_types': '@@STORAGE@@Выберите типы для копирования:',
    'storage.move_types': '@@STORAGE@@Выберите типы для перемещения:',
    'storage.add': '@@STORAGE@@➕ Добавить хранилище',
    'storage.video_size_mb': 'Максимальный размер видео: {size} МБ',
    'storage.first_media_free': '💾 <b>Отправьте первое медиа!</b>\n\nТеперь отправьте фото, файл, анимацию, голосовое, аудио, стикер или видеосообщение — сохраню его в <b>«{name}»</b>.\n\n📋 <b>Что можно сохранять:</b>\n• 📸 Фото\n• 📄 Файлы (документы, анимации)\n• 🎵 Аудио и голосовые\n• 🎨 Стикеры и видеосообщения\n• ❌ Видео — <b>только Premium</b>\n\n📦 <b>Ваши лимиты (Free):</b>\n@@STORAGE@@• 1 хранилище, до 100 файлов\n@@STORAGE@@• Без видео в хранилище\n\n💎 <b>Premium открывает:</b>\n@@STORAGE@@• 20 хранилищ, без лимита файлов в каждом\n• 🎬 Загрузку видео (до 50 МБ)\n• 🔐 Резервные копии и экспорт\n\n/skip — пропустить этот шаг',
    'storage.first_media_premium': '💾 <b>Отправьте первое медиа!</b>\n\nТеперь отправьте фото, видео, файл, анимацию, голосовое, аудио, стикер или видеосообщение — сохраню его в <b>«{name}»</b>.\n\n📋 <b>Что можно сохранять:</b>\n• 📸 Фото\n• 🎬 Видео (до 50 МБ)\n• 📄 Файлы, анимации, документы\n• 🎵 Аудио и голосовые\n• 🎨 Стикеры и видеосообщения\n\n📦 <b>Ваши лимиты (Premium):</b>\n@@STORAGE@@• 20 хранилищ, без лимита файлов\n• Видео до 50 МБ каждое\n\n/skip — пропустить этот шаг',
}
