# -*- coding: utf-8 -*-
"""RU batch: remaining small sections A–D."""

PATCH = {
    'about.text': '📋 <b>О боте Fast Scheduler</b>\n\nВерсия: {version}\n\nПланируйте и управляйте постами в Telegram легко и удобно.',
    'about.bot_info': '🤖 Fast Scheduler Bot — @FastSchedulerBot\n\nПланирование сообщений, управление каналами и отслеживание ваших постов.',
    'action.cancelled': '❌ Действие отменено.',
    'action.channel_pick_title': '📢 <b>Выберите канал</b>\n\nВыберите один из подключённых каналов:',
    'action.restricted': '❌ Это действие ограничено.',
    'action.restricted_nonadmin': '❌ Это могут делать только администраторы.',
    'activate.premium_referral': '⭐ Активировать дни',
    'album.label': '🖼 Альбом',
    'album.media_received': '🖼 Получен альбом ({count} шт.). Теперь отправьте дату и время:',
    'album.too_many': '❌ В альбоме Telegram не может быть больше 10 файлов. Лишние файлы пропущены.',
    'all.btn': 'Все',
    'all.features_unlocked': '✅ Все возможности открыты',
    'announcement': '📢 Объявление',
    'monthly_standard_option': '⭐ Стандартная месячная подписка — {price}/мес',
    'monthly_three_option': '3️⃣ 3 месяца — {price} (экономия {full_price})',
    'monthly_six_option': '6️⃣ 6 месяцев — {price} (экономия {full_price})',
    'monthly_pay_monthly_note': '💡 При помесячной оплате: 3 месяца = {three_month_total}, 6 месяцев = {six_month_total}',
    'multi_month_discount_note': '🏷️ <b>Скидка при предоплате: {percent}%</b> — вы платите {discounted} вместо {price}.',
    'archive.progress': '⏳ Создаём архив... {percent}%',
    'are.you_sure': '❓ Вы уверены?',
    'are.you_sure_irreversible': '⚠️ Это действие нельзя отменить.',
    'assign.bot_btn': '🤖 Привязать @{bot_username}',
    'attachment.name': '📎 {name}',
    'auto.renewal': 'Автопродление',
    'autorenew.reenabled': '✅ Автопродление снова включено!\n\nВаша подписка Premium будет продлеваться автоматически.',
    'blocked.alert': '🚫 {reason}',
    'blocked.users': '🚫 Пользователей: {count}',
    'bots.btn': '🤖 Боты ({limit}, {type})',
    'bots.label': '🤖 Боты ({count})',
    'bots.header': '🤖 <b>Боты-отправители</b>',
    'bots.connected_list': '🤖 <b>Ваши боты ({count}/{limit})</b>\n\n{list}',
    'broadcast.add_callback_btn': '➕ Добавить callback-кнопку',
    'broadcasting.to_all': '📢 Отправляем всем пользователям...',
    'build.info': 'Сборка: {build}',
    'bulk.check_on': '@@STORAGE@@✅',
    'bulk.check_off': '@@STORAGE@@⬜',
    'buy.premium_monthly': '💵 На месяц — {price}/мес',
    'buy.premium_yearly': '💵 На год — {price}/год ({savings})',
    'buy.premium_monthly_tg': '⭐ На месяц — {price}/месяц',
    'buy.premium_yearly_tg': '⭐ На год — {price}/год',
    'cache.cleared': '✅ Кэш очищен.',
    'cache.cleared_admin': '✅ Кэш администратора очищен.',
    'callback.button_added': '🔘 Callback-кнопка: {label} → {value}',
    'cancelled.btn': '✅ Отменено.',
    'cancelled.simple': 'Отменено.',
    'cannot.block_admin': '❌ Нельзя заблокировать администратора.',
    'cannot.toggle_admin_premium': 'Нельзя менять Premium-статус другого администратора.',
    'cat.check_off': '❌',
    'cat.check_on': '✅',
    'ch.off': '❌',
    'ch.on': '✅',
    'changelog.text': '📝 <b>Список изменений</b>\n\n{text}',
    'changelog.not_found': '❌ Список изменений не найден.',
    'channels.btn': '📢 Каналы ({limit}, {max}, {type})',
    'channels.connected_line': '📢 Подключено каналов: {count}.',
    'channels.connected': 'Каналы подключены',
    'chat.with_me': '💬 Написать админу',
    'check.again': '🔄 Проверить снова',
    'check.admin_status': '✅ Проверить статус админа',
    'check.subscription': '✅ Проверить подписку',
    'checkbox.on': '✅',
    'checkbox.off': '⬜',
    'checkbox.checked': '✅',
    'checkbox.unchecked': '⬜',
    'checklist.default_title': '📋 Чек-лист',
    'checklist.enter_title': '📋 <b>Создание чек-листа</b>\n\nВведите заголовок чек-листа:',
    'checkout.link_failed': '❌ Не удалось создать ссылку на оплату. Попробуйте позже.',
    'command.not_found': '❌ Команда не найдена.',
    'comment.count': '💬 {count}',
    'compression.help_btn': '🖼️ Подробности о сжатии',
    'compression.progress': '⏳ Сжимаем {label}…',
    'connected.channel_count': '📢 Каналы ({count})',
    'connected.bot_welcome_creator': '👋 <b>Добро пожаловать, {name}!</b>\n\n✅ <b>@{bot}</b> подключён к Fast Scheduler.\n\n📢 <b>Канал:</b> {channel}\n\n<b>Что делает этот бот:</b>\n📨 Публикует отложенные сообщения в ваш канал\n⚠️ Сообщает, если публикация не удалась\n✅ Подтверждает доставку сообщений\n\n<b>Управляйте всем через:</b> @FastSchedulerBot\n\n💡 Посторонние, запустившие этого бота, по умолчанию увидят название вашего канала. Кнопка ниже скрывает его.',
    'contact': '📞 <b>Связь с нами</b>\n\nПоддержка и вопросы:\n@MaximalXP',
    'contact_btn': '💬 Связаться',
    'poll_type_label': 'Опрос',
    'content.received_waiting_date': '✅ Контент получен. Теперь отправьте дату и время:',
    'conversation.closed': '❌ Диалог закрыт.',
    'conversation.closed_text': 'Этот диалог закрыт.',
    'conversation.history': 'История диалога',
    'count.10': '@@STORAGE@@10',
    'count.20': '@@STORAGE@@20',
    'count.30': '@@STORAGE@@30',
    'crypto.payment_text': ' 🪙 <b>CryptoBot — {plan}</b>\n\n<b>Цена:</b> {price}\n\n<a href="{pay_url}">💳 Оплатить криптовалютой</a>\n\n<code>{pay_url}</code>',
    'crypto.payment': '💱 Crypto Bot',
    'crypto.manual_renew_note': '\n\n⚠️ <b>Важно:</b> криптоплатежи не поддерживают автопродление — подписку придётся продлевать вручную после каждого окончания. 💡 <b>Совет:</b> выберите <b>годовой план</b>, чтобы продлевать <b>раз в год</b> вместо каждого месяца (продление — скучно: зачем делать это 12 раз, если можно 1?). Годовая скидка ещё и сэкономит деньги!',
    'crypto.not_configured': '❌ Криптоплатежи не настроены.',
    'crypto.invoice_failed': '❌ Не удалось создать счёт. Попробуйте ещё раз.',
    'current.timezone': '🕐 <b>Текущий часовой пояс:</b> {tz}',
    'custom.btn': 'Свой вариант',
    'custom.cron': '⚙️ Своё расписание (cron)',
    'monthly.btn': '📅 Ежемесячно',
    'monthly.prompt': '📅 <b>Ежемесячное расписание</b>\n\nВ какой день месяца и во сколько?\n\nФормат: <code>ДЕНЬ ЧЧ:ММ</code>\nПример: <code>15 09:00</code>',
    'monthly.schedule': 'Ежемесячно {day}-го числа в {time}',
    'same_day.limit_reached': '⚠️ Достигнут лимит канала: {used}/{limit} сообщений уже запланировано на {day}.\n\nНа один день у канала может быть не больше {limit} сообщений. Распределите их по разным дням или перейдите на Premium для планирования без ограничений.',
    'dashboard.api': '📊 Dashboard API',
    'date.format_hint': 'Формат: ГГГГ-ММ-ДД',
    'date.format_invalid': '❌ Неверный формат даты. Используйте ГГГГ-ММ-ДД.',
    'date.future_required': '❌ Дата должна быть в будущем.',
    'date.received_waiting_media': '✅ Дата получена. Теперь отправьте медиа:',
    'date.format': 'ДД.ММ.ГГГГ',
    'datetime.format_hint': 'Формат: ГГГГ-ММ-ДД ЧЧ:ММ',
    'deleted.count': '🗑 Удалено сообщений: {count}.',
    'deselect.all': 'Снять всё',
    'deselect.all_btn': '❌ Снять выделение',
    'disconnect.channel_btn': '🔗 Отключить канал',
    'disconnect.channel_confirm': '⚠️ <b>Отключить канал?</b>\n\nВы уверены, что хотите отключить <b>{channel}</b>?\n\n• {scheduled} отложенных сообщений будут удалены или переназначены\n• Повторяющиеся сообщения этого канала не переносятся автоматически',
    'disconnect.warning_scheduled': '⚠️ {count} отложенных сообщений будут удалены или переназначены.',
    'disconnect.downsides': '⚠️ После отключения: все отложенные сообщения этого канала будут удалены.',
    'disconnect.channel': '🔌 Отключить канал',
    'discount.percent_off': 'скидка {percent}%',
    'discount.amount_off': 'выгода {amount}',
    'discounted.price': 'цена со скидкой',
    'dl.all': '@@STORAGE@@Все хранилища',
    'dl.box': 'Это хранилище',
    'donate.btn': '💰 Поддержать',
    'donate.text': '💰 <b>Поддержите Fast Scheduler Bot</b>\n\nЕсли бот вам полезен, вы можете поддержать разработку.',
    'donate.thanks': '❤️ Спасибо за поддержку!',
    'done.btn': '✅ Готово',
    'done.broadcast_btn': '✅ Рассылка завершена',
    'dub.done': '✅ Сообщение продублировано!',
    'dub.usage': 'Использование: /dub &lt;message_id&gt; — дублирует существующее отложенное сообщение.',
    'dup': 'Дубль',
    'edit.message_prompt': '✏️ <b>Редактирование сообщения</b>\n\nОтправьте новое содержимое для сообщения #{id}.',
    'edit.not_found': '❌ Сообщение не найдено или не может быть отредактировано.',
    'edit.usage': 'Использование: /edit &lt;message_id&gt; — открывает редактирование указанного сообщения.',
    'edit.btn': '✏️ Изменить',
    'edit.report_btn': '✏️ Изменить отзыв',
    'empty.btn': '@@STORAGE@@🗑 Очистить',
    'empty.message': '❌ Содержимое сообщения не может быть пустым.',
    'en': 'English',
    'errors.title': '⚠️ Ошибки',
    'exit.admin_mode': '🚪 Выйти из режима админа',
    'faq.btn': 'FAQ',
    'feature.disabled': '❌ Эта функция сейчас отключена.',
    'file.too_large': '❌ Файл слишком большой ({size}). Максимум — {max}.',
    'file.parse_error': '❌ Не удалось разобрать этот файл.',
    'files.btn': '@@STORAGE@@Файлы',
    'first.seen': 'Первый раз: {date}',
    'flood.wait': '⏳ Слишком много запросов. Ждём {seconds} с...',
    'forward.not_channel': '❌ Это сообщение не из канала. Перешлите пост из вашего канала.',
    'friday': 'Пятница',
    'from.today': '📅 С сегодняшнего дня',
    'from.tomorrow': '📅 С завтрашнего дня',
    'fsback.nopw_btn': '🔒 Без пароля',
    'fspback.pw_btn': '🔒 С паролем',
    'fuzzy.match_single': '💡 Возможно, вы имели в виду: /{cmd} — {desc}',
    'fuzzy.match_multi': '💡 Несколько совпадений:\n{lines}',
    'generating.export': '⏳ Готовим экспорт...',
    'global.timezone': 'Глобальный часовой пояс',
    'global.error_msg': 'Произошла ошибка. Попробуйте ещё раз.',
    'globe.icon': '🌐',
    'go.to_sender_bot': '🤖 Открыть @{bot}',
    'go.to_main_bot': '🏠 Открыть @FastSchedulerBot',
    'go.to_sender_bot_for_channel': '🤖 Открыть @{bot} для @{channel}',
    'goto.sender_bot_btn': '🤖 Открыть бота-отправителя',
    'grant.premium_title': '🎯 <b>Выдать Premium</b>\n\nПользователь: <code>{user_id}</code>\n\nВыберите тип срока:',
    'hide.channel_toggled': '{state} видимость для {channel}.\n\nПосторонние теперь увидят канал как «{display}» — вы и админы канала видите его полностью.',
    'images.btn': '@@STORAGE@@Изображения',
    'importing.with_media': '⏳ Импортируем вместе с медиа...',
    'importing.without_media': '⏳ Импортируем без медиа...',
    'internal.error_alert': '❌ Внутренняя ошибка. Попробуйте ещё раз.',
    'invoice.title_monthly': 'FastSchedule Premium — месяц',
    'invoice.title_yearly': 'FastSchedule Premium — год',
    'invoice.label': '⭐ Подписка Premium',
    'invoice.sent_check': '📨 Счёт отправлен! Проверьте сообщения в Telegram — там будет запрос на оплату.',
    'items.count': '{count} шт.',
    'json.btn': 'JSON',
    'keep.old_media': '@@STORAGE@@Оставить текущее медиа',
    'last.seen': 'Был(а): {date}',
    'leaderboard': '🏆 Рейтинг',
    'leaderboard_all': 'За всё время',
    'leaderboard_btn': '🔜 Рейтинг',
    'leaderboard_channel_line': '📢 {channel}',
    'leaderboard_comments': '💬 Комментарии',
    'leaderboard_month': 'Этот месяц',
    'leaderboard_no_data': '📪 Данных для рейтинга пока нет.',
    'leaderboard_period_line': '📅 {period}',
    'leaderboard_reactions': '📷 Реакции',
    'leaderboard_today': 'Сегодня',
}
