# -*- coding: utf-8 -*-
"""RU batch: media remainder."""

PATCH = {
    'media.type_video_note': '@@STORAGE@@Видеосообщение',
    'media.label_photo': '@@STORAGE@@Фото',
    'media.label_video': '@@STORAGE@@Видео',
    'media.label_document': '@@STORAGE@@Документ',
    'media.label_animation': '@@STORAGE@@Анимация',
    'media.label_voice': '@@STORAGE@@Голосовое',
    'media.label_audio': '@@STORAGE@@Аудио',
    'media.label_sticker': '@@STORAGE@@Стикер',
    'media.label_video_note': '@@STORAGE@@Видеосообщение',
    'media.type_location': '📍 Геолокация',
    'media.label_location': '📍 Геолокация',
    'media.type_venue': '🏢 Место',
    'media.label_venue': '🏢 Место',
    'media.exceeds_limit': '@@STORAGE@@❌ Файл превышает лимит размера ({limit} МБ).',
    'media.exceeds_premium_limit': '@@STORAGE@@❌ Файл превышает максимальный лимит размера ({limit} МБ).',
    'media.attached_info': 'Прикреплено файлов: {count}',
    'media.saved_multiple': '@@STORAGE@@✅ Медиафайлов сохранено в хранилище: {count}.',
    'media.moved': '@@STORAGE@@✅ Медиа перемещено.',
    'media.text_without_media': '@@STORAGE@@❌ Для этого действия с хранилищем нужны медиафайлы.',
    'media.text': 'Медиа',
    'media.caption_template': '@@STORAGE@@{caption}',
    'media.icon_photo': '📷',
    'media.icon_video': '📹',
    'media.icon_location': '📍',
    'media.caption_too_long': '❌ Подпись слишком длинная ({count} симв.). Максимум — {max} симв.',
    'media.download': '📥 Скачать',
    'media.storage_list': '@@STORAGE@@💾 <b>Список хранилища</b>\n\n{legend}\n\nФайлов: {media_count} — Страница {page}/{total_pages}',
    'media.received_waiting_date': '📷 {media_type} получено. Теперь отправьте дату и время:',
    'media.emoji_received_waiting_date': '✨ {media_type} получено. Теперь отправьте дату и время:',
    'media.doc_text_received': '📄 Получено: {media_type} + текст.\n\n⚠️ <b>Внимание:</b> если вы хотите импортировать отложенные сообщения, удалите подпись у документа и отправьте его снова.',
    'media.text_received_waiting_date': '✅ Получено: {media_type} + текст. Теперь отправьте дату и время:\n\nПример: <code>25.12.2024 10:00</code> или <code>10:00</code> для сегодня.\nТекст будет опубликован вместе с {media_type}.',
    'media.updated_confirm': '✅ Медиа обновлено для задания #{job_id}.',
    'media.renamed_confirm': '✏️ Переименовано в {name}.',
    'media.pick_video': '🎬 {name}',
    'media.storage_count': '💾 Файлов в хранилище',
    'media.download_sent': '📥 Вот файл:',
    'media.page_size_set': '✅ Размер страницы задан.',
    'media.image': '🖼 Изображение',
    'media.file': '📄 Файл',
    'media.type_poll': 'Опрос',
    'media.type_checklist': 'Чек-лист',
    'media.items_total': '💾 Всего файлов в хранилище',
    'media.pick_photo': '📷 {name}',
}
