# -*- coding: utf-8 -*-
"""RU batch: remaining small sections L–Z."""

PATCH = {
    'leaderboard_top_count_line': '🏆 #{count}',
    'leaderboard_views': '👁 Просмотры',
    'leaderboard_week': 'Эта неделя',
    'leaderboard_year': 'Этот год',
    'learn.benefits': '💡 Узнать больше',
    'legal.menu_text': '📖 <b>Правовые документы</b>\n\nОзнакомьтесь с нашими политиками и условиями.',
    'legal.privacy_btn': '🛡 Политика конфиденциальности',
    'legal.refund_btn': '💰 Политика возврата',
    'legal.terms_btn': '📖 Условия использования',
    'legal.website_btn': '🌐 Сайт',
    'limit.reached': '⚠️ <b>Достигнут лимит</b>\n\nВы исчерпали лимит для <b>{type}</b> ({limit}).\n\n{upsell}',
    'link.copied': '🔗 Ссылка скопирована!',
    'list.empty': '📪 Список пуст.',
    'list.media_main_0': '@@STORAGE@@📎 Хранилище медиа',
    'loading.text': '⏳ Загрузка...',
    'locked.channel_calendar': '🔴 <b>Календарь недоступен</b>\n\nУправление этим каналом ведётся через <b>@{bot}</b>.\n\nКалендарь доступен в @{bot}.',
    'maintenance.mode': '⚠️ Бот на техническом обслуживании. Попробуйте позже.',
    'manage.promocodes': '📋 Управление промокодами',
    'management.btn': '⚙️ Настройки',
    'management.menu_title': '⚙️ <b>Настройки канала</b>',
    'management.menu_text': 'Настройка канала <b>{channel}</b>.\n\nКаждый бот-отправитель ведёт свой канал — это меню относится только к этому каналу.',
    'management.menu_only_sender_bot': 'Это меню доступно только в режиме бота-отправителя.',
    'mark.spam': '🚫 Отметить как спам',
    'max.bots_reached': '⚠️ Подключено максимальное количество ботов ({limit}).\n\nОтключите одного из ботов или перейдите на Premium, чтобы добавить больше.',
    'max.media_size_mb': 'Максимальный размер медиа: {size} МБ',
    'max.video_size_mb': 'Максимальный размер видео: {size} МБ',
    'media.': '📁 Медиа',
    'memo.icon': '📝',
    'mgmt.menu_header': '⚙️ <b>Настройки канала</b>\n\nВыберите пункт ниже, чтобы настроить этот канал:',
    'mgmt.moved_auto': '✅ <b>Управление передано @{bot}</b>\n\nВаш канал {channel} теперь полностью управляется ботом-отправителем. Планируйте и управляйте сообщениями через @{bot}.',
    'modify.replace': '🔄 Заменить',
    'modify.ask_content': '📝 Отправьте новое содержимое:',
    'modify.ask_date': '📅 Отправьте новую дату и время:',
    'modify.done': '✅ Сообщение #{id} изменено.',
    'modify.ask_poll_content': 'Отправьте новый опрос на замену существующего или отправьте текст, чтобы оставить опрос и обновить только его описание:',
    'monday': 'Понедельник',
    'more.btn': '▶ Ещё',
    'move.btn': '@@STORAGE@@Переместить',
    'move.all_btn': '@@STORAGE@@Переместить всё',
    'msg.list_menu': 'Содержимое меню',
    'multi.schedule': '📅 Мультипланирование',
    'multi.channel_select': 'Выберите каналы для отправки',
    'next.btn': '➡️ Далее',
    'nopromocodes': '📪 Доступных промокодов нет.',
    'normal.photo_mode': '📷 Обычный',
    'not.found': '❌ Не найдено.',
    'not.saved': '❌ Не сохранено.',
    'notification.feedback': '💬 Новый отзыв от {user}:\n\nТема: {subject}\n{description}',
    'notification.complaint': '⚠️ Жалоба от {user}:\n\n{description}',
    'odt.btn': 'ODT',
    'onboarding.completed': '✅ Знакомство завершено! Вы готовы пользоваться ботом.',
    'onboarding.skip': '⏭ Пропустить знакомство',
    'open.main_bot': '🏠 Открыть @FastSchedulerBot',
    'open.channel_btn': '📢 Открыть канал',
    'open.sender_bot_stats': '📊 Открыть статистику',
    'open.channel': '🔗 Открыть канал',
    'other.btn': '@@STORAGE@@Другое',
    'page.btn': '📄 Страница {current} из {total}',
    'page.info': 'Страница {page} из {total}',
    'pager.next': 'Далее ▶',
    'pager.prev': '◀ Назад',
    'pause.btn': '⏸️ Пауза',
    'payment.error': '❌ Ошибка оплаты: {error}',
    'pending.schedule_btn': '📅 Ожидающие отложенные',
    'pending.recurring_btn': '🔄 Ожидающие повторяющиеся',
    'pending.bot_ready': '✅ @{bot_username} готов!',
    'photo.attached': '📷 Фото прикреплено.',
    'photos.received': '📷 Получено фото: {count}.',
    'plan.yearly': 'На год',
    'plan.monthly': 'На месяц',
    'plan.monthly_3': '3 месяца предоплатой',
    'plan.monthly_6': '6 месяцев предоплатой',
    'preference.saved': '✅ Настройка сохранена.',
    'prev.btn': '◀ Назад',
    'preview.count_prompt': '@@STORAGE@@💾 Сколько файлов показать?',
    'preview.eye': '👁',
    'preview.btn': '👁 Предпросмотр',
    'previous': '⬅️ Назад',
    'privacy.policy': '🛡 Политика конфиденциальности',
    'private.channel': 'частный канал',
    'proceed.to_payment': '💳 Перейти к оплате',
    'processed.media': '📁 Обработано медиафайлов: {count}.',
    'processing': '⏳ Обработка...',
    'promocode.invalid': '❌ Неверный промокод.',
    'promocode.usage_hint': '💡 Введите промокод, чтобы получить скидку на Premium.',
    'promocode.applied': '✅ Промокод {code} применён! {discount_text} ({remaining})',
    'promocode.active': '🎟 {code}: {discount_text} ({remaining})',
    'promocodes.list_title': '🎟 <b>Промокоды</b>\n\n{list}',
    'promocodes.none': 'Активных промокодов нет.',
    'random.photo_mode': '🎲 Случайно',
    'random.photo_attached': '📷 Случайное фото прикреплено ({count}).',
    'rc.deeplink_text': '🔄 Повторяющиеся — @{bot}',
    'reconnect.bot': '🔄 Переподключить',
    'refresh.btn': '🔄 Обновить',
    'refresh.button': '🔄 Обновить',
    'remember.keep_old_media': '@@STORAGE@@💡 Запомнить мой выбор',
    'remove.bot': '🗑 Удалить бота',
    'remove.bot_btn': '🗑 Удалить бота',
    'remove.bot_item': '🗑 Удалить @{username}',
    'remove.default_channel': '❌ Убрать канал по умолчанию',
    'rename.box_btn': '@@STORAGE@@✏️ Переименовать хранилище',
    'rename.btn': '@@STORAGE@@Переименовать',
    'replace.bot': '🔄 Заменить бота',
    'reply.to_admin': '📩 Ответить админу',
    'reply.to_admin_button_text': '📩 Ответить админу',
    'reply.to_user': '📩 Ответить пользователю',
    'resume.btn': '▶️ Продолжить',
    'retry.btn': '🔄 Повторить',
    'retry.button': '🔄 Повторить',
    'rtf.btn': 'RTF',
    'saturday': 'Суббота',
    'save.btn': '✅ Сохранить',
    'saved': '✅ Сохранено.',
    'sc.deeplink_text': '📅 SetDate — @{bot}',
    'selected.count': 'Выбрано: {count}',
    'sent.simple': '✅ Отправлено',
    'sent.today': '📤 Отправлено сегодня: {count}',
    'server.time': 'Время на сервере: {time}',
    'session.expired': '⏳ Сессия истекла. Начните заново.',
    'session.cancelled': '❌ Сессия отменена.',
    'set.default_ch_btn': '⭐ Сделать основным',
    'set.default_channel': '⭐ Сделать основным',
    'settings.btn': '⚙️ Настройки',
    'share.btn': '🔗 Поделиться',
    'show.attached_files': '📁 Показать прикреплённые файлы',
    'sig.delete_btn_icon': '❌',
    'sig.edit_btn_icon': '✏️',
    'sig.toggle_btn_icon': '🔄',
    'single.post_btn': '📄 Один пост',
    'skip.btn': '⏭ Пропустить',
    'skip.button': '⏭ Пропустить',
    'skip.photos': '⏭ Пропустить фото',
    'snapshot.label': '📸 #{sid} ({cats})',
    'star.default_channel_suffix': ' ⭐',
    'stars.payment': '⭐ Telegram Stars',
    'stars.payment_failed': '❌ Оплата через Telegram Stars не удалась или была отменена.',
    'stars.payment_link_prompt': 'Нажмите кнопку ниже, чтобы открыть платёжную панель:',
    'stars.auto_renew_note': '\n\n✅ <b>Автопродление включено:</b> эта стандартная месячная подписка Telegram Stars продлевается каждые 30 дней. Отмена — в меню Premium; доступ сохраняется до конца оплаченного периода.',
    'stars.yearly_one_time_note': '\n\nℹ️ <b>Разовый платёж:</b> этот годовой план Stars оплачивается один раз. Он действует год; через год мы напомним выбрать и оплатить новый план.',
    'statistics': '📊 Статистика',
    'stop.btn': '⏹ Остановить',
    'store.media_save_prompt': '@@STORAGE@@💾 Сохранить в хранилище медиа?',
    'subscribe.channels': '📢 Подписаться на каналы',
    'subscribe.required': '⚠️ <b>Нужна подписка</b>\n\nПодпишитесь, чтобы открыть все возможности:',
    'subscribed.users': '👥 Подписчиков: {count}',
    'subscription.success': '✅ <b>Спасибо за подписку!</b>\n\nВсе возможности теперь доступны.',
    'subscription.failed': '❌ <b>Вы подписаны не на все каналы</b>\n\nПожалуйста, подпишитесь на все обязательные каналы:',
    'subscription.lost': '⚠️ <b>Подписка потеряна!</b>\n\nВы вышли из одного из наших каналов.\nВозможности Premium отключены.\n\nПодпишитесь снова, чтобы вернуть доступ.',
    'suggested.command_btn': '💡 {cmd}',
    'sunday': 'Воскресенье',
    'supported.formats': '📁 Поддерживаемые форматы: {formats}',
    'telegram.error': '❌ Ошибка Telegram: {error}',
    'terms.of_service': '📖 Условия использования',
    'terms.accept_btn': '✅ Принять',
    'terms.accept_required': '⚠️ Чтобы пользоваться ботом, нужно принять Условия использования.',
    'terms.accepted_thanks': '✅ Спасибо за принятие Условий использования!',
    'thursday': 'Четверг',
    'time.format_hint': 'Формат: ЧЧ:ММ (24 ч)',
    'time.format': 'ДД.ММ.ГГГГ ЧЧ:ММ',
    'tips.cmd.addbot': '/addbot — Подключить своего Telegram-бота',
    'tips.cmd.backup': '/backup — Создать полную резервную копию',
    'tips.cmd.bots': '/bots — Управление ботами-отправителями',
    'tips.cmd.calendar': '/calendar — Календарь отложенных сообщений',
    'tips.cmd.channel': '/channel — Управление подключённым каналом',
    'tips.cmd.delete': '/delete — Удалить сообщения',
    'tips.cmd.export': '/export — Экспорт данных',
    'tips.cmd.feedback': '/feedback — Связаться с поддержкой',
    'tips.cmd.help': '/help — Показать справку',
    'tips.cmd.import': '/import — Импорт сообщений из файла',
    'tips.cmd.lang': '/lang — Сменить язык бота',
    'tips.cmd.language': '/language — Сменить язык бота',
    'tips.cmd.list': '/list — Список всех отложенных сообщений',
    'tips.cmd.listbots': '/listbots — Список всех подключённых ботов',
    'tips.cmd.premium': '/premium — Тарифы и подписка Premium',
    'tips.cmd.recurring': '/recurring — Создать повторяющееся сообщение',
    'tips.cmd.referral': '/referral — Реферальная программа — бесплатные дни Premium',
    'tips.cmd.removebot': '/removebot — Отключить подключённого бота',
    'tips.cmd.schedule': '/schedule — Запланировать новое сообщение',
    'tips.cmd.search': '/search — Поиск по отложенным сообщениям',
    'tips.cmd.setchannel': '/setchannel — Сменить канал по умолчанию',
    'tips.cmd.start': '/start — Перезапустить бота и открыть главное меню',
    'tips.cmd.stats': '/stats — Посмотреть вашу статистику',
    'tips.cmd.storage': '@@STORAGE@@/storage — Открыть хранилище медиа',
}
