# -*- coding: utf-8 -*-
"""RU batch: report section (90 strings)."""

PATCH = {
    'report.title': '📊 Отчёты',
    'report.btn': '📊 Создать отчёт',
    'report.create_title': '📊 <b>Создание отчёта</b>',
    'report.type_daily': 'Ежедневная сводка',
    'report.type_weekly': 'Недельный отчёт',
    'report.type_monthly': 'Месячный отчёт',
    'report.type_custom': 'Свой период',
    'report.type_summary': '📊 Сводка',
    'report.type_leaderboard': '🏆 Рейтинг',
    'report.type_comments': '💬 Самые обсуждаемые',
    'report.type_reactions': '❤️ Самые реагируемые',
    'report.select_type': '📝 Выберите тип отчёта:',
    'report.email_prompt': '📨 Введите email для получения отчёта:',
    'report.email_skip': '⏭ Пропустить email',
    'report.email_invalid': '❌ Неверный адрес email.',
    'report.email_confirmed': '📨 Отчёт будет отправлен на {email}',
    'report.generating': '⏳ Формируем отчёт...',
    'report.ready': '✅ Отчёт готов!',
    'report.download_btn': '📥 Скачать отчёт',
    'report.no_data': '❌ Данных для отчёта нет.',
    'report.send_btn': '📤 Отправить',
    'report.channel_prompt': '📢 Выберите канал для отчёта:',
    'report.deleted': '🗑 Отчёт удалён.',
    'report.deleted_text': '✅ Отчёт удалён.',
    'report.metric_comments': '💬 Комментарии: {count}',
    'report.metric_reactions': '📷 Реакции: {count}',
    'report.metric_views': '👁 Просмотры: {count}',
    'report.name_invalid': '❌ Неверное имя отчёта. Используйте буквы, цифры и подчёркивания.',
    'report.name_prompt': '📝 Отправьте название для этого отчёта:',
    'report.not_found': '❌ Отчёт не найден.',
    'report.pause_btn': '⏸️ Пауза',
    'report.rename_prompt': '📝 Отправьте новое название для этого отчёта:',
    'report.resume_btn': '▶️ Возобновить',
    'report.stats_avg_comments': 'Средние комментарии: {avg}',
    'report.stats_avg_reactions': 'Средние реакции: {avg}',
    'report.stats_avg_views': 'Средние просмотры: {avg}',
    'report.stats_channel': 'Канал: {name}',
    'report.stats_note': '📝 Заметка: {text}',
    'report.stats_title': '📊 Статистика отчёта',
    'report.stats_top_reactions': '🔥 Топ-реакции: {reactions}',
    'report.stats_total': 'Всего: {total}',
    'report.stats_type': 'Тип: {type}',
    'report.status_active': '✅ Активен',
    'report.status_paused': '⏸ На паузе',
    'report.toggled': '✅ Статус отчёта изменён.',
    'report.toggled_text': 'Статус отчёта изменён.',
    'report.line_channel': '📢 {channel}: {text}',
    'report.line_warning': '⚠️ {text}',
    'report.header': '📊 <b>{name}</b>',
    'report.status_line': '✅ Статус: {status}',
    'report.renamed': '✏️ Отчёт переименован в {name}.',
    'report.line_calendar': '📅 {text}: {value}',
    'report.created_line': 'Создан: {created}',
    'report.line_comments': '💬 {count} комм. — {text}',
    'report.cron_line': '⏰ {cron}',
    'report.channel_line': '📢 {channel}',
    'report.interval_prompt': '📅 Выберите интервал для {name}:',
    'report.item_cron_line': '⏰ {cron}',
    'report.line_reactions': '📷 {count} реакций — {text}',
    'report.metric_header': '📊 {metric}',
    'report.line_chart': '📊 {text}',
    'report.type_line': 'Тип: {type}',
    'report.line_total': '📊 Всего {count} — {text}',
    'report.line_views': '👁 {count} просм. — {text}',
    'report.created': '✅ Отчёт создан: {name} ({interval_label})',
    'report.item_line': '📋 #{id} — {name} ({status})',
    'report.line_trophy': '🏆 {text}',
    'report.free_limit_reached': '⚠️ <b>Достигнут лимит бесплатного тарифа</b>\n\nБесплатные пользователи могут иметь до 3 активных автоматических отчётов. Вы достигли этого лимита.\n\n💎 <b>Перейдите на Premium</b> — отчёты без ограничений со своими расписаниями!',
    'report.top_line': '📋 <b>Топ {count}</b>',
    'report.channel_link': '📢 {channel}',
    'report.confirm_pause': '⏸ Приостановить этот отчёт?',
    'report.confirm_pause_yes': '✅ Да, на паузу',
    'report.confirm_resume': '▶️ Возобновить этот отчёт?',
    'report.confirm_resume_yes': '✅ Да, возобновить',
    'report.created_date': '📅 Создан: {date}',
    'report.cron_custom': '⏰ Свой: {cron}',
    'report.delete_confirm': '⚠️ Удалить этот отчёт?',
    'report.delete_no': '❌ Отмена',
    'report.delete_yes': '✅ Да, удалить',
    'report.edit_btn': '✏️ Изменить',
    'report.edit_settings': '⚙️ Изменить настройки',
    'report.info_btn': 'ℹ️ Информация',
    'report.next_send': '📅 Следующая отправка: {time}',
    'report.no_reports': '📭 Отчётов пока нет.',
    'report.paused': '⏸ Отчёт на паузе.',
    'report.prev_send': '📅 Предыдущая отправка: {time}',
    'report.rename_btn': '✏️ Переименовать',
    'report.resumed': '▶️ Отчёт возобновлён.',
    'report.total_sent': '📊 Всего отправлено: {count}',
    'report.updated': '✅ Отчёт <b>{name}</b> обновлён.\n\nНовое расписание: {interval_label}.',
}
