# -*- coding: utf-8 -*-
"""RU batch: stats section (88 strings)."""

PATCH = {
    'stats.title': '📊 Статистика',
    'stats.channel_title': '📊 <b>Статистика канала</b>',
    'stats.overall_header': '📊 <b>Общая статистика</b>',
    'stats.overview_title': '📊 <b>Обзор статистики</b>',
    'stats.period_today': 'Сегодня',
    'stats.period_week': 'Эта неделя',
    'stats.period_month': 'Этот месяц',
    'stats.period_all': 'За всё время',
    'stats.period_custom': 'Свой период',
    'stats.select_period': '📅 Выберите период:',
    'stats.total_sent': '✅ Всего отправлено: {count}',
    'stats.total_failed': '❌ С ошибками: {count}',
    'stats.total_pending': '⏳ В ожидании: {count}',
    'stats.success_rate': '✅ Доля успешных: {percent}%',
    'stats.channel_breakdown': '📢 По каналам:',
    'stats.channel_line': '{name}: отправлено {sent}, с ошибками {failed}',
    'stats.no_data': '📪 За этот период данных нет.',
    'stats.daily_header': '📆 По дням:',
    'stats.daily_line': '{date}: отправлено {sent}, с ошибками {failed}',
    'stats.busiest_day': '📅 Самый активный день: {date} ({count} сообщ.)',
    'stats.avg_sent_per_day': '📊 В среднем в день: {avg}',
    'stats.chart_btn': '📊 График',
    'stats.detailed_btn': '📊 Подробный отчёт',
    'stats.no_channel_selected': '❌ Канал не выбран.',
    'stats.leaderboard_title': '🔜 <b>Рейтинг</b>\n\nЛучшие сообщения и каналы.',
    'stats.leaderboard_by_views': 'По просмотрам',
    'stats.leaderboard_by_posts': 'По постам',
    'stats.leaderboard_empty': 'Данных пока нет.',
    'stats.leaderboard_position': '#{pos}',
    'stats.leaderboard_content': '📋 {content}',
    'stats.leaderboard_channel': '📢 {channel}',
    'stats.leaderboard_views': '👁 {views} просм.',
    'stats.leaderboard_posts': '📤 {posts} постов',
    'stats.leaderboard_btn': '🔜 Рейтинг',
    'stats.refresh_btn': '🔄 Обновить',
    'stats.date_from': 'С:',
    'stats.date_to': 'По:',
    'stats.created': 'Создано: {count}',
    'stats.dashboard_title': '📊 <b>Панель</b>',
    'stats.note_text': '📝 Заметки: {count}',
    'stats.recurring': 'Повторяющихся: {count}',
    'stats.scheduled': 'Отложено: {count}',
    'stats.sent_today': 'Отправлено сегодня: {count}',
    'stats.sent_total': 'Всего отправлено: {count}',
    'stats.view_note_formatted': '📝 {note}',
    'stats.view_title_formatted': '📊 {title}',
    'stats.view_avg_reactions_formatted': '💬 Средние реакции: {count}',
    'stats.view_top_reactions_formatted': '🔥 Топ-реакции: {reactions}',
    'stats.total_line': '📊 Всего: {count}',
    'stats.scheduled_line': '📅 Отложено: {count}',
    'stats.avg_views_line': '👁 Средние просмотры: {count}',
    'stats.channel_btn': '📢 {display} (@{uname})',
    'stats.channel_header': '📢 {display}',
    'stats.avg_reactions_line': '💬 Средние реакции: {count}',
    'stats.avg_comments_line': '💬 Средние комментарии: {count}',
    'stats.view_avg_comments_formatted': '💬 Средние комментарии: {count}',
    'stats.leaderboard_top': '🏆 Топ {limit}',
    'stats.view_channel_formatted': '📢 {channel}',
    'stats.view_avg_views_formatted': '👁 Средние просмотры: {count}',
    'stats.view_messages_formatted': '📋 {count}',
    'stats.leaderboard_period': '📅 {period}',
    'stats.channel_nobot_btn': '📢 {display}',
    'stats.metric_views': 'Самые просматриваемые',
    'stats.metric_comments': 'Самые обсуждаемые',
    'stats.metric_reactions': 'Самые реагируемые',
    'stats.time_day': 'Сегодня',
    'stats.time_week': 'Последние 7 дней',
    'stats.time_month': 'Последние 30 дней',
    'stats.time_year': 'Последний год',
    'stats.time_all': 'За всё время',
}
