# -*- coding: utf-8 -*-
"""RU batch: channel section (58 strings)."""

PATCH = {
    'channel.btn': '📢 Канал',
    'channel.menu_title': '📢 <b>Каналы</b>\n\nУправляйте подключёнными каналами и их настройками.',
    'channel.tz_line': '🕐 {tz}',
    'channel.connect_new': '📢 Подключить канал',
    'channel.bot_tag': '🤖 @{bot}',
    'channel.prompt': '📢 <b>Подключение канала</b>\n\nВыберите один из способов:\n\n<b>1️⃣ Публичный канал</b>\nОтправьте ссылку: <code>https://t.me/yourchannel</code> или просто <code>@yourchannel</code>\n\n<b>2️⃣ Приватный канал</b>\nОтправьте ссылку-приглашение: <code>https://t.me/c/1234567890</code> (скопируйте её из любого поста канала)\n\n<b>3️⃣ Любой канал</b>\nПерешлите мне любое сообщение из канала\n\nЯ проверю, что вы админ, и подключу канал.\n\n<b>Требования:</b>\n• Вы должны быть админом канала\n• Бот (@FastSchedulerBot) должен быть добавлен админом',
    'channel.connected': '✅ Канал <b>{channel}</b> подключён!',
    'channel.connected_basic': '✅ Канал подключён! Теперь можно планировать для него сообщения.',
    'channel.connected_success': '✅ Канал <b>{channel}</b> успешно подключён!\n\nГлавный бот теперь имеет доступ к вашему каналу.\n\n<b>Следующий шаг: подключите бота-отправителя.</b>\nБот-отправитель нужен для управления каналом и публикации отложенных сообщений. Откройте раздел <b>Боты</b>, чтобы создать нового или подключить существующего.',
    'channel.connected_success_user': '✅ Канал <b>{channel}</b> подключён! Полное подтверждение отправлено вам главным ботом.',
    'channel.sender_bot_required': '🤖 <b>Нужен бот-отправитель</b>\n\nЭтот канал нельзя управлять из главного бота. Подключите и верифицируйте бота-отправителя с правом <b>Публикация сообщений</b> для этого канала. Если бот уже подключён — добавьте его администратором и нажмите <b>Проверить снова</b>.',
    'channel.connected_all_set': '✅ Всё готово! Канал <b>{channel}</b> активен.\n\nКанал привязан к ожидающим сообщениям: {count}.',
    'channel.disconnected': '❌ Канал <b>{channel}</b> отключён.\n\nОтложенных сообщений удалено или переназначено: {redirected}.',
    'channel.channel_hidden_done': '✅ Канал теперь скрыт от посторонних.',
    'channel.channel_visible_done': '✅ Канал снова виден посторонним.',
    'channel.not_found': '❌ Канал не найден. Возможно, он удалён или бот больше не админ.',
    'channel.invalid_link': '❌ Это не похоже на ссылку на канал.\n\nОтправьте один из вариантов:\n• Публичная ссылка: <code>https://t.me/yourchannel</code> или <code>@yourchannel</code>\n• Приватная ссылка: <code>https://t.me/c/1234567890</code>\n• Или перешлите любой пост из канала',
    'channel.invalid_message': '❌ Перешлите сообщение <b>из вашего канала</b>, а не из личного чата или группы.',
    'channel.connect_error': '❌ Не удалось подключить канал. Проверьте:\n• Бот (@FastSchedulerBot) — админ в канале\n• Ссылка или пересланное сообщение — из самого канала\n• Вы владелец канала или админ с правами',
    'channel.max_reached': '⚠️ Достигнут лимит каналов ({limit}).\n\nОтключите один из каналов или перейдите на Premium, чтобы подключить больше.',
    'channel.verify_failed_simple': '❌ Не удалось проверить. Я не смог подтвердить, что вы админ этого канала.\n\nУбедитесь:\n1. Бот — админ в вашем канале\n2. Вы переслали реальный пост из канала',
    'channel.invalid_channel_format': '❌ Неверный формат канала.',
    'channel.redirect_count': '📦 Отложенных сообщений перенаправлено в этот канал: {count}.',
    'channel.redirect_recurring_count': '🔄 Повторяющихся сообщений ({count}) остались на прежнем канале. Обновите их отдельно.',
    'channel.info_text': '📢 <b>О канале</b>\n\n<b>{channel}</b>\n\nРоль: {role}\nБот-админ: {bot_admin}\nБот-отправитель: @{bot}\nСкрыт: {hidden}\nЧасовой пояс: {tz}\n\n<b>Статистика:</b>\nОтложено: {scheduled}\nПовторяющихся: {recurring}\nОтправлено: {sent}',
    'channel.info_unknown_time': 'неизвестно',
    'channel.pick_free': '🆓 Свободный: {channel}',
    'channel.pick_managed': '🤖 Управляемый: {channel}',
    'channel.locked_desc': '🔒 <b>Канал заблокирован</b>\n\nКаналом управляет бот-отправитель. Используйте @{bot}.',
    'channel.has_bot': '✅ У канала есть бот: @{bot}',
    'channel.no_bot': '❌ К каналу не подключён бот.',
    'channel.visibility_hidden': '👻 Скрыт (виден как «частный канал»)',
    'channel.visibility_visible': '👁 Виден ({channel})',
    'channel.visibility_state': 'Видимость: {state}',
    'channel.bot_not_admin_simple': '❌ Бот должен быть админом в этом канале.',
    'channel.limit_premium_reached': '⚠️ Достигнут лимит каналов. Перейдите на Premium, чтобы подключить больше.',
    'channel.stats_title': '📊 <b>Канал: {name}</b>',
    'channel.user_not_admin_simple': '❌ Вы должны быть админом в этом канале.',
    'channel.check_off': '❌',
    'channel.check_on': '✅',
    'channel.changed_notice': '✅ Старый канал <code>{old_channel}</code> будет отключён.',
    'channel.sender_bot_not_admin': '❌ Бот-отправитель {bot} не админ в этом канале.\n\nСначала добавьте {bot} администратором и попробуйте снова.',
    'channel.limit_premium': '⚠️ Бесплатные пользователи могут подключить только 1 канал.\n\n💎 Перейдите на Premium — до 3 каналов!',
    'channel.premium_notice': '⭐ Возможность Premium: планирование сразу в несколько каналов!',
    'channel.has_bot_replace': '⚠️ <b>У канала уже есть бот</b>\n\nК каналу <code>{channel}</code> уже подключён бот @{old_bot}.\n\nЗаменить его на @{new_bot}? Старый бот будет отключён.',
    'channel.no_message': '❌ Сообщение не получено. Отправьте ссылку на канал или его ID.',
    'channel.locked_sender': '🔴 <b>Канал управляется через бота-отправителя</b>',
    'channel.action_schedule': '📅 Отложить',
    'channel.action_stats': '📊 Статистика',
    'channel.action_recurring': '🔄 Повторяющиеся',
    'channel.action_calendar': '📅 Календарь',
    'channel.action_messages': '📋 Сообщения',
    'channel.hidden_popup': '✅ Канал скрыт от посторонних',
    'channel.visible_popup': '✅ Канал снова виден посторонним',
    'channel.hidden_done': '✅ Канал скрыт от посторонних.',
    'channel.visible_done': '✅ Канал снова виден посторонним.',
}
