# -*- coding: utf-8 -*-
"""RU batch: media section (74 strings)."""

PATCH = {
    'media.only_allowed': '❌ Здесь принимаются только медиафайлы (фото, видео, документы).',
    'media.receive_status': '✅ Медиа получено (всего: {count}). Отправьте ещё или нажмите <b>Готово</b>.',
    'media.storage': '@@STORAGE@@💾 Хранилище медиа',
    'media.storage_title': '@@STORAGE@@💾 <b>Хранилище медиа</b>\n\nСохраняйте медиафайлы и используйте их повторно в отложенных сообщениях.',
    'media.storage_empty': '@@STORAGE@@📪 В этом хранилище пока нет файлов.',
    'media.storage_full': '@@STORAGE@@⚠️ Хранилище заполнено ({count}/{limit}). Удалите часть файлов или перейдите на Premium.',
    'media.storage_limit_reached': '@@STORAGE@@⚠️ Достигнут лимит хранилища медиа ({limit}).',
    'media.limit_reached_premium': '@@STORAGE@@⚠️ <b>Достигнут лимит хранилищ медиа ({limit})</b>\n\nУдалите одно из хранилищ или добавляйте медиа в уже существующее вместо создания нового — либо напишите нашему админу (@MaximalXP) о индивидуальных повышенных лимитах.',
    'media.my_storages_btn': '@@STORAGE@@💾 Мои хранилища',
    'media.use_from_storage': '@@STORAGE@@💾 Взять из хранилища',
    'media.saved': '@@STORAGE@@✅ Медиа сохранено в хранилище.',
    'media.saved_count': '@@STORAGE@@✅ Сохранено медиафайлов: {count}.',
    'media.deleted': '@@STORAGE@@🗑 Медиафайл удалён.',
    'media.renamed': '@@STORAGE@@✅ Медиа переименовано в {name}.',
    'media.replaced': '@@STORAGE@@✅ Медиафайл заменён.',
    'media.name_prompt': '@@STORAGE@@📝 Отправьте название для этого медиафайла:',
    'media.rename_btn': '@@STORAGE@@✏️ Переименовать',
    'media.replace_btn': '@@STORAGE@@🔄 Заменить',
    'media.use_btn': '@@STORAGE@@💾 Использовать',
    'media.save_prompt': '@@STORAGE@@💾 Сохранить в хранилище медиа?\n\nЭтот файл можно сохранить для повторного использования в будущих сообщениях.',
    'media.pick_prompt': '@@STORAGE@@💾 Выберите медиа из хранилища:\n\nВыберите файл, чтобы прикрепить его к сообщению.',
    'media.rename_prompt': '@@STORAGE@@📝 Отправьте новое название для этого медиафайла:',
    'media.replace_prompt': '@@STORAGE@@❓ Заменить этот медиафайл новым?\n\nСтарый файл будет удалён.',
    'media.type_animation': '@@STORAGE@@Анимация',
    'media.type_audio': '@@STORAGE@@Аудио',
    'media.type_document': '@@STORAGE@@Документ',
    'media.type_photo': '@@STORAGE@@Фото',
    'media.type_sticker': '@@STORAGE@@Стикер',
    'media.type_video': '@@STORAGE@@Видео',
    'media.type_voice': '@@STORAGE@@Голосовое',
}
