# -*- coding: utf-8 -*-
"""RU batch: small utility strings + previously partial sections."""

PATCH = {
    # ---- back ----
    'back.btn': '🔙 Назад',
    'back.to_menu': '🔙 В меню',
    'back.main_btn': '🔙 Главное меню',
    'back.to_file_list': '📁 К файлам',
    'back.to_main': '🏠 На главную',
    'back.to_premium_menu': '◀️ В меню Premium',
    # ---- cancel ----
    'cancel.btn': '❌ Отмена',
    'cancel.premium_prompt': '📝 Почему вы отменяете подписку? (необязательно)\n\nВаш отзыв поможет нам стать лучше.',
    'cancel.premium_reason_no_longer_needed': 'Больше не нужен',
    'cancel.premium_reason_issues': 'Технические проблемы',
    'cancel.premium_reason_other': 'Другая причина',
    'cancel.premium_enter_other_reason': '📝 Опишите, почему вы отменяете подписку:',
    'cancel.premium_reason_optional_prompt': 'Причина: {reason}',
    'cancel.premium_referral_days_note': '💡 У вас есть <b>{avail}</b> неиспользованных реферальных дней Premium — отмена на них не повлияет.',
    'cancel.premium_skip_reason_button': '⏭ Пропустить',
    'cancel.button': '❌ Отмена',
    'cancel.premium_confirm_button': '✅ Да, отменить Premium',
    'cancel.premium_additional_reason': '📝 Подробности: {details}',
    'cancel.premium_confirm_text': '⚠️ Вы уверены, что хотите отменить Premium?\n\nПричина: {reason}',
    'cancel.premium_already_requested': '⏳ Отмена уже запрошена.',
    'cancel.premium_requested': '⏳ Отмена запрошена',
    'cancel.premium_requested_button': '⏳ Отмена запрошена',
    'cancel.premium_request_sent': '✅ Ваш запрос на отмену отправлен.\n\nПреимущества Premium сохранятся до конца текущего оплаченного периода.',
    'cancel.premium_request_error': '❌ Не удалось отправить запрос на отмену: {error}',
    # ---- yes / no / ok / close / clear ----
    'yes.btn': '✅ Да',
    'yes.simple': 'Да',
    'ok.btn': '✅ ОК',
    'ok.button': '✅ ОК',
    'close.btn': '❌ Закрыть',
    'close.button': '❌ Закрыть',
    'close.feedback': '❌ Закрыть',
    'close.conversation': '💬 Закрыть диалог',
    'close.complaint': '🔒 Закрыть',
    'clear.default_ch_btn': '❌ Убрать канал по умолчанию',
    # ---- copy / copied / create / confirm ----
    'copy.btn': '📋 Копировать',
    'copy.all_btn': '@@STORAGE@@Копировать всё',
    'copied': '✅ Скопировано!',
    'create.btn': '➕ Создать',
    'confirm.btn': '✅ Подтвердить',
    'confirm.button': '✅ Подтвердить',
    'confirm.cancel_button': '❌ Подтвердить отмену',
    'confirm.no': '❌ Нет',
    'confirm.yes': '✅ Да',
    'confirm.import_photos': '📷 Подтвердить {count} фото?',
    'confirm.photos': '📷 Подтверждено фото: {count}.',
    # ---- continue / choose ----
    'continue.wo_bot_btn': '➡️ Продолжить без бота',
    'continue.btn': '▶ Продолжить',
    'continue.inline_btn': '▶ Продолжить',
    'choose.plan_to_upgrade': '💳 <b>Переход на Premium</b>\n\nВыберите подходящий тариф:',
    'choose.lang': '🌐 Язык / Language',
    'choose.timezone': '🌍 Часовой пояс',
    'choose.btn': '📝 Выбрать',
    'choose.bulk_filter': '📂 Фильтр:',
    # ---- back extras ----
    'no.btn': '❌ Нет',
    'no.reason': 'Причина не указана.',
    'no.simple': 'Нет',
}
