# -*- coding: utf-8 -*-
"""RU batch: premium section part 2 (remainder)."""

PATCH = {
    'premium.grace_expired_title': '❌ <b>Льготный период истёк</b>',
    'premium.grace_expired_info': 'Ваши замороженные активы удалены — льготный период закончился.',
    'premium.grace_expired_label': 'Истекло',
    'premium.change_payment_method_btn': '💳 Сменить способ оплаты',
    'premium.change_payment_title': '💳 Смена способа оплаты',
    'premium.change_payment_info': 'Выберите другой способ оплаты для будущих продлений.',
    'premium.change_payment_instructions': 'Выберите новый способ оплаты ниже:',
    'premium.retry_payment_btn': '🔄 Повторить оплату',
    'premium.retry_exhausted_title': '❌ Попытки оплаты исчерпаны',
    'premium.retry_exhausted_info': 'Все автоматические попытки повтора оплаты использованы.',
    'premium.retry_alternatives': 'Попробуйте сменить способ оплаты или купить новую подписку.',
    'premium.retry_initiated_title': '🔄 Повтор запущен',
    'premium.retry_initiated_info': 'Попытка повтора оплаты {attempt}/{total}. Осталось попыток: {remaining}.',
    'premium.retry_what_happens': 'Telegram снова попытается списать оплату с сохранённого способа.',
    'premium.retry_status_title': '🔄 Статус повтора оплаты',
    'premium.retry_attempts_used': 'Попытки: {used}/{total}',
    'premium.retry_exhausted_short': '❌ Попыток не осталось.',
    'premium.retry_remaining_info': 'Осталось попыток: {remaining}.',
    'premium.retry_history_header': 'История попыток:',
    'premium.retry_attempt_line': 'Попытка {attempt}: {date}',
    'premium.retry_check_status_btn': '🔄 Проверить статус',
    'premium.retry_retry_now_btn': '🔄 Повторить сейчас',
    'premium.upsell_free_limit': '⭐ <b>{feature}</b>\n\nВаш текущий тариф допускает {limit}. Перейдите на Premium, чтобы поднять лимиты.\n\n<b>Преимущества Premium:</b>\n• Повышенные или безлимитные лимиты для всех функций\n• Загрузка видео для пользователей Premium\n• Полная статистика и рейтинг\n• Резервная копия и экспорт\n• Приоритетная поддержка',
    'premium.cancel_additional_reason': 'Дополнительные комментарии (необязательно):',
    'premium.activation_error_user': '❌ Не удалось активировать Premium. Напишите в поддержку.',
    'premium.activation_failed_title': '❌ Ошибка активации',
    'premium.activation_failed_footer': 'Если с вас списали оплату, напишите в поддержку с деталями платежа.',
    'premium.auto_activate_text': '⏳ После успешной оплаты Premium активируется автоматически. Подтверждение появится здесь.',
    'premium.cancel_by_date': 'Отменить до {date}',
    'premium.30days': '{days} дн.',
    'premium.lifetime': 'Навсегда',
    'premium.custom_date': 'Своя дата',
    'premium.manage_excess_prompt': 'Управляйте активами до вступления смены тарифа в силу.',
    'premium.manage_excess_btn': 'Управлять лишними активами',
    'premium.no_excess_info': 'Лишних активов не обнаружено.',
    'premium.purchase_blocked_status': 'Покупки: {status}',
    'premium.promo_prompt': '🎟 <b>Введите промокод:</b>\n\nОтправьте промокод обычным сообщением.\n\nОтправьте /cancel, чтобы прервать.',
    'premium.activated_notification': '✅ <b>Premium активирован!</b>\n\nВаша подписка Premium теперь активна.',
    'premium.payment_return_success': '✅ <b>Premium ({plan}) активирован!</b>\n\nПоздравляем и благодарим за выбор Fast Scheduler!\n\nВаш Premium ({plan}) активен до <b>{date}</b>.\n\n<b>Что открылось:</b>\n• Больше отложенных сообщений, каналов и ботов-отправителей\n• Повторяющиеся сообщения и отчёты без ограничений\n• Полная статистика и рейтинги\n• Загрузка видео большего размера и хранилище медиа\n• Приоритетная доставка и лучшее качество медиа\n\nПользуйтесь открытыми возможностями!',
    'premium.payment_return_pending': '⏳ <b>Premium пока не активен</b>\n\nВаша подписка Premium ещё ожидает подтверждения или не активирована. Подождите несколько минут и откройте ссылку снова либо проверьте <code>/premium</code>.\n\nЭта ссылка только проверяет статус аккаунта; сама она Premium не активирует.',
    'premium.canceled': '❌ Premium отменён.',
    'premium.cancelled_info': 'Premium отменён. Доступ сохранится до конца текущего периода.',
    'premium.expires': 'Истекает',
    'premium.expiring_soon': 'Ваша подписка Premium скоро закончится.',
    'premium.grace_24h_title': '⏳ <b>Льготный период</b>\n\nВаш Premium истёк менее 24 часов назад. Продлите подписку, чтобы сохранить активы.',
    'premium.granted': '✅ Premium выдан пользователю {user}.',
    'premium.limit_reached': '⚠️ Достигнут лимит Premium для {type}.',
    'premium.manual_renew_label': 'Ручное продление',
    'premium.refund_notification': '💰 Возврат для {user} обработан: {amount}',
    'premium.started': 'Начало',
    'premium.unavailable': '❌ Premium сейчас недоступен.',
    'premium.flow_unavailable': '❌ Оформление Premium временно недоступно.',
    'premium.payment_processing': '⏳ Обрабатываем оплату... Истекает: {expires}',
    'premium.auto_renew_failed_title': '⚠️ <b>Автопродление не удалось</b>',
    'premium.auto_renew_failed_info': 'Не удалось автоматически списать оплату подписки (например, недостаточно средств или устаревший способ оплаты).\n\nPremium остаётся активным до <b>{expires}</b>.',
    'premium.auto_renew_failed_warning': 'Осталось около {days} дн., чтобы поправить оплату, прежде чем лишние каналы и боты-отправители будут заморожены.',
    'premium.auto_renew_failed_final': 'Это была последняя автоматическая отсрочка. Если Premium не будет продлён, лишние каналы и боты будут заморожены, а затем отключены.',
    'premium.cancel_already_requested': '❌ Отмена уже запрошена. Premium действует до {expires}.',
    'premium.ends_in': '⏳ Premium закончится через {days} дн.',
    'premium.renew_manual_text': '🔄 Ручное продление. Истекает: {expires}',
}
