# -*- coding: utf-8 -*-
"""RU batch: unknown + signature (full sections)."""

PATCH = {
    # ---- unknown ----
    'unknown.timezone': '❌ Неизвестный часовой пояс.',
    'unknown.export_type': '❌ Неизвестный тип экспорта.',
    'unknown.file_type': '❌ Неизвестный тип файла.',
    'unknown.format': '❌ Неизвестный формат.',
    'unknown.action': '❌ Неизвестное действие: {action}',
    'unknown.command': '❌ Неизвестная команда: {cmd}',
    # ---- signature ----
    'signature.title': '📝 Подписи',
    'signature.btn': '📝 Подпись',
    'signature.menu_text': '📝 <b>Подписи</b>\n\nДобавьте строку подписи к отложенным сообщениям. Она будет автоматически добавляться в конец каждого поста.',
    'signature.prompt': '📝 Отправьте текст, который хотите использовать как подпись:',
    'signature.current': '📝 <b>Текущая подпись:</b>\n\n{signature}',
    'signature.current_none': '📝 Подпись не задана.',
    'signature.set': '✅ Подпись сохранена!\n\nОна будет появляться в конце каждого сообщения.',
    'signature.removed': '🗑 Подпись удалена.',
    'signature.too_long': '❌ Подпись слишком длинная. Максимум {max} символов.',
    'signature.confirm': '✅ Подпись: {signature}',
    'signature.remove_btn': '🗑 Удалить подпись',
    'signature.edit_btn': '✏️ Изменить подпись',
    'signature.not_allowed': '❌ Подпись недоступна для этого типа сообщения.',
    'signature.auto_label': 'Авто',
    'signature.label': '📝 Подпись',
    'signature.pos_end_label': 'В конце',
    'signature.pos_start_label': 'В начале',
    'signature.try_done_btn': '✅ Готово',
    'signature.edit_position_btn': '📍 Позиция',
    'signature.menu_title': '📝 <b>Подписи</b>',
    'signature.try_text_prompt': '📝 Отправьте текст для предпросмотра:',
    'signature.text_prompt': '📝 Отправьте текст подписи:',
    'signature.try_applied': '✅ Подпись применена к предпросмотру.',
    'signature.upsell_tried': '⭐ Пробную версию вы уже использовали. Перейдите на Premium для неограниченных подписей.',
    'signature.try_sample': '📝 Пример текста:',
    'signature.pos_start': '📝 В начале',
    'signature.saved_list_title': '📝 Сохранённые подписи',
    'signature.lines_custom_prompt': '📝 Введите количество строк:',
    'signature.lines_prompt': '📝 Сколько строк должна занимать подпись?',
    'signature.lines_invalid': '❌ Неверное число. Введите корректное количество строк.',
    'signature.auto_prompt': '⚡ Добавлять подпись автоматически ко всем сообщениям?',
    'signature.edit_title': '✏️ Изменить подпись',
    'signature.edit_detail': '📝 <b>Подпись:</b> {text}\n<b>Позиция:</b> {pos}\n<b>Строк:</b> {lines}\n<b>Авто:</b> {auto}\n\nПо умолчанию: {default}',
    'signature.saved': '✅ Подпись сохранена!',
    'signature.channel_picker_title': '📢 Выберите канал для этой подписи:',
    'signature.edit_lines_btn': '📏 Строки',
    'signature.update_posts_prompt': '🔄 Обновить существующие отложенные посты этой подписью?',
    'signature.auto_enabled': '✅ Автоподпись включена.',
    'signature.auto_added_to': '✅ Подпись добавлена к: {channels}',
    'signature.try_preview': '👁 Предпросмотр',
    'signature.deleted_ok': '🗑 Подпись удалена.',
    'signature.delete_used_by': '⚠️ Эта подпись используется в <b>{scheduled}</b> отложенных и <b>{recurring}</b> повторяющихся сообщениях.',
    'signature.try_demo_hint': '💡 Это всего лишь демо-предпросмотр.',
    'signature.upsell_try': '⭐ Попробуйте Premium, чтобы открыть пользовательские подписи',
    'signature.pos_end': '📝 В конце',
    'signature.add_btn': '➕ Добавить подпись',
    'signature.position_prompt': '📍 Где должна появляться подпись?',
    'signature.delete_confirm': '⚠️ Удалить эту подпись? Действие необратимо.',
    'signature.edit_text_btn': '✏️ Изменить текст',
    'signature.try_demo_result': '✅ Демо-предпросмотр показан выше.',
    'signature.toggle_ok': '✅ Подпись переключена.',
    'signature.edit_text_prompt': '📝 Введите новый текст подписи:',
    'signature.delete_also_remove': '🗑 Также убрать из существующих постов',
    'signature.try_btn': '👁 Попробовать предпросмотр',
    'signature.disable_auto_btn': '🔕 Отключить автодобавление',
    'signature.pos_setting_btn': '📍 Позиция',
    'signature.lines_setting_btn': '📏 Строки',
    'signature.saved_list_btn': '📝 Сохранённые подписи',
    'signature.auto_disabled': '❌ Автоподпись отключена.',
    'signature.no_saved': '\U0001FACD Сохранённых подписей нет.',
    'signature.updated': '✅ Подпись обновлена.',
    'signature.try_applied_all': '✅ Подпись будет добавлена ко всем вашим отложенным постам.',
    'signature.try_no_posts': 'Отложенных постов не найдено. Сначала запланируйте пост и попробуйте снова.',
    'signature.try_upsell': '\n\n⭐ <b>Перейдите на Premium</b>, чтобы добавлять подписи к неограниченному числу постов!',
    'signature.free_limit_notice': '\n\n📌 Подпись получила только 1 пост (бесплатный лимит). Перейдите на Premium, чтобы подписать все {count} постов.',
    'signature.none_saved': 'Сохранённых подписей пока нет. Создать?',
    'signature.save_prompt': 'Сохранить эту подпись для будущих повторяющихся сообщений?',
    'signature.delete_for_scheduled': '🗑 Удалить подпись у этого расписания',
    'signature.removed_for_scheduled': '✅ Подпись убрана у этого расписания.',
}
