# -*- coding: utf-8 -*-
"""RU batch: signature remainder, import (58), backup (49)."""

PATCH = {
    # ---- signature remainder ----
    'signature.removed_alert': '🗑 Подпись удалена.',
    # ---- import ----
    'import.btn': '📥 Импорт',
    'import.export_title': '📤 📥 Экспорт / Импорт',
    'import.export_menu_text': '📤 📥 <b>Экспорт / Импорт</b>\n\nУправление вашими данными:\n• Экспортируйте все сообщения, каналы и настройки в файл\n• Импортируйте данные из предыдущего экспорта\n• Создавайте и восстанавливайте резервные копии',
    'import.instructions': '📥 <b>Импорт данных</b>\n\nОтправьте мне JSON-файл, экспортированный из Fast Scheduler Bot.\n\n⚠️ Импорт объединит данные с текущими и перезапишет совпадающие записи.',
    'import.file_missing': '❌ Отправьте корректный JSON-файл экспорта.',
    'import.invalid_format': '❌ Неверный формат файла. Отправьте JSON-файл экспорта.',
    'import.success': '✅ Импорт прошёл успешно!\n\n• Сообщений импортировано: {messages}\n• Каналов импортировано: {channels}\n• Ботов импортировано: {bots}',
    'import.error_version': '❌ Этот экспорт создан другой версией бота. Может потребоваться обновление.',
    'import.error_generic': '❌ Ошибка импорта: {error}',
    'import.merge_options_title': '📥 Параметры импорта',
    'import.merge_keep_existing': 'Оставить существующие (пропустить дубли)',
    'import.merge_overwrite': 'Перезаписать существующие',
    'import.merge_add': 'Добавить всё (оставить дубли)',
    'import.merge_mode_chosen': '✅ Режим импорта: {mode}',
    'import.file_too_large': '❌ Файл слишком большой. Максимум: {limit} МБ.',
    'import.file_size_limit': '❌ Файл слишком большой для импорта (макс. {limit} МБ).',
    'import.file_wrong_extension': '❌ Отправьте файл .json.',
    'import.processing': '⏳ Обрабатываем импорт...',
    'import.preview': '📊 Предпросмотр:',
    'import.confirm_btn': '✅ Подтвердить импорт',
    'import.cancel_btn': '❌ Отмена',
    'import.global_error': '❌ Ошибка импорта: {error}',
    'import.link_invalid': '❌ Неверная ссылка импорта.',
    'import.no_file': '❌ Файл не получен. Отправьте файл экспорта.',
    'import.no_valid_messages': '❌ В импорте нет корректных сообщений.',
    'import.overflow_cancelled': '❌ Импорт отменён из-за превышения лимита.',
    'import.file_received': '✅ Импорт из файла <b>{filename}</b> прошёл успешно!',
    'import.photo_received': '📷 Фото получено ({n}/{total})',
    'import.prompt': '📥 Отправьте JSON-файл, экспортированный из Fast Scheduler Bot.',
    'import.select_photo_mode': '📷 <b>Выберите режим фото</b>\n\nКак прикреплять фото к отложенным постам:\n\n<b>📷 Обычный</b>\nКаждый пост получает одно и то же фото. Идеально для брендинга — логотип, водяной знак или единый визуальный стиль во всех сообщениях.\n\n<b>🎲 Случайный</b>\nКаждый пост получает случайное фото из загруженного набора. Хорошо для разнообразия — канал выглядит свежо без повторов одной картинки.\n\n<b>🔀 По порядку</b>\nФото отправляются по очереди, по одному на пост. Идеально для сторителлинга, пошаговых инструкций и любой последовательности, где порядок важен.\n\n<b>⏭ Пропустить фото</b>\nБез фото — только текстовые посты.',
    'import.send_photo_normal': '📷 Отправить отдельными постами',
    'import.send_photo_sequential': '📸 Отправить альбомом',
    'import.send_photos_random': '💭 Отправить со случайными фото',
    'import.session_expired': '⏳ Сессия импорта истекла. Начните заново.',
    'import.setdate_notes': '📝 Сообщения SetDate будут импортированы как обычные отложенные сообщения.',
    'import.storage_order_prompt': '💾 Выберите порядок импорта из хранилища:',
    'import.storage_select_box': '💾 Выберите хранилище для импорта:',
    'import.tz_change_account': '🔄 Сменить часовой пояс аккаунта',
    'import.tz_remember': '💡 Запомнить мой выбор',
    'import.tz_use_account': '📍 Использовать пояс аккаунта',
    'import.tz_use_file': '📁 Использовать пояс из файла',
    'import.use_storage_all_btn': '💾 Импортировать всё из хранилища',
    'import.with_normal_photo': '📷 С обычным фото',
    'import.with_random_photos': '📷 Со случайными фото',
    'import.without_photos': '❌ Без фото',
    'import.from_storage': '💾 Импорт из хранилища',
    'import.send_random_photos': '📷 Прикреплено случайных фото: {count}.',
    'import.tz_mismatch': '⚠️ Часовые пояса различаются: в файле — {file_tz}, в аккаунте — {user_tz}. Что использовать:',
    'import.item_normal': '📄 #{job_id} — {dt}',
    'import.overflow': '⚠️ Сообщений сверх лимита: {count}.',
    'import.overflow_first_n': '✅ Сохранены первые {n} сообщений.',
    'import.overflow_last_n': '✅ Сохранены последние {n} сообщений.',
    'import.limit_overflow': '⚠️ Превышение лимита: свободных слотов — {available}, всего — {total}, текущих — {current}, максимум — {limit}, лишних — {overflow}.',
    'import.item_base': '📄 #{job_id} — {dt}',
    'import.error': '❌ Ошибка импорта: {error}',
    'import.item_sequential': '📸 #{job_id} — {dt} (по порядку)',
    'import.item_random': '🎲 #{job_id} — {dt} (случайно)',
    'import.cancelled': 'Импорт отменён.',
    # ---- backup ----
    'backup.btn': '💾 Создать резервную копию',
    'backup.title': '💾 <b>Резервная копия</b>\n\nКопии обеспечивают безопасность ваших данных.\n• Создайте копию всех данных\n• Восстановите из предыдущей копии',
    'backup.created': '✅ Резервная копия успешно создана!',
    'backup.failed': '❌ Ошибка создания копии: {error}',
    'backup.restored': '✅ Резервная копия успешно восстановлена!',
    'backup.restore_failed': '❌ Ошибка восстановления: {error}',
    'backup.delete_confirm': '⚠️ Удалить эту резервную копию?',
    'backup.deleted': '🗑 Резервная копия удалена.',
    'backup.list_empty': '📪 Резервных копий нет.',
    'backup.list_header': '💾 <b>Ваши резервные копии</b>',
    'backup.info_size': 'Размер: {size}',
    'backup.info_date': 'Дата: {date}',
    'backup.confirm_password': '🔒 Подтвердите пароль резервной копии:',
    'backup.enter_password': '🔒 Введите пароль для защиты этой копии:',
    'backup.export_button': '📤 Экспортировать копию',
    'backup.generating': '⏳ Создаём резервную копию...',
    'backup.hint_prompt': '💡 Добавьте подсказку, которая поможет вспомнить пароль:',
    'backup.import_protected': '🔒 Эта копия защищена паролем. Введите пароль:',
    'backup.invalid_file': '❌ Неверный файл резервной копии.',
    'backup.no_data': '❌ Нет данных для копии.',
    'backup.password_mismatch': '❌ Пароли не совпадают.',
    'backup.restore_add': '➕ Добавить к существующим данным',
    'backup.restore_mode_prompt': '📂 Выберите режим восстановления:',
    'backup.restore_overwrite': '🔄 Перезаписать существующие данные',
    'backup.select_title': '💾 Выберите копию для восстановления:',
    'backup.show_hint': '💡 Показать подсказку',
    'backup.wrong_password_last': '❌ Неверный пароль. Это последняя попытка.',
    'backup.import_error': '❌ Ошибка импорта копии: {error}',
    'backup.import_success': '✅ Импорт прошёл успешно!\n• Сообщений импортировано: {messages}\n• Каналов импортировано: {channels}\n• Ботов импортировано: {bots}',
    'backup.backup_import_success': '✅ Импорт прошёл успешно!\n• Сообщений импортировано: {messages}\n• Каналов импортировано: {channels}\n• Ботов импортировано: {bots}',
    'backup.locked': '🔒 Копия заблокирована. Попробуйте через {minutes} мин {seconds} с.',
    'backup.locked_timer': '🔒 Подождите {minutes} мин {seconds} с',
    'backup.wrong_password': '❌ Неверный пароль. Осталось попыток: {attempts}.',
    'backup.export': '💾 Экспорт резервной копии',
    'backup.hint': '💡 Подсказка: {hint}',
    'backup.export_premium': '🔒 <b>Резервное копирование и экспорт — возможность Premium</b>\n\nБесплатные пользователи могут только просматривать свои данные. Чтобы экспортировать сообщения, настройки, каналы, отзывы и другие данные в файл копии, нужна подписка Premium.\n\n<b>В Premium входит:</b>\n• Полный экспорт (файл .fsback)\n• Выборочный экспорт (что включить)\n• Копии, защищённые паролем\n• Автоматические копии по расписанию\n\n💎 <b>Перейдите на Premium, чтобы открыть резервное копирование и экспорт.</b>',
    'backup.full': 'Полная копия',
    'backup.select_separately': 'Выбрать отдельно',
    'backup.ask_password': 'Защитить резервную копию паролем?',
    'backup.yes': 'Да',
    'backup.no': 'Нет',
    'backup.password_set': 'Пароль подтверждён.',
    'backup.hint_skipped': 'Подсказка не задана.',
    'backup.ready': 'Файл резервной копии готов!',
    'backup.protected': 'Создана копия, защищённая паролем.',
    'backup.unprotected': 'Создана копия без пароля.',
    'backup.contact_admin': 'Слишком много неудачных попыток. Обратитесь к администратору.',
    'backup.not_your_bot': 'Эта резервная копия создана не этим ботом.',
    'backup.eye_toggle': '👁',
}
