# -*- coding: utf-8 -*-
"""RU batch: timezone (39), complaint (38), feedback (38)."""

PATCH = {
    # ---- timezone ----
    'timezone.btn': '🕐 Часовой пояс',
    'timezone.change': 'Сменить часовой пояс',
    'timezone.prompt_method': '🕐 <b>Смена часового пояса</b>\n\nВыберите способ установки:',
    'timezone.set_city_btn': '🏙 Назвать город',
    'timezone.set_location_btn': '📍 Отправить геолокацию',
    'timezone.set_time_btn': '🕐 Отправить время',
    'timezone.city_found': '🏙 Город найден: <b>{city}</b>\nЧасовой пояс: <b>{tz}</b>\n\nВсё верно?',
    'timezone.city_not_found': '❌ Город <b>{city}</b> не найден.',
    'timezone.location_found': '📍 Местоположение определено: <b>{tz}</b>\nВсё верно?',
    'timezone.location_not_found': '❌ Не удалось определить часовой пояс по этой геолокации.',
    'timezone.time_found': '🕐 По вашему времени ({time}) ваш пояс — <b>{tz}</b>.\nВсё верно?',
    'timezone.time_not_found': '❌ Не удалось определить часовой пояс по этому времени.',
    'timezone.input_not_found': '❌ По этим данным пояс определить не удалось.\n\nПопробуйте одно из:\n• 🏙 Название <b>города</b> (например, <code>Москва</code>, <code>Лондон</code>, <code>Токио</code>)\n• 🕐 Ваше <b>текущее время</b> (например, <code>15:30</code>)\n• 📍 Вашу <b>текущую геолокацию</b>',
    'timezone.detect_confirm_btn': '✅ Верно',
    'timezone.detect_wrong_btn': '❌ Неверно — попробую снова',
    'timezone.apply_all': 'Применить ко всем каналам',
    'timezone.manage_title': '🕐 <b>Настройки часового пояса</b>\n\nТекущий пояс: <b>{tz}</b>\nДоступные действия:',
    'timezone.channel_bullet': '• {channel}: {tz}',
    'timezone.edit_for_channel': '🕐 Сменить пояс для {channel}',
    'timezone.per_channel': '📢 {channel}: {tz}',
    'timezone.per_channel_set': '✅ Часовой пояс для {channel} установлен: <b>{tz}</b>.',
    'timezone.apply_all_confirm': 'Применить часовой пояс <b>{tz}</b> ко всем вашим каналам?',
    'timezone.apply_all_done': '✅ Часовой пояс <b>{tz}</b> применён ко всем {count} каналам.',
    'timezone.apply_all_cancelled': '❌ Массовое обновление пояса отменено.',
    'timezone.no_channels': 'Каналы не подключены. Сначала подключите канал.',
    'timezone.detect_none': '❌ Часовой пояс не определён. Попробуйте ещё раз.',
    'timezone.no_channel_selected': '❌ Канал не выбран.',
    'timezone.no_tz_selected': '❌ Часовой пояс не выбран.',
    'timezone.detect_time_prompt': '🕐 Сколько сейчас времени в вашем регионе?\n\nОтправьте в формате ЧЧ:ММ (24 ч), например <code>15:30</code>.',
    'timezone.set': '✅ Часовой пояс установлен: {tz}.',
    'timezone.hint': 'Текущий пояс: {tz}',
    'timezone.select_prompt': '🌍 Выберите свой часовой пояс:',
    'timezone.detected': '🌍 Определённый пояс: {tz}',
    'timezone.auto_detect': '🔄 Автоопределение',
    'timezone.search_prompt': '🔍 Поиск часового пояса:',
    'timezone.search_no_results': '❌ По запросу «{query}» пояса не найдены.',
    'timezone.utc_offset': 'UTC{offset}',
    'timezone.command': '/timezone — Сменить свой часовой пояс',
    'timezone.change_for': '🕐 Смена часового пояса ({channel})',
    # ---- complaint ----
    'complaint.menu_title': '📮 <b>Отзывы и поддержка</b>',
    'complaint.send_prompt': '📮 <b>Отправка отзыва</b>\n\nОпишите проблему подробно. Добавьте всю информацию, которая поможет нам разобраться и решить её.\n\n📎 Можно прикрепить до <b>{max_files}</b> изображений или видео. Отправляйте каждый файл отдельно, затем добавьте текст для отправки.\n📏 Максимум <b>{file_size} МБ</b> на файл, <b>{total_size} МБ</b> всего.\n⚠️ После обработки отзыва админом медиафайлы станут недоступны в меню отзывов.',
    'complaint.category': '📂 Категория',
    'complaint.text_label': '📝 Описание',
    'complaint.status': '📌 Статус',
    'complaint.status_open': '📂 Открыт',
    'complaint.status_replied': '💬 Есть ответ',
    'complaint.status_spam': '🚫 Спам',
    'complaint.status_closed': '🔒 Закрыт',
    'complaint.created_at': '📅 Создан',
    'complaint.user': '👤 Пользователь',
    'complaint.user_language': '🌐 Язык',
    'complaint.id': '🆔 ID',
    'complaint.received': '✅ <b>Отзыв отправлен!</b>\n\nМы его получили, рассмотрим и ответим.\n\nВаш ID: <code>{feedback_id}</code>',
    'complaint.error': '❌ Ошибка при отправке отзыва: {error}',
    'complaint.not_found': '❌ Не найдено.',
    'complaint.no_text': '❌ Опишите свою проблему.',
    'complaint.no_attachments': 'Нет вложений',
    'complaint.attached_files': '📎 Вложения',
    'complaint.attached_files_present': '📎 Открыть вложения',
    'complaint.attachments_sent': '📎 Вложения отправлены.',
    'complaint.closed': '✅ Закрыто.',
    'complaint.deleted': '🗑 Удалено.',
    'complaint.marked_spam': '✅ Отмечено как спам.',
    'complaint.rate_limit': '⚠️ Отзыв можно отправлять не чаще одного раза в 30 секунд.',
    'complaint.saved_no_admin': '📮 Ваш отзыв сохранён. Администратор скоро его рассмотрит.',
    'complaint.only_media_allowed': '❌ Принимаются только изображения и видео. Отправьте фото или видео.',
    'complaint.file_too_large': '❌ Файл превышает лимит {size} МБ.',
    'complaint.total_too_large': '❌ Суммарный размер вложений превышает {size} МБ.',
    'complaint.max_media': '❌ К отзыву можно прикрепить до {count} файлов.',
    'complaint.media_collected': '📎 Медиа собрано: {current}/{max_count}. Отправьте ещё, добавьте текст или нажмите «Отправить».',
    'complaint.submit_now': '✅ Отправить отзыв',
    'complaint.submitted_title': '✅ Отзыв отправлен',
    'complaint.media_removed': '📎 Медиа удалено администратором',
    'complaint.media_note': '📎 Примечание: после обработки отзыва админом вложенные медиа станут недоступны в меню отзывов.',
    'complaint.no_media': 'Нет медиафайлов для отправки.',
    'complaint.reply_prompt': '💬 Напишите ответ. Можно также отправить изображения или видео (до 3, по 20 МБ каждый). Отправляйте файлы отдельно, затем текст для отправки.',
    'complaint.reply_sent': '✅ Ответ отправлен.',
    # ---- feedback ----
    'feedback.btn': '📮 Отзыв',
    'feedback.title': '💬 Отзыв',
    'feedback.menu': '📮 Отзыв',
    'feedback.menu_title': '💬 <b>Мои отзывы</b>',
    'feedback.send_prompt': '📝 <b>Напишите сообщение</b>\n\nПодробно опишите проблему или предложение.\n📷 Можно прикрепить <b>фото</b> или <b>видео</b> (альбомы поддерживаются). Другие типы файлов не принимаются.\n\nКогда закончите, нажмите <b>Готово</b> — или отправьте ещё сообщения, чтобы дополнить.',
    'feedback.error': '❌ Ошибка отправки отзыва.',
    'feedback.id': 'ID: {id}',
    'feedback.user': 'Пользователь: {name}',
    'feedback.user_language': 'Язык: {lang}',
    'feedback.media_note': '📷 Можно прикрепить до {max} медиафайлов.',
    'feedback.media_removed': '🗑 Медиа удалено.',
    'feedback.no_attachments': 'Нет вложений.',
    'feedback.no_media': '❌ Здесь нельзя отправлять медиафайлы.',
}
