# -*- coding: utf-8 -*-
"""RU batch: addbot, bot, feedback, setdate, user, send, autotime."""

PATCH = {
    # ---- addbot ----
    'addbot.share_selected': '✅ Ссылка для шаринга бота создана.',
    'addbot.token_request': '🔑 Отправьте мне токен бота (из @BotFather):',
    'addbot.token_prompt': '🔑 <b>Ввод токена бота</b>\n\nВставьте токен, полученный от @BotFather.\n\nОн выглядит так:\n<code>1234567890:ABCdefGHIjklmNOPqrstUVwxyz</code>',
    'addbot.remove_confirm_title': '🗑 <b>Удалить бота?</b>',
    'addbot.remove_confirm_text': 'Вы уверены, что хотите удалить <b>@{username}</b>?\n\n• Канал <b>{channel}</b> вернётся под управление главного бота\n• Все отложенные сообщения останутся на месте\n\nТого же бота можно будет подключить снова.',
    'addbot.remove_error': '❌ Не удалось удалить бота.',
    'addbot.replace_title': '🔄 <b>Замена бота</b>',
    'addbot.replace_error': '❌ Не удалось заменить бота. Токен нового бота не прошёл проверку.',
    'addbot.replace_pending_admin_check': '⏳ Токен нового бота сохранён. Убедитесь, что @{username} — админ в вашем канале, и нажмите <b>Проверить снова</b>.',
    'addbot.connected_hint': '💡 Каждый бот-отправитель ведёт один канал. Premium позволяет подключить до {limit} ботов.',
    'addbot.connected_title': '✅ Бот подключён!',
    'addbot.connected_text': '@{username} теперь управляет <b>{channel}</b>.',
    'addbot.connected_multi_title': '✅ Подключено ботов: {count}!',
    'addbot.create_button': '➕ Создать нового бота',
    'addbot.token_button': '🔑 У меня есть токен',
    'addbot.create_info': '<b>Создание бота-отправителя</b>\n\nЕсли токен уже есть, вставьте его через <b>У меня есть токен</b>.\n\nЕсли нет — используйте <b>Создать нового бота</b> ниже, затем вернитесь с токеном от @BotFather.',
    'addbot.create_success': '✅ Бот успешно создан!\n\nТеперь добавьте @{username} админом в свой канал и нажмите <b>Проверить снова</b>.',
    'addbot.create_failed': '❌ Не удалось создать бота.',
    'addbot.verified_success': '✅ Бот проверен и подключён!\n\nБот: @{username}\nТокен: <code>****{last4}</code>\n\nТеперь этим ботом можно управлять каналом.',
    'addbot.verify_error_detail': '❌ Не удалось проверить бота.\n\nВозможные причины:\n• Токен неверен (проверьте через @BotFather)\n• Бот не админ в вашем канале\n• Бот заблокирован Telegram',
    'addbot.verify_no_channel': '❌ Сначала подключите канал, чтобы я мог проверить этого бота.\n\n1. Сначала добавьте канал\n2. Добавьте @{username} админом в этот канал\n3. Выдайте как минимум право «Публикация сообщений»\n4. Нажмите <b>Проверить снова</b>',
    'addbot.instruction_text': '<b>Бот-отправитель — отдельный Telegram-бот для одного канала.</b>\n\nЭто даёт лучшую производительность, безопасность и контроль.\n\nИспользуйте <b>Создать нового бота</b>, если у вас его ещё нет, или вставьте токен через <b>У меня есть токен</b>.',
    'addbot.instruction_title': '<b>Подключение бота-отправителя</b>',
    'addbot.verify_error': '❌ Не удалось проверить бота. Убедитесь, что токен верен и бот ещё не подключён.',
    'addbot.button': '🤖 Подключить бота',
    'addbot.removed_success': '✅ Бот успешно отключён.',
    # ---- bot ----
    'bot.btn': 'бот',
    'bot.not_admin_channel': '❌ Бот не админ в этом канале.\n\nДобавьте @FastSchedulerBot админом с этими правами:\n• Публикация сообщений\n• Редактирование сообщений\n• Удаление сообщений\n• Добавление администраторов (необязательно)\n\nПосле добавления нажмите кнопку ниже для повторной проверки.',
    'bot.not_admin_yet': '💾 Токен сохранён для @{username}. ({count}/{limit})\n\nНо бот пока не админ в вашем канале.\nДобавьте @{username} администратором, затем проверьте.',
    'bot.no_post_permission': '💾 Токен получен для @{username}, но у этого бота нет права <b>Публикация сообщений</b> в вашем канале.\n\nДобавьте @{username} администратором с правом <b>Публикация сообщений</b>, затем проверьте снова.',
    'bot.connected': '✅ Бот <b>@{username}</b> подключён и привязан к <b>{channel}</b>!',
    'bot.removed': '❌ Бот <b>@{username}</b> отключён от <b>{channel}</b>.\n\nУправление возвращено главному боту.',
    'bot.already_connected': '⚠️ Этот бот (@{username}) уже подключён к другому каналу.',
    'bot.limit_reached': '⚠️ <b>Достигнут лимит ботов-отправителей ({limit})</b>\n\nУдалите одного из ботов или замените существующего вместо создания нового — либо напишите нашему админу (@MaximalXP) об индивидуальных повышенных лимитах.',
    'bot.assigned_check': '✅',
    'bot.unassigned_check': '⬜',
    'bot.back_online': '✅ Бот @{username} снова в сети и управляет {channel}.',
    'bot.benefits_title': 'Зачем подключать бота-отправителя?',
    'bot.benefits_detailed': '• Ваш канал выглядит управляемым вашим собственным ботом\n• Полная поддержка инлайн-клавиатур\n• Быстрая публикация на выделенных ресурсах\n• Посторонние видят «@{bot}» вместо главного бота\n• Скрытые каналы остаются по-настоящему приватными\n• Premium позволяет подключить несколько ботов',
    'bot.blocked': '❌ Бот был заблокирован пользователем.',
    'bot.kicked': '❌ Бот был удалён из группы/канала.',
    'bot.list_item': '🤖 {username}',
    'bot.hide_channel_btn_hide': '🔒 Скрыть канал от посторонних',
    'bot.hide_channel_btn_show': '🔓 Показать канал посторонним',
    'bot.not_admin': '❌ Бот должен быть администратором канала.',
    'bot.no_channel': '❌ Нет канала',
    'bot.channel_connected': '✅ <b>Бот подключён к каналу</b>\n\nБот @{bot} теперь привязан к <code>{channel}</code>.',
    'bot.channel_connected_user': '✅ <b>Бот подключён</b>\n\n@{bot} → <code>{channel}</code>.',
    'bot.change_icon': '🔄',
    'bot.remove_icon': '🗑',
    'bot.hide_info': '💡 <b>Скрыть/показать канал:</b> когда канал скрыт, посторонние, запустившие вашего подключённого бота, не увидят его название. Бот просто скажет, что публикует сообщения «в канал», не раскрывая какой.\n<i>(Касается только приветствия подключённого бота — в вашей панели управления Fast Scheduler канал виден всегда.)</i>',
    'bot.sender_bot_online': '👋 Я в сети и подключён к вашему каналу!\n\nЯ @{username} — ваш персональный бот-отправитель. Посты в ваш канал доставляются через меня, и я сообщу здесь, если что-то потребует вашего внимания.',
    # ---- feedback ----
    'feedback.no_text': '❌ В отзыве должен быть текст.',
    'feedback.not_found': '❌ Отзыв не найден.',
    'feedback.only_media_allowed': '📷 Принимаются только медиафайлы (фото/видео).',
    'feedback.reply_prompt': '📩 Напишите ответ:',
    'feedback.reply_sent': '✅ Ответ отправлен.',
    'feedback.saved_no_admin': '✅ Отзыв сохранён. Сейчас нет администратора для рассмотрения.',
    'feedback.status': 'Статус: {status}',
    'feedback.status_open': '📬 Открыт',
    'feedback.status_replied': '✅ Есть ответ',
    'feedback.status_spam': '🚫 Спам',
    'feedback.status_closed': 'Закрыт',
    'feedback.submitted_title': '✅ <b>Отзыв отправлен</b>',
    'feedback.text_label': 'Текст: {text}',
    'feedback.rate_limit': '⏳ Подождите {seconds} с перед отправкой следующего отзыва.',
    'feedback.total_too_large': '❌ Суммарный размер слишком велик ({size}).',
    'feedback.file_too_large': '❌ Файл слишком большой ({size}).',
    'feedback.media_collected': '📷 Медиа: {current}/{max_count}',
    'feedback.max_media': '📷 Максимум {count} медиафайлов.',
    'feedback.attached_files_present': '📎 Прикреплено файлов: {count}.',
    'feedback.received': '📩 Отзыв #{feedback_id} получен.',
    'feedback.attachments_sent': '✅ Вложения отправлены.',
    'feedback.category': 'Категория: {cat}',
    'feedback.created_at': 'Создан: {date}',
    'feedback.attached_files': 'Вложений: {count}',
    'feedback.submit_now': '✅ Отправить сейчас',
    # ---- setdate ----
    'setdate.promo': '📢 <b>Спецреклама: бот SetDate</b>\n\nНужно запланировать десятки постов за секунды? Попробуйте <b>SetDate Bot</b> — наш рекомендуемый инструмент для массового планирования.\n\n<b>Как это работает:</b>\n1. Задайте начальную дату\n2. Выберите количество постов в день и время\n3. Напишите посты (или загрузите .txt-файл)\n4. Получите готовое расписание с датами\n5. Импортируйте его сюда одним нажатием\n\n• Импорт в Fast Scheduler в один клик — выберите медиа и вперёд\n• Работает с любым количеством постов — при создании лимитов нет\n\n👇 Нажмите кнопку ниже, чтобы открыть SetDate Bot:',
    'setdate.import_ready': '📥 <b>Сообщения импортированы из SetDate!</b>\n\nРасписание получено. Сообщения готовы к планированию.\n\nВыберите, добавлять ли медиа:',
    'setdate.cancel_btn': '❌ Отмена',
    'setdate.dont_show_btn': '🚫 Скрыть рекламу',
    'setdate.promo_hidden': '✅ Реклама скрыта. Включить её снова можно в любой момент из меню настроек.',
    'setdate.promo_premium_only': '⭐ Premium скрывает рекламу и открывает больше возможностей!',
    'setdate.promo_premium_body': '⭐ <b>Возможность Premium: без рекламы</b>\n\nСкрытие рекламных сообщений — возможность Premium. Перейдите на Premium и наслаждайтесь без рекламы!\n\n<b>✨ Преимущества Premium:</b>\n• 🚫 Скрытие всех рекламных сообщений\n• 📅 Планирование без лимитов\n• 🔄 Несколько повторяющихся постов\n• 📊 Подробная статистика\n• 💾 Больше хранилищ медиа\n• 🤖 Несколько ботов-отправителей',
    'setdate.promo_on': '✅ Реклама SetDate включена.',
    'setdate.promo_off': '🔕 Скрыть рекламу',
    'setdate.promo_toggled_on': '✅ Реклама теперь будет показываться при планировании.',
    'setdate.promo_toggled_off': '🔕 Реклама теперь скрыта.',
    'setdate.hide_ad_premium_btn': '🚫 Скрыть рекламу',
    'setdate.hide_ad_premium_body': '⭐ <b>Возможность Premium: без рекламы</b>\n\nСкрытие рекламных сообщений — возможность Premium. Перейдите на Premium и наслаждайтесь без рекламы!\n\n<b>✨ Преимущества Premium:</b>\n• 🚫 Скрытие всех рекламных сообщений\n• 📅 Планирование без лимитов\n• 🔄 Несколько повторяющихся постов\n• 📊 Подробная статистика\n• 💾 Больше хранилищ медиа\n• 🤖 Несколько ботов-отправителей',
    'setdate.promo_disabled_btn': '🔕 Включить рекламу SetDate',
    'setdate.enable_confirm': 'Включить рекламу SetDate? Она будет показываться при планировании.',
    'setdate.enable_yes': '✅ Да, включить',
    'setdate.enable_no': '❌ Нет, оставить выключенной',
    'setdate.promo_enabled': '✅ Реклама SetDate включена. Она будет показываться при планировании.',
    'setdate.promo_disabled': '🔕 Реклама SetDate отключена.',
    'setdate.promo_enabled_btn': '✅ Реклама SetDate включена',
    'setdate.disable_confirm': 'Отключить рекламу SetDate? Она больше не будет показываться при планировании.',
    'setdate.disable_yes': '✅ Да, отключить',
    'setdate.disable_no': '❌ Нет, оставить включённой',
    # ---- user ----
    'user.not_admin_channel': '❌ Похоже, вы не админ этого канала.',
    'user.not_found': '❌ Пользователь не найден.',
    'user.deactivated': '❌ Аккаунт пользователя деактивирован.',
    'user.access_level': 'Доступ: {level}',
    'user.blocked': '❌ Заблокирован',
    'user.channel': 'Канал: {name}',
    'user.created': 'Создан: {date}',
    'user.id': 'ID: {id}',
    'user.info_title': '👤 <b>О пользователе</b>',
    'user.language': 'Язык: {lang}',
    'user.name': 'Имя: {name}',
    'user.premium': 'Premium: {status}',
    'user.premium_revoked_alert': '⚠️ Premium отозван у {user}.',
    'user.recurring': 'Повторяющихся: {count}',
    'user.scheduled': 'Отложено: {count}',
    'user.sent_total': 'Отправлено: {count}',
    'user.username': 'Юзернейм: @{name}',
    'user.blocked_msg': '🚫 {reason}',
    'user.not_admin': '❌ Чтобы подключить канал, вы должны быть его админом или создателем.',
    'user.subscribed': '✅ Подписан',
    'user.unblocked_alert': '✅ Вы разблокированы и снова можете пользоваться ботом.',
    'user.premium_granted_alert': '🎉 <b>Premium активирован!</b>\n\nТеперь вам доступны все премиум-возможности!',
    'user.blocked_alert': 'Вы заблокированы администратором.',
    # ---- send ----
    'send.media_replace_prompt': '@@STORAGE@@❓ Заменить существующее медиа или оставить?',
    'send.new_media_option': '@@STORAGE@@📷 Отправить новое медиа',
    'send.new_media_prompt': '@@STORAGE@@❓ Отправить новое изображение или выбрать из хранилища?',
    'send.btn': '📤 Отправить',
    'send.json_csv': '📥 Отправить как JSON/CSV',
    'send.photo_please': '📷 Пожалуйста, отправьте фото.',
    'send.photos_prompt': '📷 Отправьте фото или нажмите «Готово»:',
    'send.error_both_failed': '❌ Обе попытки отправки не удались для канала {channel_id}:\n{error}\n{error2}',
    'send.success_channel': 'Сообщение отправлено в {channel}. <a href="{link}">Смотреть</a>',
    'send.success_channel_no_link': 'Сообщение отправлено в {channel} (сообщение #{sent_id}).',
    'send.sequential_prompt': '📤 Отправьте {count} медиафайлов по порядку:',
    'send.error_unexpected': '❌ Неожиданная ошибка при отправке в {channel_id}: {error} (задание #{job_id})',
    'send.now_btn': '✅ Отправить сейчас',
    'send.error_bot_not_admin': 'Бот не админ канала {channel_id} или у него нет права «Отправка сообщений».\n\nПроверьте настройки админов канала и попробуйте снова.\n\nОшибка: {error}',
    'send.error_bot_blocked': 'Бот заблокирован или удалён из канала {channel_id}.\n\nВерните бота админом.\n\nОшибка: {error}',
    'send.error_token_invalid': 'Токен доступа вашего бота-отправителя неверен или отозван.\n\nВыполните /bots, чтобы проверить подключённых ботов.',
    'send.error_channel_not_found': 'Канал {channel_id} не найден или недоступен.\n\nВозможно, канал удалён или бота убрали из админов.\n\nПроверьте свои каналы через /channel.',
    'send.error_main_bot_failed': 'Сообщение не удалось отправить в канал {channel_id} через {bot}.\n\nПричина: {error}\n\nУбедитесь, что бот — админ канала с правом «Отправка сообщений».',
    'send.error_poll_non_anonymous': 'Неанонимные опросы нельзя отправлять в каналы.\n\nОпросы для каналов должны быть в <b>анонимном</b> режиме (по умолчанию в Telegram).\n\nСоздайте новый опрос в анонимном режиме и попробуйте снова.',
    'send.error_no_channel': 'Канал отложенного сообщения #{job_id} больше не существует или удалён.',
    # ---- autotime ----
    'autotime.title': '🕐 AutoTime',
    'autotime.btn': '🕐 AutoTime',
    'autotime.menu_text': '🕐 <b>AutoTime</b>\n\nАвтоматически определяет лучшее время публикации по активности аудитории канала.',
    'autotime.channel_prompt': '📢 Выберите канал для анализа:',
    'autotime.analyzing': '⏳ Анализируем активность канала... Это займёт немного времени.',
    'autotime.result': '🕐 <b>Лучшее время публикации для {channel}</b>\n\nРекомендуемое время: {time}\n\nПо {samples} недавним постам ваша аудитория наиболее активна именно в это время.',
    'autotime.no_data': '❌ Данных для определения лучшего времени недостаточно. Публикуйте больше сообщений и попробуйте снова.',
    'autotime.apply_btn': '✅ Применить это время',
    'autotime.applied': '✅ AutoTime установлен на {time} для {channel}.',
    'autotime.analysis_failed': '❌ Не удалось проанализировать активность канала.',
    'autotime.analyze_btn': '🕐 Анализировать',
    'autotime.insufficient_posts': '❌ Для анализа нужно минимум {min} постов. Сейчас: {current}.',
    'autotime.cancel_btn': '❌ Отменить AutoTime',
    'autotime.dont_show_btn': '🚫 Больше не показывать',
    'autotime.promo': '⏳ AutoTime предложит лучшее время публикации по активности вашего канала.',
    'autotime.promo_hidden': '❌ Реклама AutoTime скрыта.',
    'autotime.promo_on': '✅ Реклама AutoTime включена.',
    'autotime.promo_premium_body': '⭐ AutoTime предложит лучшее время публикации по активности вашей аудитории.',
    'autotime.promo_toggled_on': '✅ Реклама AutoTime теперь видна.',
}
