# -*- coding: utf-8 -*-
"""RU batch: premium section part 1."""

PATCH = {
    'premium.status': '⭐ Premium: {status}',
    'premium.badge': '⭐',
    'premium.unsupported_title': '⚠️ <b>Этот контент пока нельзя отправить:</b>',
    'premium.sticker_warning': '⚠️ Премиум-стикеры нельзя отправить — их могут отправлять только аккаунты с Telegram Premium, а бот Premium не бывает.',
    'premium.rich_warning': '⚠️ Богато отформатированные статьи пока нельзя отправить — для этого у владельца бота должен быть Telegram Premium. Сообщение уйдёт как обычный текст.',
    'premium.plans_comparison_btn': '📊 Сравнить тарифы',
    'premium.status_frozen': '🧊 Заморожено',
    'premium.status_text': '⭐ Premium',
    'premium.menu_text': '<b>Подписка Premium</b>\n\n<b>Ваш тариф:</b> {plan}\n\n📦 <b>БЕСПЛАТНЫЙ ТАРИФ</b>\n\n• Повторяющиеся: {recurring_free} (завершаются через год)\n\n• Каналы: {channels_free}\n\n• Боты: {bots_free}\n\n• Статистика: только средние (полная — в Premium)\n\n• Видео в отложенных сообщениях: {videos_msg_free}\n\n• Видео в хранилище: {videos_storage_free}\n\n• Всего файлов в хранилищах: {media_items_free}\n\n• Медиа в 4K: {allow_4k_free}\n\n• Приоритет рассылок: обычный\n\n• Сжатие: {compression_free}\n\n• Рейтинг: нет\n\n• Автоотчёты: до 3 расписаний\n\n👑 <b>ТАРИФ PREMIUM</b>\n\n• Повторяющиеся: {recurring_prem}\n\n• Каналы: {channels_prem}\n\n• Боты: {bots_prem}\n\n• Статистика: отчёты без ограничений, рейтинг, полные данные по каждому посту\n\n• Видео в отложенных сообщениях: {videos_msg_prem}\n\n• Видео в хранилище: {videos_storage_prem}\n\n• Всего файлов в хранилищах: {media_items_prem}\n\n• Медиа в 4K: {allow_4k_prem}\n\n• Приоритет рассылок: приоритетный\n\n• Сжатие: {compression_prem}\n\n• Рейтинг: да\n\n• Автоотчёты: без ограничений',
    'premium.menu_title': '💎 <b>Premium</b>',
    'premium.value_intro': 'Проводите меньше времени на управление каналом. Готовьте контент на недели вперёд, держите медиа под рукой, а надёжную доставку доверьте Fast Scheduler — и занимайтесь ростом аудитории.',
    'premium.menu_stats_premium': ' 📊 Статистика: отчёты без ограничений, рейтинг, полные данные по постам',
    'premium.menu_stats_free': ' 📊 Статистика: только средние (полная — в Premium)',
    'premium.menu_leaderboard_premium': ' 🏆 Рейтинг: сортировка по реакциям, периоды, топ-100, свои фильтры',
    'premium.menu_leaderboard_free': ' 🏆 Рейтинг: только в Premium',
    'premium.menu_senderbot_premium': ' 🤖 Управление ботами-отправителями: все возможности',
    'premium.menu_senderbot_free': ' 🤖 Управление ботами-отправителями: ограничено (полное — в Premium)',
    'premium.menu_autoreports_premium': ' 📊 Автоотчёты: без ограничений',
    'premium.menu_autoreports_free': ' 📊 Автоотчёты: до 3 расписаний',
    'premium.features_btn': '⭐ Возможности Premium',
    'premium.activated_lifetime': '✅ <b>Premium активирован!</b>\n\nВаш Premium теперь активен <b>навсегда</b>.',
    'premium.activated_date': '✅ <b>Premium активирован!</b>\n\nВаш Premium ({plan}) активен до {date}.',
    'premium.status_line_free': 'Вы на <b>бесплатном</b> тарифе.',
    'premium.status_line_paid': '✅ <b>Premium активен</b>\n\n{expires}\nАвтопродление: {autorenew}',
    'premium.status_line_paid_cancelled': '✅ <b>Premium активен</b>\n\nИстекает: {expires} (автопродление отменено)',
    'premium.next_renewal': 'Следующее продление',
    'premium.status_details': '⭐ <b>Статус Premium</b>\n\nТариф: {plan}\nСтатус: {status}\nНачало: {started}\nИстекает: {expires}\nАвтопродление: {autorenew}',
    'premium.not_active': '❌ Premium на вашем аккаунте не активен.',
    'premium.expiration_unknown': 'Неизвестно',
    'premium.start_unknown': 'Неизвестно',
    'premium.required': '⭐ <b>Возможность Premium</b>\n\nДля этой функции нужна активная подписка Premium.\n\nС Premium открываются:\n• Повышенные лимиты сообщений, каналов и ботов\n• Загрузка видео\n• Полная статистика и рейтинги\n• Резервное копирование и экспорт\n• Приоритетная поддержка',
    'premium.comparison_rich': '📊 <b>Сравнение тарифов</b>\n\n| Возможность | Free | Premium |\n|---------|:----:|:-------:|\n| Повторяющиеся сообщения | {recurring_free} | {recurring_prem} |\n@@STORAGE@@| Хранилища медиа | {media_storages_free} | {media_storages_prem} |\n| Подключённые каналы | {channels_free} | {channels_prem} |\n| Боты-отправители | {bots_free} | {bots_prem} |\n| Загрузка видео | {videos_msg_free} | {videos_msg_prem} |\n| Макс. размер медиа | {max_media_free} | {max_media_prem} |\n| Медиа 4K | {free_allow_4k} | {premium_allow_4k} |\n| Статистика | базовая | расширенная |\n| Поиск | есть | есть |\n| Календарь | есть | есть |\n| Резервная копия и экспорт | — | ✓ |\n| Рейтинг | — | ✓ |\n| Отчёты | {reports_free} | {reports_prem} |',
    'premium.comparison_free': '📊 <b>Бесплатный тариф</b>\n\n• {monthly_sent_free} отправленных сообщений на канал в месяц\n• До {scheduled_free} ожидающих отложенных сообщений\n• До {recurring_free} повторяющихся сообщений\n• До {channels_free} канала\n• До {bots_free} бота-отправителя\n• Медиа до {max_media_free}\n@@STORAGE@@• Хранилища медиа: {media_storages_free}\n• Видео: {videos_msg_free}\n• Статистика: да\n• Поиск: да\n• Резервная копия и экспорт: нет',
    'premium.comparison_paid': '📊 <b>Тариф Premium</b>\n\n• Отправка сообщений без ограничений\n• Отложенные сообщения без ограничений\n• До {recurring_prem} повторяющихся сообщений\n• До {channels_prem} каналов\n• До {bots_prem} ботов-отправителей\n• Медиа до {max_media_prem}\n@@STORAGE@@• Хранилища медиа: {media_storages_prem}\n• Видео: {videos_msg_prem}\n• Полная статистика + рейтинг\n• Резервная копия и экспорт\n• Отчёты без ограничений\n• Приоритетная поддержка',
    'premium.comparison_text': '📊 <b>Сравнение тарифов</b>\n\nЧто даёт Premium:',
    'premium.payment_choice_text': '⭐ <b>Выберите срок Premium</b>\n\nВсе платежи Premium — через Telegram Stars:',
    'premium.plan_monthly_3': '3 месяца предоплатой',
    'premium.plan_monthly_6': '6 месяцев предоплатой',
    'premium.monthly_subscription_explainer': '✅ <b>Стандартная месячная подписка:</b> оплачивается через Telegram Stars, затем Telegram продлевает её каждые 30 дней, пока вы не отмените. После отмены Premium действует до конца оплаченного периода.',
    'premium.multi_month_payment_explainer': '✅ <b>Сейчас вы оплачиваете все {months} мес. сразу.</b> Этот срок не продлевается автоматически. По окончании Premium не продолжится; цена месяца для сравнения — {monthly_price}. Когда захотите продолжить, выберите новый план.',
    'premium.yearly_one_time_explainer': 'ℹ️ <b>Годовой план — разовая покупка Stars.</b> Через год Premium завершится, если вы не выберете и не оплатите новый план.',
    'premium.monthly_standard_option': '⭐ Стандартная месячная подписка — {price}/мес',
    'premium.monthly_three_option': '3️⃣ 3 месяца — {price} (экономия {full_price})',
    'premium.monthly_six_option': '6️⃣ 6 месяцев — {price} (экономия {full_price})',
    'premium.monthly_pay_monthly_note': '💡 При помесячной оплате: 3 месяца = {three_month_total}, 6 месяцев = {six_month_total}',
    'premium.multi_month_discount_note': '🏷️ <b>Скидка при предоплате: {percent}%</b> — вы платите {discounted} вместо {price}.',
    'premium.payment_options_text': '💳 Доступные способы оплаты:',
    'premium.price_line': '💰 {price}',
    'premium.stars_only_payment_notice': '⭐ Оплата Premium доступна только через Telegram Stars.',
    'premium.cancel_provider_failed': '❌ Telegram не смог подтвердить отмену. Premium остаётся активным; попробуйте ещё раз до следующего продления.',
    'premium.premium_cancel_provider_failed': '❌ Telegram не смог подтвердить отмену. Premium остаётся активным; попробуйте ещё раз до следующего продления.',
    'premium.purchase_blocked_notice': '❌ Покупка Premium сейчас отключена. Попробуйте позже или напишите в поддержку.',
    'premium.payment_success': '✅ <b>Оплата прошла успешно!</b>\n\nДоступ Premium активирован. В меню Premium видно, продлевается ли этот план автоматически. Стандартный месячный продлевается каждые 30 дней; предоплаченные 3/6 месяцев и годовой — разовые покупки.\n\nДобро пожаловать в Premium!',
    'premium.cancel': '❌ Отменить Premium',
    'premium.cancel_requested_button': '❌ Отмена запрошена',
    'premium.already_cancelled_info': '❌ Отмена уже в процессе.\n\nНачало: {started}\nИстекает: {expires}\nОтмена до: {cancel_by}',
    'premium.cancel_request_error': '❌ Не удалось обработать отмену.',
    'premium.cancel_request_sent': '✅ Запрос на отмену отправлен!\n\nPremium останется активным до <b>{expires}</b>.',
    'premium.cancel_requested': '❌ Отмена запрошена. Premium действует до {expires}.',
    'premium.cancel_confirm_button': '✅ Да, отменить Premium',
    'premium.cancel_confirm_text': '⚠️ Вы уверены, что хотите отменить Premium?\n\nПосле окончания текущего периода доступ к функциям Premium будет закрыт.',
    'premium.invoice_description': 'Подписка Fast Scheduler Bot Premium',
    'premium.auto_renew_on': 'Автопродление включено',
    'premium.auto_renew_off': 'Автопродление выключено',
    'premium.reenable_auto_renew_btn': '✅ Включить автопродление',
    'premium.turn_off_auto_renew_btn': '❌ Выключить автопродление',
    'premium.auto_renew_benefits': '✅ Автопродление держит ваш Premium активным без перерывов.',
    'premium.keep_premium_text': 'Сохраните Premium и управляйте лишними активами ниже.',
    'premium.excess_summary_header': '⚠️ <b>Обнаружены лишние активы</b>\n\nКогда Premium закончится, активов станет больше, чем допускает бесплатный тариф.',
    'premium.excess_channels_detail': '📢 Каналы: {current} (лимит: {limit}, отложено: {scheduled})',
    'premium.excess_bots_detail': '🤖 Боты: {current} (лимит: {limit})',
    'premium.excess_recurring_detail': '🔄 Повторяющиеся: {current}',
    'premium.excess_consequences': '⚠️ Лишние активы будут заморожены (не удалены). Их можно восстановить, снова включив Premium.',
    'premium.backup_recommendation': '📤 <b>Рекомендация:</b> экспортируйте данные до окончания Premium.',
    'premium.step_header': '⭐ <b>Управление активами перед понижением</b>\n\nНачало: {started}\nИстекает: {expires}',
    'premium.manage_channels_btn': '📢 Управление каналами',
    'premium.manage_bots_btn': '🤖 Управление ботами',
    'premium.manage_recurring_btn': '🔄 Управление повторяющимися',
    'premium.manage_complete_text': '✅ Все лишние активы обработаны. Всё готово!',
    'premium.select_keep_channel': '📢 Оставить {channel}',
    'premium.select_keep_bot': '🤖 Оставить @{bot}',
    'premium.select_keep_recurring': '🔄 Оставить сообщение #{id}',
    'premium.save_selection': '✅ Сохранить выбор',
    'premium.select_max_limit': '⚠️ Можно выбрать до {limit} шт.',
    'premium.select_at_least_one': '❌ Выберите хотя бы один пункт.',
    'premium.selection_saved': '✅ Выбор сохранён.',
    'premium.give_up_btn': '❌ Отказаться и понизить тариф',
    'premium.give_up_title': '❌ <b>Отказ от премиум-активов</b>',
    'premium.give_up_warning': '⚠️ Вы собираетесь отказаться от активов сверх лимитов бесплатного тарифа.',
    'premium.give_up_assets_header': 'Активы к отказу:',
    'premium.give_up_consequences': '❌ Эти активы будут удалены навсегда. Это необратимо!',
    'premium.give_up_irreversible': '🚫 Это действие необратимо.',
    'premium.give_up_confirm_btn': '✅ Да, отказываюсь',
    'premium.give_up_done_title': '✅ Понижение завершено',
    'premium.give_up_done_info': 'Ваш аккаунт переведён на бесплатный тариф.',
    'premium.give_up_done_channels': '🗑 Отказано от каналов: {count}',
    'premium.give_up_done_bots': '🗑 Отказано от ботов: {count}',
    'premium.not_frozen': '❌ Замороженных активов нет.',
    'premium.unfreeze_info_title': '🧊 <b>Замороженные активы</b>',
    'premium.unfreeze_info_grace': 'Льготный период до: {date}',
    'premium.unfreeze_info_assets': 'Замороженные активы:',
    'premium.unfreeze_info_restore': 'Снова включите Premium, чтобы восстановить эти активы.',
    'premium.unfreeze_celebration_title': '✅ <b>С возвращением в Premium!</b>',
    'premium.unfreeze_celebration_footer': 'Все ваши активы восстановлены.',
    'premium.unfreeze_asset_channels': '📢 Восстановлено замороженных каналов: {count}',
    'premium.unfreeze_asset_bots': '🤖 Восстановлено замороженных ботов: {count}',
    'premium.unfreeze_asset_recurring': '🔄 Восстановлено замороженных повторяющихся сообщений: {count}',
    'premium.frozen_notification_title': '🧊 <b>Premium истёк — активы заморожены</b>',
    'premium.frozen_grace_info': 'Ваша подписка Premium истекла. До {date} можно продлить подписку, пока замороженные активы не будут удалены.',
    'premium.frozen_next_steps': 'Снова включите Premium, чтобы мгновенно вернуть всё.',
}
