# -*- coding: utf-8 -*-
"""RU batch: signature remainder, referral (40), search (39)."""

PATCH = {
    # ---- signature remainder ----
    'signature.remove_btn': '🗑 Убрать подпись',
    'signature.edit_btn': '✏️ Изменить подпись',
    'signature.not_allowed': '❌ Подпись недоступна для этого типа сообщения.',
    'signature.auto_label': 'Авто',
    'signature.label': '📝 Подпись',
    'signature.pos_end_label': 'В конце',
    'signature.pos_start_label': 'В начале',
    'signature.try_done_btn': '✅ Готово',
    'signature.edit_position_btn': '📍 Позиция',
    'signature.menu_title': '📝 <b>Подписи</b>',
    'signature.try_text_prompt': '📝 Отправьте текст для предпросмотра:',
    'signature.text_prompt': '📝 Отправьте текст подписи:',
    'signature.try_applied': '✅ Подпись применена к предпросмотру.',
    'signature.upsell_tried': '⭐ Вы уже использовали пробный период. Premium открывает подписи без ограничений.',
    'signature.try_sample': '📝 Пример текста:',
    'signature.pos_start': '📝 В начале',
    'signature.saved_list_title': '📝 Сохранённые подписи',
    'signature.lines_custom_prompt': '📝 Введите количество строк:',
    'signature.lines_prompt': '📝 Сколько строк должна занимать подпись?',
    'signature.lines_invalid': '❌ Неверное число. Введите корректное количество строк.',
    'signature.auto_prompt': '⚡ Добавлять подпись автоматически во все сообщения?',
    'signature.edit_title': '✏️ Изменение подписи',
    'signature.edit_detail': '📝 <b>Подпись:</b> {text}\n<b>Позиция:</b> {pos}\n<b>Строк:</b> {lines}\n<b>Авто:</b> {auto}\n\nПо умолчанию: {default}',
    'signature.saved': '✅ Подпись сохранена!',
    'signature.channel_picker_title': '📢 Выберите канал для этой подписи:',
    'signature.edit_lines_btn': '📏 Строки',
    'signature.update_posts_prompt': '🔄 Обновить существующие отложенные посты этой подписью?',
    'signature.auto_enabled': '✅ Автоподпись включена.',
    'signature.auto_added_to': '✅ Подпись добавлена к: {channels}',
    'signature.try_preview': '👁 Предпросмотр',
    'signature.deleted_ok': '🗑 Подпись удалена.',
    'signature.delete_used_by': '⚠️ Эта подпись используется в <b>{scheduled}</b> отложенных и <b>{recurring}</b> повторяющихся сообщениях.',
    'signature.try_demo_hint': '💡 Это просто демо-предпросмотр.',
    'signature.upsell_try': '⭐ Попробуйте Premium, чтобы открыть свои подписи',
    'signature.pos_end': '📝 В конце',
    'signature.add_btn': '➕ Добавить подпись',
    'signature.position_prompt': '📍 Где должна появляться подпись?',
    'signature.delete_confirm': '⚠️ Удалить эту подпись? Действие необратимо.',
    'signature.edit_text_btn': '✏️ Изменить текст',
    'signature.try_demo_result': '✅ Демо-предпросмотр показан выше.',
    'signature.toggle_ok': '✅ Статус подписи изменён.',
    'signature.edit_text_prompt': '📝 Введите новый текст подписи:',
    'signature.delete_also_remove': '🗑 Также убрать из существующих постов',
    'signature.try_btn': '👁 Попробовать предпросмотр',
    'signature.disable_auto_btn': '🔕 Отключить автодобавление',
    'signature.pos_setting_btn': '📍 Позиция',
    'signature.lines_setting_btn': '📏 Строки',
    'signature.saved_list_btn': '📝 Сохранённые подписи',
    'signature.auto_disabled': '❌ Автоподпись отключена.',
    'signature.no_saved': '📪 Сохранённых подписей нет.',
    'signature.updated': '✅ Подпись обновлена.',
    'signature.try_applied_all': '✅ Подпись будет добавлена ко всем вашим отложенным постам.',
    'signature.try_no_posts': 'Отложенных постов нет. Сначала запланируйте пост и попробуйте снова.',
    'signature.try_upsell': '\n\n⭐ <b>Перейдите на Premium</b>, чтобы добавлять подписи без ограничений!',
    'signature.free_limit_notice': '\n\n📌 Подпись добавлена только к 1 посту (бесплатный лимит). Premium подпишет все {count} постов.',
    'signature.none_saved': 'Сохранённых подписей пока нет. Создать?',
    'signature.save_prompt': 'Сохранить эту подпись для будущих повторяющихся сообщений?',
    'signature.delete_for_scheduled': '🗑 Удалить подпись у этой записи',
    'signature.removed_for_scheduled': '✅ Подпись удалена у этой записи.',
    # ---- referral ----
    'referral.program': '🎁 Реферальная программа',
    'referral.info_text': '🎁 <b>Реферальная программа</b>\n\nВаша ссылка:\n{ref_link}\n\n• Приглашено: {ref_count}\n• Максимум рефералов: {referral_max}\n• Заработано дней: {total_days}\n• Использовано дней: {used_days}\n• Доступно дней: {avail_days}\n\n{referral_requirement_note}',
    'referral.promo_text': '🎁 <b>Получите дни Premium бесплатно!</b>\n\nИспользуйте мою реферальную ссылку — мы оба получим бесплатные дни Premium:\n{link}\n\nПодключайтесь к Fast Scheduler Bot и планируйте свои посты!',
    'referral.join_count_collapsed': '👥 Приглашено: {count}',
    'referral.join_count_format': '👥 {count}',
    'referral.send_link': '🔗 Отправить ссылку',
    'referral.requirement_note': '✅ Чтобы реферал засчитался, приглашённый должен запланировать хотя бы одно сообщение.',
    'referral.premium_activated_text': '✅ Активировано {avail} дн. Premium с вашего реферального баланса!',
    'referral.premium_active_note': '💡 Ваш реферальный Premium (<b>{avail}</b> дн.) остаётся активным, и отмена на него не влияет.',
    'referral.days_unused_note': '💡 У вас всё ещё <b>{avail}</b> неиспользованных реферальных дней Premium. Активируйте их в меню Premium!',
    'referral.activate_failed': '❌ Не удалось активировать реферальные дни.',
    'referral.info': '🎁 О программе',
    'referral.copy_link': '🔗 Копировать ссылку',
    'referral.link_invalid': '❌ Неверная реферальная ссылка.',
    'referral.locked_text': '🔒 Реферал пока не зачислен. Приглашённый должен запланировать своё первое сообщение.',
    'referral.notification': '🎉 <b>Новый реферал!</b>\n\nКто-то воспользовался вашей ссылкой!\n\nДни Premium начислятся, когда он запланирует первое сообщение.',
    'referral.failed_notification': 'ℹ️ <b>Обновление по рефералу</b>\n\nКто-то открыл вашу ссылку, но реферал не был засчитан:\n{reason}\n\nДни Premium за этот переход не начислены.',
    'referral.recorded_pending': '⏳ Реферал зафиксирован! Дни Premium начислятся, когда он запланирует первое сообщение.',
    'referral.arrived_via_link': '🎁 <b>Вы пришли по реферальной ссылке!</b>\n\nПодключите канал и запланируйте первое сообщение — вы и пригласивший получите по <b>3 дня Premium</b>.',
    'referral.credited_referee': '✅ Вы получили {days} дн. Premium по реферальной программе!',
    'referral.credited_referrer': '✅ Вы получили {days} дн. Premium за приглашение друга!',
    'referral.no_referrals_yet': '📪 Рефералов пока нет.',
    'referral.your_referred_users': '👥 Ваши приглашённые:',
    'referral.err_self_referral': 'Нельзя пригласить самого себя.',
    'referral.err_already_referred': '❌ Этот аккаунт уже был приглашён другим пользователем.',
    'referral.err_referrer_not_active': '❌ Эта ссылка сейчас неактивна. Пусть отправитель откроет /referral в боте и убедится, что его канал всё ещё подключён, и попробуйте снова.',
    'referral.err_max_reached': '❌ Эта ссылка достигла лимита в 15 приглашённых и больше не даёт дни Premium.',
    'referral.err_generic': '❌ Реферала не удалось применить. Если считаете это ошибкой, напишите в поддержку.',
    'referral.err_qualified_premium': '❌ Ссылка работает только для новых пользователей — у этого аккаунта уже есть Premium.',
    'referral.err_qualified_used_premium': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже пользовался Premium.',
    'referral.err_qualified_scheduled': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже планировал сообщения.',
    'referral.err_qualified_recurring': '❌ Ссылка работает только для новых пользователей — у этого аккаунта уже есть повторяющиеся сообщения.',
    'referral.err_qualified_channel': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже подключал канал.',
    'referral.err_qualified_bot': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже подключал бота-отправителя.',
    'referral.err_qualified_active': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже был активен в боте.',
    'referral.err_qualified_media': '❌ Ссылка работает только для новых пользователей — этот аккаунт уже сохранял медиа в хранилище.',
    'referral.welcome_premium': '🎉 <b>Добро пожаловать!</b>\n\nВы пришли по реферальной ссылке и получили <b>3 дня Premium</b>! Пригласивший тоже получил 3 дня.\n\nПользуйтесь возможностями Premium!',
    'referral.success_status': '✅ Он получил 3 дня Premium! Вы тоже получили 3 дня.',
    'referral.fail_status': '❌ {msg}',
    'referral.copied_alert': '✅ Ссылка скопирована! Поделитесь с друзьями. Когда они зарегистрируются, вы оба получите по 3 дня Premium!',
    # ---- search ----
    'search.btn': '🔍 Поиск',
    'search.title': '🔍 Поиск',
    'search.prompt': '🔍 <b>Поиск по сообщениям</b>\n\nОтправьте ключевое слово или фразу для поиска по вашим сообщениям.\n\nМожно искать по:\n• Тексту сообщения или подписи\n• Названию канала\n• Периоду (например, «на прошлой неделе»)\n• Статусу (отправлено/ожидает/ошибка)',
    'search.no_query': '🔍 Отправьте поисковый запрос:',
    'search.no_results': '🔍 Сообщения не найдены.',
    'search.results_header': '🔍 <b>Результаты поиска</b>\n\nЗапрос: {query}\nНайдено: {count}',
    'search.result_item': '📋 #{id} — {channel}\n{text_preview}\n{i} Статус: {status} — {date}',
    'search.too_many_results': '🔍 Найдено результатов: {count}. Показаны первые {max}:',
    'search.by_channel_prompt': '🔍 Выберите канал для поиска:',
    'search.by_status_prompt': '🔍 Фильтр по статусу:',
    'search.by_date_prompt': '🔍 Фильтр по периоду:',
    'search.all_channels': 'Все каналы',
    'search.status_sent': 'Отправлено',
    'search.status_pending': 'В ожидании',
    'search.status_failed': 'С ошибкой',
    'search.status_all': 'Все',
    'search.advanced_btn': '🔍 Расширенный поиск',
    'search.filters_title': '🔍 <b>Расширенный поиск</b>\n\nФильтры:',
    'search.filter_channel': 'Канал: {channel}',
    'search.filter_status': 'Статус: {status}',
    'search.filter_date': 'Период: {date}',
    'search.no_filters': 'Фильтры не применены',
    'search.clear_filters': '❌ Сбросить фильтры',
    'search.apply_btn': '✅ Применить',
    'search.total_count': 'Всего: {count}',
    'search.too_many_results_warning': 'Слишком много результатов. Уточните запрос.',
    'search.result_click_hint': 'Нажмите на результат, чтобы изменить.',
    'search.result_scheduled': '📅',
    'search.result_sent': '✅',
    'search.result_failed': '❌',
    'search.result_paused': '⏸',
    'search.go_to_msg_btn': '📋 К сообщению',
    'search.prev_btn': '◀ Назад',
    'search.next_btn': 'Далее ▶',
    'search.page_info': 'Страница {page}/{pages}',
    'search.hint': '🔍 Введите запрос...',
    'search.results': '🔍 Результаты по запросу «{query}»:',
    'search.found': '🔍 Найдено результатов: {count}',
    'search.more': '... и ещё {count} сообщ.',
}
