/* Fast Scheduler website — Russian chrome + landing dictionary (separate file).
 * Loaded with `defer` BEFORE lang.js so every string is available
 * synchronously: switching EN->RU translates the whole page instantly,
 * no refresh needed. lang.js merges this over its tiny inline core
 * (settings/nav fallback) and never touches element markup — only text
 * nodes are replaced, so SVG icons, gradients and layout survive.
 *
 * MAP: exact visible EN string -> RU. Only whole-text-node matches apply,
 * so short keys can never corrupt longer sentences.
 * FIXUPS: selector-based replacements for lone words inside formatting
 * tags (e.g. <i>your</i>) and aria-labels that have no safe text key.
 */
(function () {
  'use strict';
  window.FS_RU_CHROME = {
    STR: {
      settings: 'Настройки', dark: 'Тёмная тема', anim: 'Анимации', fx: 'Эффекты',
      keys: 'Горячие клавиши', seeKeys: 'Показать клавиши', help: 'Помощь', support: 'Чат поддержки',
      openBot: 'Открыть бота', langLabel: 'Язык', openHelp: 'Открыть центр помощи',
      recent: 'Недавние запросы', searchPh: 'Поиск по центру помощи…',
      openMenu: 'Открыть меню', closeMenu: 'Закрыть меню'
    },
    META: {
      title: 'Fast Scheduler — автопланирование постов Telegram-канала',
      desc: 'Fast Scheduler — бесплатный Telegram-бот для автопланирования, публикации и аналитики постов канала. Планируйте недели контента в одном чате, публикуйте от своего бота и смотрите, что заходит. Настройте один раз — экономьте часы каждую неделю.'
    },
    MAP: {
      // nav (desktop + mobile sheet)
      'Time saved': 'Экономия времени',
      'Features': 'Возможности',
      'How it works': 'Как это работает',
      'Reviews': 'Отзывы',
      'Pricing': 'Тарифы',
      'FAQ': 'Вопросы и ответы',
      'Blog': 'Блог',
      'Help': 'Помощь',
      'Help Center': 'Центр помощи',
      'Open Bot': 'Открыть бота',
      // hero (split across inline tags — part keys keep <span>/<b> intact)
      'Your channel': 'Ваш канал',
      'posts itself.': 'публикуется сам.',
      'You just write.': 'Вы просто пишете.',
      'Paste a week of posts into one chat —': 'Вставьте неделю постов в один чат —',
      'publishes each one at the exact time you chose, in your timezone, from': 'публикует каждый в точное выбранное время, в вашем часовом поясе, от',
      'your own bot': 'вашего собственного бота',
      '. Set it once, then get on with life.': '. Настройте один раз — и занимайтесь жизнью.',
      'Start free — it takes 60 seconds': 'Начать бесплатно — это займёт 60 секунд',
      'No app. No signup. Works inside Telegram you already use.': 'Без приложений. Без регистрации. Работает в привычном Telegram.',
      '↺ Replay demo': '↺ Смотреть демо ещё раз',
      'Free plan forever': 'Бесплатный тариф навсегда',
      'Posts from your own bot': 'Посты от вашего бота',
      'Your timezone, not ours': 'Ваш часовой пояс, а не наш',
      'No card required': 'Карта не нужна',
      'Scheduled in one chat.': 'Запланировали в одном чате.',
      'Posted forever.': 'Публикуется всегда.',
      'Fast Scheduler delivered this post at 18:15 sharp — while its owner was away. Your channel can run like this too.': 'Fast Scheduler опубликовал этот пост ровно в 18:15 — пока владелец был офлайн. Ваш канал тоже так может.',
      'One chat in. Your whole week, published right on time.': 'Один чат. Вся неделя — вовремя.',
      // marquee
      'News channels': 'Новостные каналы',
      'Shop drops': 'Дропы магазинов',
      'Course creators': 'Авторы курсов',
      'Artists & commissions': 'Художники и заказы',
      'Trading signals': 'Торговые сигналы',
      'Podcast releases': 'Выпуски подкастов',
      'Community digests': 'Дайджесты сообществ',
      'Startup updates': 'Новости стартапов',
      // time-saved band
      'How much time you get back': 'Сколько времени вы вернёте',
      'Posting manually every day means opening Telegram, drafting, double-checking and sending — daily. Scheduling means doing it': 'Постить вручную каждый день — значит открывать Telegram, писать, проверять и отправлять. Каждый день. А планировать — значит делать это',
      'once a week': 'раз в неделю',
      'saved every week on daily posting (vs manual sending)': 'экономии каждую неделю на ежедневном постинге (вместо ручной отправки)',
      '1 chat': '1 чат',
      'for a whole month of posts via batch scheduling': 'на целый месяц постов благодаря пакетному планированию',
      'missed posts — delivery runs even while you sleep': 'пропущенных постов — доставка работает, даже пока вы спите',
      'Every hour you don\'t spend reposting is an hour for content, community — or actually resting.': 'Каждый час без репостов — это час на контент, сообщество или просто отдых.',
      // features
      'Everything a channel needs, in one chat': 'Всё для канала — в одном чате',
      'Not a stripped-down demo bot. A full scheduling studio that happens to live in Telegram.': 'Не урезанное демо, а полноценная студия планирования, которая живёт в Telegram.',
      'Batch scheduling': 'Пакетное планирование',
      'Send many': 'Отправляйте сразу много',
      'date + message': '«дата + сообщение»',
      'pairs in a single message and create weeks of posts in one conversation. Preview everything before it goes live.': 'пар одним сообщением и создавайте посты на недели вперёд в одном диалоге. Проверяйте всё перед публикацией.',
      'saves hours': 'экономит часы',
      'Recurring posts': 'Регулярные посты',
      '"Every day at 9:00" or any cron schedule — digests, drops and reminders repeat themselves until you say stop. Pause and resume anytime.': '«Каждый день в 9:00» или любое cron-расписание — дайджесты, дропы и напоминания повторяются сами, пока вы не скажете «стоп». Пауза и продолжение в любой момент.',
      'set & forget': 'настроил и забыл',
      'Rich media posts': 'Посты с медиа',
      'Photos, videos, albums, GIFs, polls, quizzes, documents, locations — with full formatting and inline URL buttons.': 'Фото, видео, альбомы, GIF, опросы, викторины, документы, геопозиции — с полным форматированием и inline-кнопками.',
      'Stats & leaderboards': 'Статистика и рейтинги',
      'Views, comments, reactions per post — paginated top-posts and top-commentator leaderboards so you double down on what works.': 'Просмотры, комментарии и реакции по каждому посту — топ постов и топ комментаторов, чтобы усиливать то, что работает.',
      'Post from your own bot': 'Публикация от вашего бота',
      'Connect your bot\'s token once and every scheduled post is published through it — your brand, your name, on every message.': 'Подключите токен вашего бота один раз — и каждый запланированный пост выйдет через него: ваш бренд, ваше имя в каждом сообщении.',
      'Your timezone, your rules': 'Ваш часовой пояс, ваши правила',
      'Pick your timezone once — "9:00" means your 9:00 forever. Reports arrive on your schedule, not a server\'s.': 'Выберите часовой пояс один раз — «9:00» навсегда означает ваши 9:00. Отчёты приходят по вашему расписанию, а не по серверному.',
      'Auto reports': 'Автоматические отчёты',
      'Daily, weekly or monthly performance reports delivered straight to your chat — no dashboards to open, no checking manually.': 'Ежедневные, еженедельные или ежемесячные отчёты — прямо в ваш чат. Никаких дашбордов и ручных проверок.',
      'Multi-channel + team admins': 'Мультиканальность и команда',
      'Manage several channels from one bot. Add trusted admins with per-channel permissions so nobody steps on toes.': 'Управляйте несколькими каналами из одного бота. Добавляйте доверенных админов с правами на каждый канал — никто никому не мешает.',
      'Encrypted backups': 'Зашифрованные бэкапы',
      'Export everything as a password-encrypted file (AES-256-GCM) and restore on any device. Your content, portable and safe.': 'Выгружайте всё в зашифрованный паролем файл (AES-256-GCM) и восстанавливайте на любом устройстве. Ваш контент — портативный и защищённый.',
      // how it works
      'Three steps. Sixty seconds.': 'Три шага. Шестьдесят секунд.',
      'No app to install, no dashboard to learn — if you can send a Telegram message, you already know how to use it.': 'Ничего устанавливать не нужно — если умеете отправлять сообщения в Telegram, вы уже умеете этим пользоваться.',
      'Open the bot & connect a channel': 'Откройте бота и подключите канал',
      'Tap Start, add the bot as an admin to your channel. Pick your timezone so 9:00 always means': 'Нажмите Start, добавьте бота в администраторы канала. Выберите часовой пояс, чтобы 9:00 всегда означало',
      '9:00.': '9:00.',
      'Schedule one post or fifty': 'Запланируйте один пост или пятьдесят',
      'Send one date with its message — or paste several date + message blocks at once. Review, pick a photo mode, confirm: done.': 'Отправьте одну дату с сообщением — или вставьте сразу несколько блоков «дата + сообщение». Проверьте, выберите режим фото, подтвердите — готово.',
      'Live your life': 'Живите своей жизнью',
      'Posts publish themselves — even while you sleep. Stats and reports find you, so you always know what performed.': 'Посты публикуются сами — даже пока вы спите. Статистика и отчёты сами находят вас, так что вы всегда знаете, что сработало.',
      // reviews
      'Channels that stopped posting by hand': 'Каналы, которые перестали публиковать вручную',
      '"I batch-schedule the entire week every Sunday in about 10 minutes. Used to spend half an hour': '«Я планирую всю неделю каждое воскресенье примерно за 10 минут. Раньше тратил полчаса',
      'every day': 'каждый день',
      'remembering to post. Best trade I\'ve made."': 'на то, чтобы не забыть запостить. Лучший обмен в моей жизни».',
      '19K subscriber news channel': 'новостной канал, 19K подписчиков',
      '"Posting through my own bot was the deal-maker — it still looks 100% like my brand. The leaderboards showed me my 9PM posts get 3× the views."': '«Публикация через собственного бота решила всё — это по-прежнему на 100% выглядит как мой бренд. Рейтинги показали: посты в 21:00 собирают в 3 раза больше просмотров».',
      'shop drops channel': 'канал с дропами магазина',
      '"The weekly report just shows up in my chat. I don\'t chase analytics anymore — I read one message with coffee and adjust the plan."': '«Недельный отчёт просто появляется в чате. Я больше не гоняюсь за аналитикой — читаю одно сообщение за кофе и корректирую план».',
      'podcast & community': 'подкасты и сообщество',
      // pricing
      'Start free. Upgrade when it pays for itself.': 'Начните бесплатно. Переходите на Premium, когда окупится.',
      'Free is a real plan, not a trial. Premium is for channels that want the full studio.': 'Free — настоящий тариф, а не пробник. Premium — для каналов, которым нужна полная студия.',
      'Yearly': 'Год',
      'Monthly': 'Месяц',
      'Best value': 'Выгоднее всего',
      'forever — no card': 'навсегда — без карты',
      '1 channel + 1 sender bot': '1 канал + 1 бот-отправитель',
      'Up to 100 pending scheduled messages': 'До 100 отложенных запланированных сообщений',
      'Basic statistics': 'Базовая статистика',
      '100 sends / channel / month': '100 отправок / канал / месяц',
      'Start free': 'Начать бесплатно',
      '1 Month': '1 месяц',
      'full power, cancel anytime': 'полная мощность, отмена в любой момент',
      '3 channels + 3 sender bots': '3 канала + 3 бота-отправителя',
      'Unlimited sends & recurring posts': 'Безлимитные отправки и регулярные посты',
      'Leaderboards + custom auto reports': 'Рейтинги + автоотчёты под заказ',
      'Encrypted backup & export': 'Зашифрованный бэкап и экспорт',
      'Choose plan': 'Выбрать тариф',
      '3 Months': '3 месяца',
      'one payment': 'один платёж',
      '/ 3mo': '/ 3 мес',
      'Everything in Monthly': 'Всё из месячного тарифа',
      '≈ $6.15 / month': '≈ $6.15 / месяц',
      'vs $20.49 monthly': 'вместо $20.49 в месяц',
      '6 Months': '6 месяцев',
      '/ 6mo': '/ 6 мес',
      '≈ $5.94 / month': '≈ $5.94 / месяц',
      'vs $40.98 monthly': 'вместо $40.98 в месяц',
      'Best value −17%': 'Выгоднее всего −17%',
      '1 Year': '1 год',
      'one payment, no renewals': 'один платёж, без продлений',
      '/ yr': '/ год',
      '/mo': '/мес',
      '≈ $5.67 / month': '≈ $5.67 / месяц',
      'vs $81.96 monthly': 'вместо $81.96 в месяц',
      'Payments handled entirely by Telegram Stars. We never see your card.': 'Оплата полностью через Telegram Stars. Мы никогда не видим вашу карту.',
      'Refund policy': 'Политика возвратов',
      'Full plan comparison': 'Полное сравнение тарифов',
      // comparison table (rendered by main.js AFTER lang.js — observer catches it)
      'Pending scheduled messages': 'Отложенные запланированные сообщения',
      'Messages sent / month': 'Отправок сообщений / месяц',
      'Feature': 'Функция',
      'Unlimited': 'Безлимит',
      'Recurring messages': 'Регулярные посты',
      'Scheduled messages': 'Запланированные сообщения',
      'Monthly sends': 'Отправки в месяц',
      'Videos in storage': 'Видео в хранилище',
      'No': 'Нет',
      'Signatures': 'Подписи',
      '1 free trial': '1 пробная',
      'Multi-date scheduling': 'Планирование на несколько дат',
      'Media storages': 'Медиахранилища',
      'Connected channels': 'Подключённые каналы',
      'Sender bots': 'Боты-отправители',
      'Video uploads': 'Загрузка видео',
      'Max media size': 'Макс. размер медиа',
      '4K media': 'Медиа 4K',
      'Statistics': 'Статистика',
      'Basic': 'Базовая',
      'Advanced': 'Продвинутая',
      'Search': 'Поиск',
      'Included': 'Включено',
      'Calendar': 'Календарь',
      'Backup & export': 'Бэкап и экспорт',
      'Leaderboard': 'Рейтинг',
      'Reports': 'Отчёты',
      'Plan Comparison': 'Сравнение тарифов',
      // faq (summaries already known; answers are new)
      'Questions, answered': 'Вопросы и ответы',
      'Is Fast Scheduler really free?': 'Fast Scheduler действительно бесплатный?',
      'Yes. The free plan connects 1 channel and 1 sender bot with up to 100 pending scheduled messages and 100 sends per channel per month. Premium raises limits and unlocks leaderboards and custom reports — but you can run a small channel on Free forever.': 'Да. Бесплатный тариф подключает 1 канал и 1 бота-отправителя: до 100 отложенных сообщений и 100 отправок на канал в месяц. Premium поднимает лимиты и открывает рейтинги и автоотчёты — но небольшой канал можно вести на Free вечно.',
      'How does it save me time?': 'Как он экономит моё время?',
      'Batch-scheduling turns "post every day" into one weekly 10-minute session: paste a week of date+message pairs in a single chat. Recurring posts make daily digests fully automatic, and reports come to you instead of you hunting analytics.': 'Пакетное планирование превращает «постить каждый день» в одну 10-минутную сессию в неделю: вставьте неделю пар «дата+сообщение» в один чат. Регулярные посты делают ежедневные дайджесты полностью автоматическими, а отчёты приходят к вам сами.',
      'Do posts come from my own bot?': 'Посты выходят от моего бота?',
      'Yes — create a bot in @BotFather, connect it once, and every scheduled post is published through it, keeping your brand on every message. The sender bot is required: scheduling unlocks only after your channel has one (the main bot steps in only as an emergency fallback if your bot\'s token fails).': 'Да — создайте бота через @BotFather, подключите один раз, и каждый запланированный пост выйдет через него, сохраняя ваш бренд в каждом сообщении. Бот-отправитель обязателен: планирование открывается только после его подключения (основной бот подхватит лишь как экстренный запасной вариант, если токен вашего бота перестанет работать).',
      'Will posts go out if I\'m offline or asleep?': 'Выйдут ли посты, если я офлайн или сплю?',
      'Yes. Scheduling happens on the bot\'s side: once a message is queued it publishes at the exact time you chose, in your timezone, whether you\'re online or not.': 'Да. Планирование работает на стороне бота: как только сообщение в очереди, оно публикуется точно в выбранное время в вашем часовом поясе — онлайн вы или нет.',
      'Can I see who comments on my posts?': 'Видно ли, кто комментирует мои посты?',
      'Premium leaderboards rank your top posts by views, comments and reactions, plus a top-commentators ranking. Add the bot to your channel\'s discussion group and it attributes comment authors automatically.': 'Premium-рейтинги ранжируют ваши топ-посты по просмотрам, комментариям и реакциям, плюс рейтинг топ-комментаторов. Добавьте бота в группу обсуждений канала — и авторы комментариев определятся автоматически.',
      'Is my data safe?': 'Мои данные в безопасности?',
      'Bot tokens are encrypted at rest, backups support AES-256-GCM password encryption, and you can export or delete everything at any time. See our': 'Токены ботов шифруются при хранении, бэкапы поддерживают шифрование паролем AES-256-GCM, а выгрузить или удалить всё можно в любой момент. Подробнее — в нашей',
      // final CTA + footer
      'Your next post is': 'Ваш следующий пост',
      'already scheduled': 'уже запланирован',
      'Or you\'re still posting it by hand every day. Sixty seconds now — weeks of autopilot after.': 'Или вы всё ещё публикуете вручную каждый день. Шестьдесят секунд сейчас — недели автопилота потом.',
      'Open Fast Scheduler in Telegram': 'Открыть Fast Scheduler в Telegram',
      'Open Fast Scheduler': 'Открыть Fast Scheduler',
      'In Telegram': 'В Telegram',
      'Privacy': 'Конфиденциальность',
      'Terms': 'Условия',
      'Refunds': 'Возвраты',
      '© 2026 Fast Scheduler · Made for Telegram channels': '© 2026 Fast Scheduler · Сделано для Telegram-каналов',
      // shared chrome (help/blog/legal/404)
      'Free': 'Бесплатно',
      'Premium': 'Premium',
      'per month': 'в месяц',
      'Get started': 'Начать',
      'Try the bot': 'Попробовать бота',
      'Open Help Center': 'Открыть центр помощи',
      'Recent searches': 'Недавние запросы',
      'Search the help center…': 'Поиск по центру помощи…',
      'Search docs…': 'Поиск по документам…',
      'All articles': 'Все статьи',
      'Was this helpful?': 'Было ли это полезно?',
      'Yes': 'Да',
      'Previous': 'Назад',
      'Next': 'Далее',
      'Table of contents': 'Содержание',
      'On this page': 'На этой странице',
      'Privacy Policy': 'Политика конфиденциальности',
      'Terms of Service': 'Условия использования',
      'Refund Policy': 'Политика возвратов',
      'Settings': 'Настройки',
      'Dark mode': 'Тёмная тема',
      'Animations': 'Анимации',
      'Effects': 'Эффекты',
      'Hotkeys': 'Горячие клавиши',
      'See hotkeys': 'Показать клавиши',
      'Support chat': 'Чат поддержки',
      'Language': 'Язык',
      'Back to top': 'Наверх',
      'Back to blog': 'Назад в блог',
      'Back to help': 'Назад в помощь',
      'Related articles': 'Похожие статьи',
      'Read more': 'Читать далее',
      'min read': 'мин чтения',
      'Last updated': 'Обновлено',
      'Page not found': 'Страница не найдена',
      'Go home': 'На главную',
      'All topics': 'Все темы',
      'Growth': 'Рост',
      'Content': 'Контент',
      'Bots & Tools': 'Боты и инструменты',
      'Premium & Safety': 'Premium и безопасность',
      'Platform': 'Платформа',
      'Monetization': 'Монетизация',
      'Subscribers, swaps, discoverability and retention — the playbooks that compound.': 'Подписчики, свапы, поиск и удержание — стратегии, которые работают на перспективу.',
      'Formatting, calendars and content systems that keep a channel alive.': 'Оформление, календари и контент-системы, которые держат канал на плаву.',
      'The bot stack behind successful channels — scheduling, analytics, moderation.': 'Стек ботов успешных каналов — планирование, аналитика, модерация.',
      'Verification, Premium perks, Mini Apps — the platform layer behind channels.': 'Верификация, преимущества Premium, Mini Apps — платформа за кулисами каналов.',
      'How Telegram itself works: channels vs groups, bot safety, algorithms.': 'Как устроен сам Telegram: каналы и группы, безопасность ботов, алгоритмы.',
      'Ads, Stars, subscriptions and products — what pays, and when.': 'Реклама, Stars, подписки и товары — что приносит деньги и когда.'
    },
    // Selector-based fixups: [selector, attribute|null, EN, RU].
    // For lone words inside formatting tags and aria-labels with no safe key.
    FIXUPS: [
      ['#how .step p i', null, 'your', 'ваши'],
      ['#carPrev', 'aria-label', 'Previous plan', 'Предыдущий тариф'],
      ['#carNext', 'aria-label', 'Next plan', 'Следующий тариф'],
      ['.stars', 'aria-label', 'Rated 5 out of 5', 'Оценка 5 из 5']
    ]
  };
})();
