// AUTO-GENERATED by website/_build/build_site.py — do not edit by hand.
// Source of truth: src/core/plans.py, src/core/config.py, translations/en.json
window.SITE_CONFIG = {
  botUsername: "FastSchedulerBot",
  mail: "support@fastestschedule.com",
  mediaStorageEnabled: true,
  prices: {
    monthlyCents: 999,
    yearlyCents: 9999,
    monthlyUSD: "$9.99",
    yearlyUSD: "$99.99",
    yearlyMonthlyEquivalentUSD: "$8.33",
    savingsPercent: 17,
    savingsText: "2 MONTHS FREE - Save 17%"
  },
  plans: {
    free: { label: "Free", priceMonthly: "$0", priceYearly: "$0" },
    premium: {
      label: "Premium",
      priceMonthly: "$9.99",
      priceYearly: "$99.99",
      priceYearlyMonthly: "$8.33",
      savingsPercent: 17
    },
    rows: []
  },
  placeholders: {"OPERATOR_LEGAL_NAME": "Fast Scheduler", "OPERATOR_REGISTERED_ADDRESS": "—", "COMPANY_REGISTRATION_NUMBER": "—", "PRIVACY_CONTACT_EMAIL": "privacy@fastestschedule.com", "SUPPORT_TELEGRAM_HANDLE_OR_LINK": "@FastSchedulerBot", "WEBSITE": "", "CONTACT_EMAIL": "support@fastestschedule.com", "LEGAL_CONTACT_EMAIL": "legal@fastestschedule.com", "GOVERNING_JURISDICTION": "your jurisdiction", "JURISDICTION_VENUE": "local courts", "RESPONSE_WINDOW_EG_5_BUSINESS_DAYS": "5 business days", "EG_5_10_BUSINESS_DAYS": "5–10 business days", "EG_7_BUSINESS_DAYS": "7 business days", "DATE": "September 15, 2026", "KV_NAMESPACES": "your Cloudflare account"},
  comparisonHTML: ""
};
