# -*- coding: utf-8 -*-
MAP3 = [
('Replace Token','Reemplazar token'),
('Change Channel','Cambiar canal'),
('Could not change channel.','No se pudo cambiar el canal.'),
('Changelog','Cambios'),
('Change Bot','Cambiar bot'),
('Changelog not found.','Sin cambios.'),
('unknown','desconocida'),
('Visible (','Visible ('),
('Visibility:','Visibilidad:'),
('The bot must be an admin in this channel.','El bot debe ser admin de este canal.'),
('Channel:','Canal:'),
('You must be an admin in this channel.','Debes ser admin de este canal.'),
('No message received. Please send a channel link or ID.','Sin mensaje. Manda enlace o ID del canal.'),
('Channel managed via sender bot','Canal gestionado por bot remitente'),
('Stats','Stats'),
('Recurring','Recurrentes'),
('Channel hidden from strangers','Canal oculto a extraños'),
('Channel visible to strangers again','Canal visible a extraños de nuevo'),
('Channel is now visible to strangers.','Canal ahora visible a extraños.'),
('channel(s) connected.','canal(es) conectados.'),
('Chat with Admin','Chat con admin'),
('Check Again','Revisar de nuevo'),
('Add Bot as Admin','Añadir bot como admin'),
('Check Admin Status','Ver estado admin'),
('Check Subscription','Ver suscripción'),
('Checklist','Checklist'),
('Create a Checklist','Crear checklist'),
('Enter the checklist title:','Pon título al checklist:'),
('Timezone','Zona horaria'),
('Choose','Elegir'),
('Filter:','Filtro:'),
('Clear Default','Quitar por defecto'),
('Command not found.','Comando no encontrado.'),
('Category','Categoría'),
('Description','Descripción'),
('Status','Estado'),
('Open','Abierto'),
('Replied','Respondido'),
('Spam','Spam'),
('Created','Creado'),
('User','Usuario'),
('Error submitting feedback:','Error al enviar opinión:'),
('Not found.','No encontrado.'),
('Please describe your issue.','Describe tu problema.'),
('No attachments','Sin adjuntos'),
('Attachments','Adjuntos'),
('View attached files','Ver adjuntos'),
('Attachments sent.','Adjuntos enviados.'),
('Marked as spam.','Marcado como spam.'),
('You can submit feedback once every 30 seconds.','Puedes opinar cada 30 segundos.'),
('File exceeds the','El archivo supera'),
('size limit.','límite.'),
('Total attachments exceed the','Total supera'),
('You can attach up to','Puedes adjuntar hasta'),
('files per feedback.','archivos por opinión.'),
('Submit Feedback','Enviar opinión'),
('Feedback Submitted','Opinión enviada'),
('Media removed by admin','Medios borrados por admin'),
('No media files to submit.','Sin medios para enviar.'),
('Reply submitted.','Respuesta enviada.'),
('Cannot block an admin.','No puedes bloquear a un admin.'),
('Cannot modify another admin','No puedes cambiar Premium de otro admin'),
('Bots (','Bots ('),
('Bots','Bots'),
('bot','bot'),
('Build:','Build:'),
('View Day','Ver día'),
('Select a day','Elige un día'),
('No messages on this day.','Sin mensajes este día.'),
('Reason:','Motivo:'),
('Additional details:','Detalles:'),
('Error submitting cancellation:','Error al cancelar:'),
('Checklist','Checklist'),
(' собой ',' '),
]
def tr3(s):
    t = s
    for en_, es_ in MAP3:
        t = t.replace(en_, es_)
    return t
