# -*- coding: utf-8 -*-
MAP4 = [
('Manage','Gestionar'),
('View','Ver'),
('Select','Elegir'),
('Create','Crear'),
('Remove','Quitar'),
('Delete','Borrar'),
('Edit','Editar'),
('Search','Buscar'),
('Submit','Enviar'),
('Confirm','Confirmar'),
('Cancel','Cancelar'),
('Change','Cambiar'),
('Replace','Reemplazar'),
('Connect','Conectar'),
('Disconnect','Desconectar'),
('Restore','Restaurar'),
('Export','Exportar'),
('Import','Importar'),
('Backup','Copia'),
('Channel','Canal'),
('Bot','Bot'),
('Message','Mensaje'),
('Messages','Mensajes'),
('Settings','Ajustes'),
('Statistics','Estadísticas'),
('Premium','Premium'),
('Language','Idioma'),
('Timezone','Zona horaria'),
('Storage','Almacén'),
('Media','Medios'),
('Report','Reporte'),
('Feedback','Opinión'),
('Support','Soporte'),
('Help','Ayuda'),
('Error','Error'),
('Failed','Falló'),
('Success','Éxito'),
('Successful','Con éxito'),
('Available','Disponible'),
('Selected','Elegido'),
('Connected','Conectado'),
('Disconnected','Desconectado'),
('Hidden','Oculto'),
('Visible','Visible'),
('Active','Activo'),
('Expired','Expirado'),
('Today','Hoy'),
('Tomorrow','Mañana'),
('Yesterday','Ayer'),
('Week','Semana'),
('Month','Mes'),
('Year','Año'),
('Day','Día'),
('Time','Hora'),
('Date','Fecha'),
('User','Usuario'),
('Admin','Admin'),
('Owner','Dueño'),
('Members','Miembros'),
(' Buddhism ',' '),
]
def tr4(s):
    t = s
    for en_, es_ in MAP4:
        t = t.replace(en_, es_)
    return t
