# -*- coding: utf-8 -*-
MAP = [
('Add More Media','Añadir más medios'),
('Add Storage','Añadir almacén'),
('Add Media','Añadir medios'),
('Add Promo Code','Añadir código promo'),
('Add Report','Añadir reporte'),
('Share Bot','Compartir bot'),
('Choose which bot to share:','Elige qué bot compartir:'),
('Or share the channel connection:','O comparte la conexión del canal:'),
('All your channels already have bots connected.','Tus canales ya tienen bots conectados.'),
('Bot share link generated.','Enlace de bot generado.'),
('Send me your bot token (from @BotFather):','Envíame tu token (de @BotFather):'),
('Remove Bot?','¿Quitar bot?'),
('Could not remove bot.','No se pudo quitar el bot.'),
('Replace Bot','Reemplazar bot'),
('Bot Connected!','¡Bot conectado!'),
('is now managing','ahora gestiona'),
('Bots Connected!','¡Bots conectados!'),
('Create New Bot','Crear nuevo bot'),
('I Have a Token','Tengo un token'),
('Failed to create bot.','No se pudo crear el bot.'),
('Connect Sender Bot','Conectar bot remitente'),
('Connect Bot','Conectar bot'),
('Bot has been disconnected successfully.','Bot desconectado con éxito.'),
('Album','Álbum'),
('All','Todos'),
('All features unlocked','Todas las funciones desbloqueadas'),
('Announcement','Anuncio'),
('Creating archive...','Creando archivo...'),
('Are you sure?','¿Seguro?'),
('This cannot be undone.','Esto no se puede deshacer.'),
('Auto-Renewal','Auto-renovación'),
('AutoTime','AutoHora'),
('Select a channel to analyze:','Elige un canal para analizar:'),
('Analyzing channel activity... This may take a moment.','Analizando actividad... Un momento.'),
('Apply This Time','Aplicar esta hora'),
('set to','puesto a'),
('for','para'),
('Could not analyze channel activity.','No se pudo analizar.'),
('Analyze','Analizar'),
('Cancel AutoTime','Cancelar AutoHora'),
("Don't show again",'No mostrar más'),
('AutoTime promo hidden.','Promo AutoHora oculta.'),
('AutoTime promo enabled.','Promo AutoHora activa.'),
('AutoTime promo is now visible.','Promo AutoHora visible.'),
('Main Menu','Menú principal'),
('Back to Files','Volver a archivos'),
('Back to Main','Volver al inicio'),
('Back to Premium Menu','Volver a Premium'),
('No','No'),
('Violation of the bot','Violación de las reglas'),
('is back online and managing','volvió en línea y gestiona'),
('Assign','Asignar'),
('Back','Atrás'),
('Cancel','Cancelar'),
('Close','Cerrar'),
('Done','Listo'),
('Edit','Editar'),
('Delete','Borrar'),
('Send','Enviar'),
('Save','Guardar'),
('Next','Siguiente'),
('Skip','Omitir'),
('Confirm','Confirmar'),
('Retry','Reintentar'),
('Refresh','Actualizar'),
('Settings','Ajustes'),
('Help','Ayuda'),
('Support','Soporte'),
('Premium','Premium'),
('Language','Idioma'),
('Channels','Canales'),
('Bots','Bots'),
('Statistics','Estadísticas'),
('Schedule','Programar'),
('Yes','Sí'),
]
def tr(s):
    t = s
    for en_, es_ in MAP:
        t = t.replace(en_, es_)
    return t
