#!/usr/bin/env python3
"""Give the help hub a preview image.

help.html is the only content page carrying og:type/og:title/og:description but
no og:image, so every shared link to the help center rendered as a text-only
preview while every other page got the card. It also never declared og:url or
twitter:card.

The block is generated by _build/build_help.py, so both the template and the
already-built pages are patched: re-running build_help.py would otherwise drop
the metas again. Matches the index.html block (og:url, og:image with explicit
dimensions, twitter:card summary_large_image, twitter:title/description/image).

    python tools/fix_help_og.py           # apply
    python tools/fix_help_og.py --check   # report only, exit 1 if work remains
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://fastschedulebot.github.io/Fast-Schedule"
CANON = f"{SITE}/help.html"
IMAGE = f"{SITE}/og-cover-v2.png"
TITLE = "Help Center — Fast Scheduler for Telegram"

# The hub is the one page whose description is computed rather than literal, so
# match on the stable tail rather than the whole attribute.
ANCHOR = re.compile(
    r'^(?P<i>[ \t]*)<meta property="og:description" content="'
    r'(?P<desc>[^"]*searchable help topics for the Fast Scheduler Telegram bot\.)"'
    + ">" + r'[ \t]*\n',
    re.M,
)

TARGETS = [
    ROOT / "_build" / "build_help.py",
    ROOT / "website" / "_build" / "build_help.py",
    ROOT / "website" / "help.html",
    ROOT / "help.html",
]


def block(indent: str, desc: str) -> str:
    return (
        f'{indent}<meta property="og:url" content="{CANON}">\n'
        f'{indent}<meta property="og:image" content="{IMAGE}">\n'
        f'{indent}<meta property="og:image:width" content="1200">\n'
        f'{indent}<meta property="og:image:height" content="630">\n'
        f'{indent}<meta name="twitter:card" content="summary_large_image">\n'
        f'{indent}<meta name="twitter:title" content="{TITLE}">\n'
        f'{indent}<meta name="twitter:description" content="{desc}">\n'
        f'{indent}<meta name="twitter:image" content="{IMAGE}">\n'
    )


def patch(text: str) -> tuple[str, int]:
    n = 0

    def one(m: re.Match[str]) -> str:
        nonlocal n
        indent = m.group("i")
        after = text[m.end():m.end() + 400]
        # Already done: the og:url line immediately follows the anchor.
        if f'<meta property="og:url"' in after.split("\n\n")[0]:
            return m.group(0)
        n += 1
        return m.group(0) + block(indent, m.group("desc"))

    return ANCHOR.sub(one, text), n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    changed: list[tuple[Path, int]] = []
    for path in TARGETS:
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        new, n = patch(text)
        if not n:
            continue
        if not args.check:
            path.write_text(new, encoding="utf-8", newline="")
        changed.append((path.relative_to(ROOT), n))

    total = sum(n for _, n in changed)
    out = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    if not changed:
        print("help hub OG metas already complete.", file=out)
        return 0
    print(f'{"would add" if args.check else "added"} {total} meta block(s) to '
          f"{len(changed)} file(s):", file=out)
    for rel, n in changed:
        print(f"  {rel} ({n})", file=out)
    if args.check:
        print("--check: work remains.", file=out)
        return 1
    print("done.", file=out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())